### ISSUE TITLE
Delve unable to launch process in Neovim or Command Line on M3 Apple Silicon

### ISSUE THREAD

**Issue by clm-whyte** [go-delve/delve#3681] opened 2024-03-06 11:19 UTC
I'm very new to Go, so I'm absolutely willing to accept that I've messed something up here.
However, I find it odd that debugging in VS Code works correctly.
I wouldn't be wholly suprprised if it was something to do with me modifyiung the GOPATH from the default.
```
go env GOPATH
/Users/cmaciver-whyte/Projects/go
```

- What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.22.1
Build: $Id: 0c3470054da6feac5f6dcf3e3e5144a64f7a9a48 $
```
- What version of Go are you using? (`go version`)?
```
go version go1.22.0 darwin/arm64
```

- What operating system and processor architecture are you using?
```
Chip: Apple M3 Max
macOS: Sonoma 14.3.1
```

- What did you do?
I was configuring Neovim for Go, following this [video](https://youtu.be/i04sSQjd-qo?si=5X5tlDqQKsbB_gn0), however, when trying to debug a test, I get the error:

> Error on launch: Failed to launch: could not launch process: stub exited while waiting for connection: exit status 0

I don't believe it's an issue with my Neovim config, as running `dlv test` in the command line results in the same error.

- What did you expect to see?
My test run and stop at the breakpoint

What did you see instead?
> Error on launch: Failed to launch: could not launch process: stub exited while waiting for connection: exit status 0

**Comment by aarzilli** [comment] 2024-03-06 11:41
You probably didn't follow the [install instructions for macOS](https://github.com/go-delve/delve/blob/master/Documentation/installation/README.md#macos-considerations) or you are debugging through ssh (which apple makes difficult) or there is a problem with your install of X-code.
Closing, duplicate of #3056.

**Closed by aarzilli** 2024-03-06 11:41 UTC

**Comment by aarzilli** [comment] 2024-03-06 11:45
PS. you can also see the list of issues that reference back to #3056 for other possible problems that cause this.

**Comment by clm-whyte** [comment] 2024-03-06 11:53
I've re-installed `xcode-select`, enabled `DevToolsSecurity` and  added myself to the developer group.
I'm not debugging through SSH, or at least not intentionally...I'm not even sure how I would do that.

Thanks for linking those issues, I'll take a look. But almost every resolution I saw before was to do with people using AMD64 instead of ARM.

**Comment by FanchenBao** [comment] 2024-08-01 02:19
Same issue here with M3 and macOS 14.5. Followed each step in the [installation instructions for macOS](https://github.com/go-delve/delve/blob/master/Documentation/installation/README.md#macos-considerations), but still faced the same problem.
