### ISSUE TITLE
debugger Error reading debug_info: concrete subprogram without address range at 0x4fce5e

### ISSUE THREAD

**Issue by adibrastegarnia** [go-delve/delve#1765] opened 2019-11-21 16:25 UTC
@aarzilli 
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Latest version from master branch

2. What version of Go are you using? (`go version`)?
go 1.12.5
3. What operating system and processor architecture are you using?
Mac os
4. What did you do?
I ran the following command in a docker container to deploy an image in k8s 
`"dlv --listen=:40000 --headless=true --accept-multiclient=true --api-version=2 --log exec /usr/local/bin/app-debug -- \"\$@\"" >> /usr/local/bin/app-debug && `
5. What did you expect to see?
A running program without debug errors  
6. What did you see instead?
```

2019-11-21T16:21:29Z error layer=debugger Error reading debug_info: could not find abstract origin (0x4fce2e) of inlined call at 0x4fcc6b
2019-11-21T16:21:29Z error layer=debugger Error reading debug_info: could not find abstract origin (0x4fcdf5) of inlined call at 0x4fcd78
2019-11-21T16:21:29Z error layer=debugger Error reading debug_info: concrete subprogram without address range at 0x4fce5e
2019-11-21T16:21:29Z error layer=debugger Error reading debug_info: concrete subprogram without address range at 0x4fce69
2019-11-21T16:21:29Z error layer=debugger Error reading debug_info: concrete subprogram without address range at 0x4fce75
2019-11-21T16:21:29Z error layer=debugger Error reading debug_info: concrete subprogram without address range at 0x4fce80
2019-11-21T16:21:29Z error layer=debugger Error reading debug_info: concrete subprogram without address range at 0x4fce8b
```

What could be wrong?

**Comment by aarzilli** [comment] 2019-11-22 07:38
Nothing looks particularly wrong, those errors are caused by cgo and should be ignorable. We should probably make them look less scary.

**Comment by adibrastegarnia** [comment] 2019-11-22 14:49
@aarzilli 
Thanks. But In the client side, we can set breakpoints for some of the files but not for some others. I thought that error somehow related because it cannot find a subprogram. Do you think it is related?

**Comment by aarzilli** [comment] 2019-11-22 15:51
Maybe. What error are you getting and can I see the binary file you are debugging?

**Comment by adibrastegarnia** [comment] 2019-11-22 16:01
We use delve for remote debugging in k8s cluster. We use port forwarding to forward requests from local machine to the debug image that runs something like this:
`"dlv --listen=:40000 --headless=true --accept-multiclient=true --continue --api-version=2"

And we use this command like this to build the binary for a go project: 
`CGO_ENABLED=1 go build -gcflags "all=-N -l" -o build/_output/app ./cmd/app`

In the GolandIDE, we can connect to the debugger and it is continuing in the server side, but the breakpoints work just for a few files and for the others it says it cannot find the file. 

Do I need to run anything on binary file and give you an output of that command?

**Comment by aarzilli** [comment] 2019-11-22 16:39
You should try connecting with the command line client and setting the breakpoint with that. If it doesn't work use the `sources` command to check which source files exist. I'm guessing it's the usual problem where you are building outside the IDE and the IDE is asking to set a breakpoint on a file that didn't partecipate in the build (because it had a different path).

**Comment by adibrastegarnia** [comment] 2019-11-22 16:43
Thanks. OK. I will try and then let you know.

**Comment by aarzilli** [comment] 2019-12-12 18:37
Closing, no feedback.

**Closed by aarzilli** 2019-12-12 18:37 UTC
Labels: kind/needs more info

**Comment by raphink** [comment] 2021-01-25 16:49
@aarzilli does you comment mean I need to build a certain way?

I built in a local dir with:

```
go build -gcflags "all=-N -l"  -o debug_bin .
```

and then started Delve with:

```
dlv  --headless  --api-version=2 --log --log-output debugger,rpc exec ./debug_bin
```

When attaching to the process using `vim-go` and `:GoDebugAttach`, I get lots of errors similar to the ones described in this issue:

```
ERR: 2021-01-25T17:45:00+01:00 warning layer=debugger reading debug_info: concrete subprogram without address range at 0xf0af                  
ERR: 2021-01-25T17:45:00+01:00 warning layer=debugger reading debug_info: could not find abstract origin (0x102a5) of inlined call at 0x1021a
```

And then if I want to add a breakpoint with `:GoDebugBreakpoint`, it says:

```
vim-go: could not toggle breakpoint: could not find file /home/raphink/src/github.com/camptocamp/containers-course-app/backend/go/main.go                                             
```

From what I understand, Delve is the one complaining about not finding that file?

**Comment by aarzilli** [comment] 2021-01-25 16:59
> Delve is the one complaining about not finding that file?

Yes. The most likely reason for that error is that the binary you built does not contain that file, it could be either because you used a different checkpoint from what you are using in your editor or because of modules, it's unlikely that this is a problem with delve. The warning "reading debug_info" is irrelevant.
