### ISSUE TITLE
How can I set value of a variable

### ISSUE THREAD

**Issue by startdusk** [go-delve/delve#1544] opened 2019-04-28 03:31 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv ### ### ### version`)?
`v1.20`
2. What version of Go are you using? (`go version`)?
`1.12.1`
3. What operating system and processor architecture are you using?
`windows 10 professional`
4. What did you do?
I using dlv debug model
command:
`
set localip "127.0.0.1"
Command failed: 1:9: expected 'EOF', found "127.0.0.1"
`
`
set localip="127.0.0.1"
Command failed: command not available
`
`
p localip
""
`

5. What did you expect to see?
I want to see the localip is changed
6. What did you see instead?

**Comment by aarzilli** [comment] 2019-05-05 06:14
Duplicate of #826

**Closed by aarzilli** 2019-05-05 06:14 UTC
