### ISSUE TITLE
Cannot debug with dlv even when I'm using go 1.16 beta

### ISSUE THREAD

**Issue by captain-corgi** [go-delve/delve#2275] opened 2020-12-19 18:04 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
<pre>
Delve Debugger
Version: 1.5.1
Build: $Id: bca418ea7ae2a4dcda985e623625da727d4525b5 $
</pre>
2. What version of Go are you using? (`go version`)?
<pre>
go version go1.16beta1 darwin/amd64
</pre>
3. What operating system and processor architecture are you using?
<pre>
OS: macOS Big Sur 11.1 (20C69)
Processor Architecture: Apple M1 (arm64)
</pre>
4. What did you do?
<pre>
I just create a simple hello world golang project, and try to debug with Visual Studio Code - Exploration Version: 1.53.0-exploration
I'm able to run project without debugging, and it show that my go program running natively on my Macbook Air M1 (I viewed by Activity Monitor, and Architecture column shown "Apple").
</pre>
5. What did you expect to see?
<pre>
I can debug
</pre>
6. What did you see instead?
<pre>
I cannot debug, console shown this error:
dlv debug main.go
# runtime/cgo
gcc_arm64.S:28:16: error: brackets expression not supported on this target
 stp x29, x30, [sp, #-96]!
               ^
gcc_arm64.S:32:2: error: unknown use of instruction mnemonic without a size suffix
 mov x29, sp
 ^
gcc_arm64.S:34:16: error: brackets expression not supported on this target
 stp x19, x20, [sp, #80]
               ^
gcc_arm64.S:37:16: error: brackets expression not supported on this target
 stp x21, x22, [sp, #64]
               ^
gcc_arm64.S:40:16: error: brackets expression not supported on this target
 stp x23, x24, [sp, #48]
               ^
gcc_arm64.S:43:16: error: brackets expression not supported on this target
 stp x25, x26, [sp, #32]
               ^
gcc_arm64.S:46:16: error: brackets expression not supported on this target
 stp x27, x28, [sp, #16]
               ^
gcc_arm64.S:50:2: error: unknown use of instruction mnemonic without a size suffix
 mov x19, x0
 ^
gcc_arm64.S:51:2: error: unknown use of instruction mnemonic without a size suffix
 mov x20, x1
 ^
gcc_arm64.S:52:2: error: unknown use of instruction mnemonic without a size suffix
 mov x0, x2
 ^
gcc_arm64.S:54:2: error: invalid instruction mnemonic 'blr'
 blr x20
 ^~~
gcc_arm64.S:55:2: error: invalid instruction mnemonic 'blr'
 blr x19
 ^~~
gcc_arm64.S:57:16: error: brackets expression not supported on this target
 ldp x27, x28, [sp, #16]
               ^
gcc_arm64.S:60:16: error: brackets expression not supported on this target
 ldp x25, x26, [sp, #32]
               ^
gcc_arm64.S:63:16: error: brackets expression not supported on this target
 ldp x23, x24, [sp, #48]
               ^
gcc_arm64.S:66:16: error: brackets expression not supported on this target
 ldp x21, x22, [sp, #64]
               ^
gcc_arm64.S:69:16: error: brackets expression not supported on this target
 ldp x19, x20, [sp, #80]
               ^
gcc_arm64.S:72:16: error: brackets expression not supported on this target
 ldp x29, x30, [sp], #96
               ^
exit status 2
make: *** [debug] Error 1
</pre>

**Comment by aarzilli** [comment] 2020-12-19 18:06
Duplicate of #2246

**Closed by aarzilli** 2020-12-19 18:06 UTC
