### ISSUE TITLE
Can't debugging on macOS Sequoia

### ISSUE THREAD

**Issue by ZenkieBear** [go-delve/delve#3812] opened 2024-09-19 03:22 UTC
Please answer the following before submitting your issue:
I updated my macOS to Sequoia yesterday. Now I can't debugging through VSCode or GoLand, and their console all printed `Warning: no debug info found, some functionality will be missing such as stack traces and variable evaluation.`.

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.
<img width="1027" alt="image" src="https://github.com/user-attachments/assets/568d80e7-c201-472b-bf36-8bf0fe1a7f47">

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)? `1.21.2`
3. What version of Go are you using? (`go version`)? `1.21.6`
4. What operating system and processor architecture are you using? `macOS Sequoia`/`Apple Silicon M2`
5. What did you do? Update macOS from Sonoma to Sequoia(15.0)
6. What did you expect to see? The debugging program works right.
7. What did you see instead? When I started debugging my program, the breakpoints began gray circles from red dots.
<img width="170" alt="image" src="https://github.com/user-attachments/assets/54350b07-afd8-407d-b5e2-99635becac65">

**Comment by codeblooded** [comment] 2024-09-19 05:30
This is broken for me also.

**Comment by jay-youngn** [comment] 2024-09-19 07:28
Failed to launch: could not launch process: error reading debug_info: decoding dwarf section info at offset 0x5c2bd9: DW_FORM_strx with no .debug_str_offsets section

**Comment by twz915** [comment] 2024-09-19 07:45
https://github.com/mattn/go-sqlite3/issues/1269#issuecomment-2333030995

**Comment by jay-youngn** [comment] 2024-09-19 07:50
> [mattn/go-sqlite3#1269 (comment)](https://github.com/mattn/go-sqlite3/issues/1269#issuecomment-2333030995)

➜  go install github.com/go-delve/delve/cmd/dlv@master 
go: downloading github.com/go-delve/delve v1.23.1-0.20240918211707-059f149433c1

It works! Thx, old iron

**Comment by aarzilli** [comment] 2024-09-19 10:27
This is a duplicate of #3797 (but I'm going to leave it open for a while so people don't open more duplicates)

**Comment by RogelioLozano** [comment] 2024-09-20 18:30
Hi,

I've already seen #3797 and used the latest master branch to try to make dlv work in my case; nevertheless, I'm still getting the following error when executing

dlv debug .

<img width="1728" alt="Screenshot 2024-09-20 at 12 24 05 p m" src="https://github.com/user-attachments/assets/60f545b0-34de-4c5d-9cd5-b971c1079332">

Obviously same problem show up in vscode.

What version of Delve are you using (dlv version)? 
<img width="825" alt="Screenshot 2024-09-20 at 12 26 34 p m" src="https://github.com/user-attachments/assets/54f56415-93c3-4729-b742-b69bac92f67e">

What version of Go are you using? (go version)? 
<img width="556" alt="Screenshot 2024-09-20 at 12 26 53 p m" src="https://github.com/user-attachments/assets/9ba27a60-cf6f-4952-a668-2d0f36005428">

What operating system and processor architecture are you using? macOS Sonoma 14.7 Apple Silicon M3 Pro

What did you do? Update macOS to latest version allowed 

Previously it was working flawlessly. I use dlv very much, so I'm concerned to make it work again.

**Comment by mfamador** [comment] 2024-09-22 14:47
Hi, running the current master version of `dlv` on a project using go1.23 the fix from #397 seems to work. 
But on another project using go1.22.5 I still get the error:

```
❯ ~/go/bin/dlv debug cmd/watchdog/main.go
Warning: no debug info found, some functionality will be missing such as stack traces and variable evaluation.                           
could not launch process: could not read debug info (decoding dwarf section info at offset 0x0: too short) and could not read go symbol table (could not find rodata struct member)
```

**Comment by ZenkieBear** [comment] 2024-09-23 02:15
> Hi, running the current master version of `dlv` on a project using go1.23 the fix from #397 seems to work. But on another project using go1.22.5 I still get the error:
> 
> ```
> ❯ ~/go/bin/dlv debug cmd/main.go
> Warning: no debug info found, some functionality will be missing such as stack traces and variable evaluation.                           
> could not launch process: could not read debug info (decoding dwarf section info at offset 0x0: too short) and could not read go symbol table (could not find rodata struct member)
> ```

Yes, I did upgrade my golang to `v1.23.0`(from 1.21.0). The problem resolves.

**Comment by ZenkieBear** [comment] 2024-09-23 07:01
After updating go and dlv version, my program crumbs while debugging, and printed "not implemented".

**Closed** 2024-09-24 07:08 UTC

**Comment by ZenkieBear** [comment] 2024-09-24 09:17
> what about older go versions?

The latest go version works well for me.

**Comment by funwithbots** [comment] 2024-11-06 15:15
fwiw, when I updated go to v1.23.2, dlv stayed broken on master which still seems to point to v1.23.0. I had to install delve v1.23.1 using
`go install github.com/go-delve/delve/cmd/@v1.23.1` 
to fix this error

**Comment by then4p** [comment] 2025-01-09 14:37
@funwithbots There was a /dlv missing, for me it was fixed by running
```go install github.com/go-delve/delve/cmd/dlv@v1.23.1```

**Comment by immunochomik** [comment] 2025-02-23 07:53
I found that goland is bringing its own version of dlv, so  I have had to install new dlv and then replace the dlv binary used by goland
