### ISSUE TITLE
disasm.go:12:14: undefined: archInst 

### ISSUE THREAD

**Issue by Rickcau** [go-delve/delve#1486] opened 2019-02-20 16:40 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
2. What version of Go are you using? (`go version`)?
3. What operating system and processor architecture are you using?
4. What did you do?
5. What did you expect to see?
6. What did you see instead?

**Comment by Rickcau** [comment] 2019-02-20 16:46
I am trying to setup debugging for Visual Studio Code and I have set goarch=amd64 and when I run go get -u github.com/go-delve/delve/cmd/dlv I get the following error:  ..\github.com\go-delve\delve\pkg\proc\disasm.go:12:14: undefined: archInst

How can I get this working?

Responses to above 6 questions are:
1. I don't have it installed yet so I cannot run dlv verison
2. go version go 1.11.2 windows/386
3.  Windows 10 64bit
4.  I set the goarc=amd64 and then ran the following command: get -u github.com/go-delve/delve/cmd/dlv
5.  I get the following error message: delve\delve\pkg\proc\disasm.go:12:14: undefined: archInst
6. I expected the install to succeed without error
7. The error message outlined in #5.

**Comment by joegrasse** [comment] 2019-02-20 17:33
I believe the problem is the following.

> 2\. go version go 1.11.2 windows/386

You would need the 64bit version of Go, because 32bit isn't supported.

**Comment by derekparker** [comment] 2019-02-20 18:04
@joegrasse is right for pointing that out. From your description it seems that you're running a 32-bit version of Go on a 64 bit system?

**Comment by aarzilli** [comment] 2019-03-07 17:14
Closing, no feedback.

**Closed by aarzilli** 2019-03-07 17:14 UTC
Labels: kind/needs more info
