### ISSUE TITLE
Cannot debug headless with go 1.15.6, whereas all is working fine with go 1.14.12

### ISSUE THREAD

**Issue by jeremy-dupre** [go-delve/delve#2267] opened 2020-12-14 08:43 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output, stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
1.5.1

2. What version of Go are you using? (`go version`)?
1.15.6 (dlv not working), and 1.14.12 (dlv working)

3. What operating system and processor architecture are you using?
Windows 10
x64

4. What did you do?
Try to debug from vscode or using dlv command line - using the same parameters as with go 1.14.12 (which is working fine)
dlv.exe debug --headless=true --listen=127.0.0.1:23999 --api-version=2 -- -T

5. What did you expect to see?
Effective debugging of my go app to work in go 1.15.6

6. What did you see instead?
__debug_bin gets built, right place right size it seems
debugger tries to launch, freezes? and exits 10s later with code 0
nothing happens (cannot attach for some reason?)
if I switch back to go 1.14.12 and rebuilds, all is working again
if I switch back to go 1.15.6 and rebuilds, same reproducible pattern, does not work

Output log from dlv / vscode in go 1.15.6 :

Verbose logs are written to:
C:\Users\jd\AppData\Local\Temp\vscode-go-debug.txt
InitializeRequest
InitializeResponse
LaunchRequest
Using GOPATH: C:\Users\jd\go
Using GOROOT: C:\Go
Using PATH: undefined
Current working directory: D:\go\src
Running: C:\Users\jd\go\bin\dlv.exe debug --headless=true --listen=127.0.0.1:23999 --api-version=2 -- -T
API server listening at: 127.0.0.1:23999
InitializeEvent
ConfigurationDoneRequest
Changing DebugState from Halted to Running
ConfigurationDoneResponse {"seq":18,"type":"response","request_seq":3,"command":"configurationDone","success":true}
continue state {"Running":false,"Recording":false,"Threads":null,"NextInProgress":false,"exited":true,"exitStatus":3221225477,"When":""}
handleReenterDebug(breakpoint).
TerminatedEvent
DisconnectRequest
Closing Delve.
HaltRequest
HaltResponse
Failed to halt - Process 19880 has exited with status 0
DetachRequest
DisconnectRequest to parent to shut down protocol server.
DisconnectResponse
Process exiting with code: 0
Sending TerminatedEvent as delve is closed

Output log from dlv / vscode in go 1.14.12 :

Verbose logs are written to:
C:\Users\jd\AppData\Local\Temp\vscode-go-debug.txt
InitializeRequest
InitializeResponse
LaunchRequest
Using GOPATH: C:\Users\jd\go
Using GOROOT: C:\Go
Using PATH: undefined
Current working directory: D:\go\src
Running: C:\Users\jd\go\bin\dlv.exe debug --headless=true --listen=127.0.0.1:23999 --api-version=2 -- -T
API server listening at: 127.0.0.1:23999
InitializeEvent
ConfigurationDoneRequest
Changing DebugState from Halted to Running
ConfigurationDoneResponse {"seq":18,"type":"response","request_seq":3,"command":"configurationDone","success":true}
2020-12-14T09:39:41.914+0100	INFO	Main - Process started
...
>> the above line is what I expect to see

Is there anything that changed in go 1.15 that I should be aware of, or that I need to change to make it work, please ?

Thanks much

**Comment by aarzilli** [comment] 2020-12-14 08:51
What's the output with `--log --log-output=rpc2,dap`?

**Comment by jeremy-dupre** [comment] 2020-12-14 09:08
Warning: unknown log output value "rpc2", run 'dlv help log' for usage.
API server listening at: 127.0.0.1:23999 
then it freezes / nothing happens

**Comment by aarzilli** [comment] 2020-12-14 09:09
Sorry, I meant `--log --log-output=dap,rpc`, my bad.

**Comment by jeremy-dupre** [comment] 2020-12-14 09:11
API server listening at: 127.0.0.1:23999
2020-12-14T10:09:00+01:00 debug layer=rpc API server pid = 17296
then it freezes / nothing happens

**Comment by aarzilli** [comment] 2020-12-14 09:14
Did you connect to it with vscode? If you did can you try connecting with the command line `dlv connect...`?

**Comment by jeremy-dupre** [comment] 2020-12-14 09:19
I am running from command line, at my sources root directory:
dlv.exe debug --headless=true --listen=127.0.0.1:23999 --api-version=2 --log --log-output=dap,rpc -- -T

**Comment by aarzilli** [comment] 2020-12-14 09:22
The headless instance isn't going to do anything until a frontend connects to it, did you connect to it after passing `--log --log-output=dap,rpc`? Also, you can connect to a headless instance using the `dlv connect ip:addr` command, can you try that too?

**Comment by jeremy-dupre** [comment] 2020-12-14 09:25
Sorry for that, sure : 

2020-12-14T10:23:07+01:00 debug layer=rpc API server pid = 16200
2020-12-14T10:23:08+01:00 debug layer=rpc <- RPCServer.GetVersion(api.GetVersionIn{})
2020-12-14T10:23:08+01:00 debug layer=rpc -> *api.GetVersionOut{"DelveVersion":"Version: 1.5.1\nBuild: $Id: bca418ea7ae2a4dcda985e623625da727d4525b5 $","APIVersion":2,"Backend":"native","TargetGoVersion":"Go cmd/compile go1.15.6","MinSupportedVersionOfGo":"1.13.0","MaxSupportedVersionOfGo":"1.15.0"} error: ""
2020-12-14T10:23:08+01:00 debug layer=rpc (async 2) <- RPCServer.State(rpc2.StateIn{"NonBlocking":true})
2020-12-14T10:23:08+01:00 debug layer=rpc (async 2) -> rpc2.StateOut{"State":{"Running":false,"Recording":false,"currentThread":{"id":17776,"pc":140723022595505,"file":"","line":0,"goroutineID":0,"ReturnValues":null},"Threads":[{"id":17776,"pc":140723022595505,"file":"","line":0,"goroutineID":0,"ReturnValues":null},{"id":17364,"pc":140723022395380,"file":"","line":0,"goroutineID":0,"ReturnValues":null},{"id":6044,"pc":140723022395380,"file":"","line":0,"goroutineID":0,"ReturnValues":null},{"id":21412,"pc":140723022395380,"file":"","line":0,"goroutineID":0,"ReturnValues":null}],"NextInProgress":false,"exited":false,"exitStatus":0,"When":""}} error: ""
2020-12-14T10:23:08+01:00 debug layer=rpc (async 3) <- RPCServer.Command(api.DebuggerCommand{"name":"continue","ReturnInfoLoadConfig":null})
2020-12-14T10:23:08+01:00 debug layer=rpc (async 4) <- RPCServer.State(rpc2.StateIn{"NonBlocking":true})
2020-12-14T10:23:08+01:00 debug layer=rpc (async 4) -> rpc2.StateOut{"State":{"Running":true,"Recording":false,"Threads":null,"NextInProgress":false,"exited":false,"exitStatus":0,"When":""}} error: ""
2020-12-14T10:23:08+01:00 debug layer=rpc (async 3) -> rpc2.CommandOut{"State":{"Running":false,"Recording":false,"Threads":null,"NextInProgress":false,"exited":true,"exitStatus":3221225477,"When":""}} error: ""
2020-12-14T10:23:08+01:00 debug layer=rpc (async 5) <- RPCServer.Command(api.DebuggerCommand{"name":"halt","ReturnInfoLoadConfig":null})
2020-12-14T10:23:08+01:00 debug layer=rpc (async 5) -> <nil>null error: "Process 23656 has exited with status 0"
2020-12-14T10:23:08+01:00 debug layer=rpc <- RPCServer.Detach(rpc2.DetachIn{"Kill":true})
2020-12-14T10:23:08+01:00 debug layer=rpc -> *rpc2.DetachOut{} error: ""
Process exiting with code: 0

**Comment by aarzilli** [comment] 2020-12-14 09:29
It seems that vscode is automatically sending a continue command to delve. I'm not sure why it's behaving this way.
Cc @polinasok.

**Comment by aarzilli** [comment] 2020-12-14 09:33
Is the problem here that you are not seeing the log line from your program? Because I think it's just not printing it for some unrelated reason. Maybe try setting a breakpoint?

**Comment by jeremy-dupre** [comment] 2020-12-14 09:40
Not hitting the breakpoint if I set one, it is not just the logs unfortunately.

**Comment by aarzilli** [comment] 2020-12-14 09:42
Can I see the output of `--log --log-output=rpc` with setting a breakpoint, for example on the main function? Can you reproduce this with a small program I can test myself?

**Comment by jeremy-dupre** [comment] 2020-12-14 09:43
API server listening at: 127.0.0.1:23999
2020-12-14T10:40:32+01:00 debug layer=rpc API server pid = 5644
2020-12-14T10:40:32+01:00 debug layer=rpc <- RPCServer.GetVersion(api.GetVersionIn{})
2020-12-14T10:40:32+01:00 debug layer=rpc -> *api.GetVersionOut{"DelveVersion":"Version: 1.5.1\nBuild: $Id: bca418ea7ae2a4dcda985e623625da727d4525b5 $","APIVersion":2,"Backend":"native","TargetGoVersion":"Go cmd/compile go1.15.6","MinSupportedVersionOfGo":"1.13.0","MaxSupportedVersionOfGo":"1.15.0"} error: ""
2020-12-14T10:40:32+01:00 debug layer=rpc (async 2) <- RPCServer.State(rpc2.StateIn{"NonBlocking":true})
2020-12-14T10:40:32+01:00 debug layer=rpc (async 2) -> rpc2.StateOut{"State":{"Running":false,"Recording":false,"currentThread":{"id":11944,"pc":140723022595505,"file":"","line":0,"goroutineID":0,"ReturnValues":null},"Threads":[{"id":11944,"pc":140723022595505,"file":"","line":0,"goroutineID":0,"ReturnValues":null},{"id":24860,"pc":140723022395380,"file":"","line":0,"goroutineID":0,"ReturnValues":null},{"id":9464,"pc":140723022395380,"file":"","line":0,"goroutineID":0,"ReturnValues":null},{"id":9648,"pc":140723022395380,"file":"","line":0,"goroutineID":0,"ReturnValues":null}],"NextInProgress":false,"exited":false,"exitStatus":0,"When":""}} error: ""
2020-12-14T10:40:32+01:00 debug layer=rpc <- RPCServer.CreateBreakpoint(rpc2.CreateBreakpointIn{"Breakpoint":{"id":0,"name":"","addr":0,"addrs":null,"file":"D:\\go\\src\\tests.go","line":32,"Cond":"","continue":false,"traceReturn":false,"goroutine":false,"stacktrace":0,"LoadArgs":{"FollowPointers":true,"MaxVariableRecurse":1,"MaxStringLen":500,"MaxArrayValues":200,"MaxStructFields":-1},"LoadLocals":{"FollowPointers":true,"MaxVariableRecurse":1,"MaxStringLen":500,"MaxArrayValues":200,"MaxStructFields":-1},"hitCount":null,"totalHitCount":0}})
2020-12-14T10:40:32+01:00 debug layer=rpc -> *rpc2.CreateBreakpointOut{"Breakpoint":{"id":1,"name":"","addr":25514252,"addrs":[25514252],"file":"D:/go/src/tests.go","line":32,"functionName":"main.runTestTask","Cond":"","continue":false,"traceReturn":false,"goroutine":false,"stacktrace":0,"LoadArgs":{"FollowPointers":true,"MaxVariableRecurse":1,"MaxStringLen":500,"MaxArrayValues":200,"MaxStructFields":-1},"LoadLocals":{"FollowPointers":true,"MaxVariableRecurse":1,"MaxStringLen":500,"MaxArrayValues":200,"MaxStructFields":-1},"hitCount":{},"totalHitCount":0}} error: ""
2020-12-14T10:40:32+01:00 debug layer=rpc (async 4) <- RPCServer.State(rpc2.StateIn{"NonBlocking":true})
2020-12-14T10:40:32+01:00 debug layer=rpc (async 4) -> rpc2.StateOut{"State":{"Running":false,"Recording":false,"currentThread":{"id":11944,"pc":140723022595505,"file":"","line":0,"goroutineID":0,"ReturnValues":null},"Threads":[{"id":11944,"pc":140723022595505,"file":"","line":0,"goroutineID":0,"ReturnValues":null},{"id":24860,"pc":140723022395380,"file":"","line":0,"goroutineID":0,"ReturnValues":null},{"id":9464,"pc":140723022395380,"file":"","line":0,"goroutineID":0,"ReturnValues":null},{"id":9648,"pc":140723022395380,"file":"","line":0,"goroutineID":0,"ReturnValues":null}],"NextInProgress":false,"exited":false,"exitStatus":0,"When":""}} error: ""
2020-12-14T10:40:32+01:00 debug layer=rpc (async 5) <- RPCServer.Command(api.DebuggerCommand{"name":"continue","ReturnInfoLoadConfig":null})
2020-12-14T10:40:32+01:00 debug layer=rpc (async 6) <- RPCServer.State(rpc2.StateIn{"NonBlocking":true})
2020-12-14T10:40:32+01:00 debug layer=rpc (async 6) -> rpc2.StateOut{"State":{"Running":true,"Recording":false,"Threads":null,"NextInProgress":false,"exited":false,"exitStatus":0,"When":""}} error: ""
2020-12-14T10:40:33+01:00 debug layer=rpc (async 5) -> rpc2.CommandOut{"State":{"Running":false,"Recording":false,"Threads":null,"NextInProgress":false,"exited":true,"exitStatus":3221225477,"When":""}} error: ""
2020-12-14T10:40:33+01:00 debug layer=rpc (async 7) <- RPCServer.Command(api.DebuggerCommand{"name":"halt","ReturnInfoLoadConfig":null})
2020-12-14T10:40:33+01:00 debug layer=rpc (async 7) -> <nil>null error: "Process 18880 has exited with status 0"
2020-12-14T10:40:33+01:00 debug layer=rpc <- RPCServer.Detach(rpc2.DetachIn{"Kill":true})
2020-12-14T10:40:33+01:00 debug layer=rpc -> *rpc2.DetachOut{} error: ""
Process exiting with code: 0

**Comment by jeremy-dupre** [comment] 2020-12-14 10:03
for a sample - I am trying to build one but that would be too easy: I am able to debug simple code in 1.15.6  :/

**Comment by aarzilli** [comment] 2020-12-14 10:20
It seems that the program is exiting with error code 0xC0000005, could be an antivirus problem.

**Comment by jeremy-dupre** [comment] 2020-12-14 10:27
I disabled antivirus on those directories though, and I am puzzled why it works on go 1.14.12 with the exact same setup / locations. I'll double check, thx.

I managed to pinpoint some pattern: I re-added internal and external lib deps one by one, and noticed the debugger started to fail when some native code (cgo) was included. Could that make sense ?

**Comment by jeremy-dupre** [comment] 2020-12-14 10:43
hmmm
Seems like there is some asyncpreemptoff default setup that has changed from 1.14 to 1.15

**Comment by aarzilli** [comment] 2020-12-14 11:02
I doubt the asyncpreempt stuff is causing the problem because delve disables it on windows (it can not work with it). A likelier possibility is that the default buildmode switched to PIE in 1.15 on windows. You could try adding `--build-flags='-buildmode=exe'` to the command to disable it. There's also an issue with using [PIE incompatible C libraries in 1.15](https://github.com/golang/go/issues/42233)

**Comment by jeremy-dupre** [comment] 2020-12-14 11:10
You're a star, --build-flags='-buildmode=exe' did solve it. Thanks !

**Comment by aarzilli** [comment] 2020-12-14 11:12
Closing this as duplicate of https://github.com/golang/go/issues/42233 then.

**Closed by aarzilli** 2020-12-14 11:12 UTC
Labels: kind/needs more info, os/windows

**Comment by polinasok** [comment] 2020-12-14 11:29
> It seems that vscode is automatically sending a continue command to delve. I'm not sure why it's behaving this way.
> Cc @polinasok.

vscode-go has a `launch.json` setting `stopOneEntry` that is false by default. If false, an automatic continue is issued on entry.

I am glad you were able to resolve this issue and it is not related to vscode.
