### ISSUE TITLE
Breakpoints not working on Windows with Zig as the C compiler

### ISSUE THREAD

**Issue by AntonC9018** [go-delve/delve#3521] opened 2023-10-05 15:48 UTC
Some context: I'm using VS Code, not running the debugger directly in the console. My [config goes like this](https://github.com/AntonC9018/uni_distributedDatabases/blob/11d0320f73c605f7b96ad0f408827a8dfef9b88f/.vscode/launch.json). 

I was looking at GORM, which seems to require CGO and a C compiler to be installed.
I'm using Zig, because it just works for everything without hassle in my experience. I'm trying to run the debugger on the [following code](https://github.com/AntonC9018/uni_distributedDatabases/blob/11d0320f73c605f7b96ad0f408827a8dfef9b88f/source/webapp/hello.go).
Note that I'm able to compile and run it without a debugger separately without any issue by doing:
```
set CGO_ENABLED=1
set CXX=zig c++
set CC=zig cc
go run .
```

1. What version of Delve are you using (`dlv version`)? 
```
Delve Debugger
Version: 1.21.1
Build: $Id: a358c02f24aa7047ecc562b0587dc2d08330b2cf $
```

2. What version of Go are you using? (`go version`)?
```
go version go1.21.1 windows/amd64
```

3. What operating system and processor architecture are you using? -- Windows 10 64 bit Intel

4. Zig version: `0.11.0`

**Comment by aarzilli** [comment] 2023-10-05 16:28
Try debugging from the command line and post a transcript.

**Comment by AntonC9018** [comment] 2023-10-05 16:54
I think there are no debug symbols loaded whatsoever. I'm trying to execute `next` on the command line with the debugger, it just says:
```
Stopped at: 0x7ffb2d2a0911
=>   1:	no source available
```
`continue` just lets the program run to completion.

Which folder is it supposed to generate the debug info into? Do I maybe need some flag for the Go compiler to make it output these when using CGO? I know for a fact zig does generate debug info by default, which is a pdb by running it by default on Windows. My guess is that the debugger expects a different format maybe? Though I expect the format to have been handled by the relevant flags passed by the Go compiler to the C compiler.

I might be wrong about everything here, though. I don't know how the debugger works or how it calls the Go compiler, or how the Go compiler uses the C compiler.

**Comment by aarzilli** [comment] 2023-10-05 19:49
Go (and delve) simply use DWARF embedded into the executable. But what you are seeing doesn't mean that there aren't debug symbols, just that there aren't for the entry point, which is fine. What zig produces should be irrelevant.

**Comment by AntonC9018** [comment] 2023-10-06 06:49
Ok just figured out how to use it from the command line:
```
(dlv) break D:\coding\uni_distributedDatabases\source\webapp\hello.go:15
Breakpoint 1 set at 0x7ff61ce7bdbd for main.main() D:/coding/uni_distributedDatabases/source/webapp/hello.go:15
(dlv) continue
> main.main() D:/coding/uni_distributedDatabases/source/webapp/hello.go:15 (hits total:1) (PC: 0x7ff61ce7bdbd)
    10:         Code  string
    11:         Price uint
    12: }
    13:
    14: func main() {
=>  15:         db, err := gorm.Open(sqlite.Open("test.db"), &gorm.Config{})
    16:         if err != nil {
    17:                 panic("failed to connect database")
    18:         }
    19:
    20:         // Migrate the schema
(dlv) next
Process 7436 has exited with status 3221225477
```

It works when I just do `go run .` (I have verified that by putting a `Println` at the end which does get hit)

**Comment by AntonC9018** [comment] 2023-10-06 06:52
A correction to [the earlier message](https://github.com/go-delve/delve/issues/3521#issuecomment-1749308069): it exists with the same code 3221225477. It seems to be an access violation which only manifests when running with the debugger.

**Comment by aarzilli** [comment] 2023-10-06 08:23
But if you don't set a breakpoint, if you just type `continue` as the first command, it doesn't happen?

**Comment by AntonC9018** [comment] 2023-10-06 08:25
> But if you don't set a breakpoint, if you just type `continue` as the first command, it doesn't happen?

It does, that's what I tried to clarify with the earlier message. It works correctly (the process runs to completion with zero error code) only when running it without the debugger.

**Comment by aarzilli** [comment] 2023-10-06 08:34
Ok, that makes sense. You don't know about this but some Windows syscalls behave differently when there's a debugger attached: some things that are wrong will still succeed when no debugger is attached but if there's a debugger it becomes an error.
It's likely that this is what's happening here.
You could try doing `break os.Exit` and see if that's what's making the program quit. Otherwise it's probably coming from the C code, that's a problem because with zig you won't have symbols.

**Comment by AntonC9018** [comment] 2023-10-06 08:41
> Otherwise it's probably coming from the C code, that's a problem because with zig you won't have symbols.

I imagine Zig does support the DWARF format, it's just not the default. Like I mentioned, I assumed CGo would enable that with a flag, but I might need to do that manually after all. Currently, there are no C symbols in my program, right?

I'm assuming CGo is needed to link to some C code used by the module I'm trying, and the code it compiles should be in the module files. Is my assumption correct?

**Comment by AntonC9018** [comment] 2023-10-06 08:42
> You could try doing break `os.Exit` and see if that's what's making the program quit

```
(dlv) break os.Exit
Breakpoint 1 set at 0x7ff6f1a1228a for os.Exit() C:/Program Files/Go/src/os/proc.go:62
(dlv) continue
Process 3736 has exited with status 3221225477
```

**Comment by aarzilli** [comment] 2023-10-06 08:55
> I imagine Zig does support the DWARF format, it's just not the default. Like I mentioned, I assumed CGo would enable that with a flag, but I might need to do that manually after all. Currently, there are no C symbols in my program, right?

I don't have any experience with zig and I don't know how well cgo supports zig. I don't know if there are C symbols in the program or not, you could try the `funcs` command and see what's there. My guess at this point is that some of the C code is calling exit() with the error return value of a system call.

**Comment by AntonC9018** [comment] 2023-10-06 09:02
Yeah doesn't seem like it has any [funcs.txt](https://github.com/go-delve/delve/files/12829048/funcs.txt).
As far as I understand, Zig just bundles Clang while supporting the flags of both Clang and GCC. So if CGo works with Clang, it should it theory work with Zig as well.

**Comment by AntonC9018** [comment] 2023-10-06 16:10
So I've tried debugging this with GCC, and it works. As I had just found out, GCC is the only officially supported toolchain by CGo. Not even Clang. So that code probably won't work with Clang either, would be my guess. The C code they include must be assuming it's working with GCC.

**Comment by aarzilli** [comment] 2023-10-08 05:33
I'm closing this because I don't think there's anything to do for us here. The difference in behaviour between debugger and no debugger is either caused by the '-N -l' we pass or by some of the increasingly strict checks that windows applies to debugged programs.

**Closed by aarzilli** 2023-10-08 05:33 UTC
Labels: kind/bug, os/windows, kind/needs more info
