### ISSUE TITLE
Command failed: protocol error E09 during set breakpoint for packet (M1 Mac)

### ISSUE THREAD

**Issue by Diastro** [go-delve/delve#2967] opened 2022-04-10 21:06 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.8.2
Build: $Id: dbb493ec14d1e7753504d016b1e1ef1665b75b16
```
3. What version of Go are you using? (`go version`)?
```
go version go1.18 darwin/arm64
```
5. What operating system and processor architecture are you using?
```
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
```
7. What did you do?
Trying to add a breakpoint to dlv (dlv connect, break <source>)
9. What did you expect to see?
Breakpoint to be set.
10. What did you see instead?
```
(dlv) 
Command failed: protocol error E09 during set breakpoint for packet $Z0,7ff70162a2bb,4
```

FWIW, bebug in goland works but breakpoint are not being hit either.
Goland info : 
```
Version: 2021.3.4 ([Release notes](https://youtrack.jetbrains.com/articles/GO-A-35))

Build: 213.7172.22

Released: 15 March 2022
```

**Comment by aarzilli** [comment] 2022-04-11 07:13
Closing, duplicate of #2936, #1116

**Closed by aarzilli** 2022-04-11 07:13 UTC
