### ISSUE TITLE
Unexplained slowness stepping over cgo call on Windows

### ISSUE THREAD

**Issue by pds2208** [go-delve/delve#1761] opened 2019-11-18 08:18 UTC
There is something odd going on when debugging an application when that application calls a CGO routine. Under Windows it takes minutes to step over the call while on macos or linux just a few seconds.

Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

1.3.2

2. What version of Go are you using? (`go version`)?

1.13.4

3. What operating system and processor architecture are you using?

Windows 10. Version 1909

4. What did you do?

Debug an application that calls CGO to call into a C library

5. What did you expect to see?

 Equivalent, or at least similar  performance, to the same debug session running on Mac and linux.

6. What did you see instead?

The debugger takes a considerable amount of time to step over a CGO call. At least 3 or 4 minutes. The exact same debug session on MacOS or even linux running in docker takes at most a few seconds.

**Comment by aarzilli** [comment] 2019-11-20 12:14
Is this a statically or dynamically linked C library? Does it happen with any call to any C library or is there something in particular about this C call?

**Comment by pds2208** [comment] 2019-11-20 17:13
This is a dynamically linked library. The library is called readstat and can be found here: https://github.com/WizardMac/ReadStat

The source for the CGO application can be found here: https://github.com/ONSdigital/lfs-imports and the actual bit of CGO is in here: https://github.com/ONSdigital/lfs-imports/tree/develop/importdata/sav.  The CGO call is in the file import_sav.go and is: 

var res = C.parse_sav(name) <-- takes forever but only on windows

**Comment by aarzilli** [comment] 2019-11-27 11:01
I put together an attempt at [minimal reproduction](https://github.com/aarzilli/delve-savfile-cgo-windows-repro). It failed, stepping over that line doesn't take any more time. You should try this, and see if it still does it or if it's something else in your program that causes it. If you have antivirus running I'd check that too, a lot of malware uses the same API as debuggers and we could be triggering it.

**Comment by pds2208** [comment] 2019-11-28 13:57
Hi,

Thanks for looking at this. I've tried your version and it works with your sav file. However, if I replace your file with the LFSwk18PERS_non_confidential.sav file in the project above then the problem occurs.

As I said this is only on windows so something must be going on with delve under windows with CGO...?

**Comment by aarzilli** [comment] 2019-11-28 14:36
Can I have LFSwk18PERS_non_confidential.sav? Is it a lot bigger?

> As I said this is only on windows so something must be going on with delve under windows with CGO...?

No clue at the moment, seems strange that it would only happen when certain files are being read by the program.

**Comment by pds2208** [comment] 2019-11-28 14:39
Yeah, strange. The file is here:

https://github.com/ONSdigital/lfs-imports/blob/develop/testdata/LFSwk18PERS_non_confidential.sav


________________________________

**Comment by aarzilli** [comment] 2019-11-29 08:52
Alright, this is weird, but believe it or not, this is actually how Windows works. The memory allocator in the standard C library will detect if a debugger is attached to the process and, if it is, use a different, much slower, heap. That's the cause of your slowdown (it's only visible with the bigger file because it does many more allocations). To disable this behavior you have to set the _NO_DEBUG_HEAP variable to 1. You have to do this *when you run the program*, not at compile time.

Reference: https://devblogs.microsoft.com/oldnewthing/20130103-00/?p=5653

Closing, *intended behavior* apparently.

**Closed by aarzilli** 2019-11-29 08:52 UTC
Labels: kind/needs more info, os/windows

**Comment by pds2208** [comment] 2019-11-29 10:30
Can't say I'm surprised. Would it be possible to add this to the documentation?

**Comment by aarzilli** [comment] 2019-11-29 11:02
I'm not sure where I'd add it that people would read it. I'm hoping google will index and show this, at the moment.
