### ISSUE TITLE
Macos could not launch process: stub exited while waiting for connection: exit status 0

### ISSUE THREAD

**Issue by bzeron** [go-delve/delve#3102] opened 2022-08-12 05:48 UTC
1. What version of Delve are you using (`dlv version`)?

 ```
Delve Debugger
Version: 1.9.0
Build: $Id: 69310c2f438e492f892d6af22e8e62c8ea1e9d8d $
```

2. What version of Go are you using? (`go version`)?

```
go version go1.19 darwin/amd64
```

3. What operating system and processor architecture are you using?

```
Arch: amd64
GOOS: darwin
ProductName:	macOS
ProductVersion:	12.5
BuildVersion:	21G72
```

4. What did you do?

###### main.go

```go
package main

import "fmt"

func main() {
	fmt.Println("hello world")
}
```

###### build app

```
go build -o app -gcflags 'all=-N -l' main.go
```

###### debug app

```
dlv --log --listen=127.0.0.1:9999 --headless=true --api-version=2 --check-go-version=false --only-same-user=false exec app
```

5. What did you expect to see?

```
debug successs
```

6. What did you see instead?

```
API server listening at: 127.0.0.1:9999
2022-08-12T13:46:54+08:00 info layer=debugger launching process with args: [app]
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1316.0.9.46
 for x86_64.
error: failed to launch process /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver: failed to get the task for process 15543
Exiting.
could not launch process: stub exited while waiting for connection: exit status 0
```

**Comment by aarzilli** [comment] 2022-08-12 06:01
Duplicate of #3056. Either you didn't follow the installation instructions, you are trying to debug through ssh (which apple does not allow) or your install of xcode is broken and you should talk to apple.

**Closed by aarzilli** 2022-08-12 06:01 UTC
