### ISSUE TITLE
No support exit dlv

### ISSUE THREAD

**Issue by liangjingkanji** [go-delve/delve#1989] opened 2020-04-05 13:29 UTC
I using remote debug  at `Go Remote` of GoLand 

![image](https://user-images.githubusercontent.com/21078112/78499632-63aea600-7784-11ea-93c5-d13f5181af1f.png)

![image](https://user-images.githubusercontent.com/21078112/78499587-1b8f8380-7784-11ea-8a3b-eb62db72e037.png)

1. dlv version  1.4.0
2. go version  1.13.4
3. Mac x64
4. expect exit delve

**Comment by chainhelen** [comment] 2020-04-06 08:52
You should `dlv connect 192.168.8.134:2345` and type `quit` for exit When `--headless`.  ( `kill` is also ok)

I have try the Latest GoLand, it seems that GoLand's support for `Go Remote`is not friendly enough. 
Any idea? @dlsniper

**Comment by aarzilli** [comment] 2020-04-06 13:06
Delve instances started with `--accept-multiclient` do not exit when the last client disconnects, because of competing feature requests. This is not a bug.

**Comment by liangjingkanji** [comment] 2020-04-06 14:19
> Delve instances started with `--accept-multiclient` do not exit when the last client disconnects, because of competing feature requests. This is not a bug.

Can't I log out manually?

**Comment by aarzilli** [comment] 2020-04-06 14:53
Yes, if you connect with the command line client you will be asked what to do before quitting.

**Comment by liangjingkanji** [comment] 2020-04-06 15:22
> Yes, if you connect with the command line client you will be asked what to do before quitting.

But, I using GoLand, I don't know quit;

**Comment by dlsniper** [comment] 2020-04-06 15:26
Thanks for the ping @chainhelen.

If you launch the process without `--accept-multiclient` flag, then when you'll disconnect GoLand, the process will also stop. To disconnect the IDE, click on the [red square](https://www.jetbrains.com/help/go/debug-tool-window.html#debugtoolbar) in the Debug tool window. 

I'll raise an issue on our tracker to either document this somewhere or make clear in the Run Configuration window.

**Comment by liangjingkanji** [comment] 2020-04-06 19:49
> Thanks for the ping @chainhelen.
> 
> If you launch the process without `--accept-multiclient` flag, then when you'll disconnect GoLand, the process will also stop. To disconnect the IDE, click on the [red square](https://www.jetbrains.com/help/go/debug-tool-window.html#debugtoolbar) in the Debug tool window.
> 
> I'll raise an issue on our tracker to either document this somewhere or make clear in the Run Configuration window.

1.  dlv debug
![image](https://user-images.githubusercontent.com/21078112/78598800-89ba7000-7882-11ea-918b-bf4f1e8914a8.png)

2. listener
![image](https://user-images.githubusercontent.com/21078112/78598829-98a12280-7882-11ea-86c0-b93696d52891.png)

3. close debug mode
![image](https://user-images.githubusercontent.com/21078112/78598854-a5be1180-7882-11ea-91ef-7cc88f58d443.png)

4. but not exit
![image](https://user-images.githubusercontent.com/21078112/78598898-b79fb480-7882-11ea-9d3c-981f2d6a6198.png)

**Comment by nd** [comment] 2020-04-07 16:02
@liangjingkanji stopping delve on remote machine is not implemented at the moment. Please watch/vote for https://github.com/go-delve/delve/issues/1989.

The only workaround at the moment is to kill it manually, e.g. by running `killall dlv`.

**Comment by liangjingkanji** [comment] 2020-04-08 12:56
How do i attach to a running process

**Comment by dlsniper** [comment] 2020-04-08 13:21
@liangjingkanji please provide steps to reproduce the issue. Also, the question is not related to the current one, please open a new one. If you want to chat, there's a #goland channel on Gophers Slack https://invite.slack.golangbridge.org/. And if it's a question for GoLand, please use our tracker first, https://youtrack.jetbrains.com/issues/Go. We'll forward anything we need to this tracker.

**Comment by oxycoder** [comment] 2020-04-11 02:12
@liangjingkanji  Find your process pid first
```
bash-5.0# pidof gorl

1942

bash-5.0# dlv attach 1942
```

**Comment by liangjingkanji** [comment] 2020-04-11 09:12
> @liangjingkanji Find your process pid first
> 
> ```
> bash-5.0# pidof gorl
> 
> 1942
> 
> bash-5.0# dlv attach 1942
> ```

But i using delve of GoLand, its invalid

**Comment by chainhelen** [comment] 2020-04-20 07:04
>dlsniper:  @liangjingkanji please provide steps to reproduce the issue. Also, the question is not related to the current one, please open a new one. If you want to chat, there's a #goland channel on Gophers Slack https://invite.slack.golangbridge.org/. And if it's a question for GoLand, please use our tracker first, https://youtrack.jetbrains.com/issues/Go. We'll forward anything we need to this tracker.

@liangjingkanji I think you can follow those steps and this issue can be closed.

**Comment by aarzilli** [comment] 2020-09-08 11:43
Closing, goland feature request.

**Closed by aarzilli** 2020-09-08 11:43 UTC
