### ISSUE TITLE
panic on printing nil

### ISSUE THREAD

**Issue by bobcob7** [go-delve/delve#2753] opened 2021-10-20 02:04 UTC
1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.7.2
Build: $Id: 5b6f24e7fbcad3fe3bc574d3763b2f20afa1d6a1 $
```
2. What version of Go are you using? (`go version`)?
```
go version go1.17.2 darwin/amd64
```
3. What operating system and processor architecture are you using?
```
darwin/amd64
```
4. What did you do?
Ran `dlv debug main.go` then continue.
This is my `main.go` file.
```
package main

import (
        "fmt"
        "time"
)

type Time struct {
        time.Time
}

func main() {
        fmt.Println("Before")
        var nilTime *Time
        fmt.Println(nilTime)
        fmt.Println("After")
}
```
5. What did you expect to see?
I would expect to see similar to the output of `go run main.go`.
```
Before
<nil>
After
```
6. What did you see instead?
The program never completes and seems to abort while printing the nil.
```
# dlv debug main.go
Type 'help' for list of commands.
(dlv) c
Before
> main.(*Time).String() <autogenerated>:1 (PC: 0x10abe2d)
Command failed: bad access
```

**Comment by aarzilli** [comment] 2021-10-20 05:07
Do
```
$ cd $(xcode-select --print-path)
$ ../SharedFrameworks/LLDB.framework/Versions/A/Resources/debugserver --unmask-signals
$ ../SharedFrameworks/LLDB.framework/Versions/A/Resources/debugserver --version
```
and post the output. This is likely a duplicate of #852 which is only fixed if you have a recent verison of macos and of macos command line tools.

**Closed as completed** 2021-10-23 09:43 UTC
