### ISSUE TITLE
could not launch process: decoding dwarf section info at offset 0x0: too short

### ISSUE THREAD

**Issue by official-minister** [go-delve/delve#2019] opened 2020-04-21 06:06 UTC
Hello, I get a error when I use delve.
system: windows 10 64-bit
goversion: go1.14.2 windows/amd64
delveversion: 1.4.0

1. I build a bazel project follow by google project named "gapid". Link: https://github.com/google/gapid;
    I use "bazel buid pkg" to build my project, and it's ok.

2. I want to debug process and test my project. Then I fellow the instruction:
https://github.com/google/gapid/blob/master/DEVDOC.md

3. When I use "dlv exec ./bazel-bin/pkg/gapis -- -enable-local-files -persist -rpc localhost:8888" in cmd, I get a error: could not launch process: decoding dwarf section info at offset 0x0: too short.

4. I search some solutions and someone said I should update delve. So I use "go get -u -v  github.com/go-delve/delve/cmd/dlv". but still has error.

   I has setted GOPATH and GOROOT. I run a simple debug process for helloword and it run well.

  So it's my project builds error, or the delve has problem?

**Comment by jhftss** [comment] 2020-04-21 06:27
I have the same issue with you

**Comment by official-minister** [comment] 2020-04-21 07:58
> I have the same issue with you

How do you solve it ? I update delve bu no use

**Comment by aarzilli** [comment] 2020-04-21 08:58
The error message means that the executable doesn't have debug symbols. Something in the build system is disabling it. This doesn't look like a bug in delve.

**Comment by official-minister** [comment] 2020-04-21 09:58
> The error message means that the executable doesn't have debug symbols. Something in the build system is disabling it. This doesn't look like a bug in delve.

Thanks, I will check the debug symbols and qurry gapids manager.

**Comment by aarzilli** [comment] 2020-09-08 11:42
Closing, not a bug.

**Closed by aarzilli** 2020-09-08 11:42 UTC
