### ISSUE TITLE
Error "bad access" formatting struct pointer struct time.Time

### ISSUE THREAD

**Issue by MikeSpreitzer** [go-delve/delve#3316] opened 2023-03-28 14:55 UTC
```console
(base) mspreitz@mjs12 notime % dlv version
Delve Debugger
Version: 1.20.1
Build: $Id: 96e65b6c615845d42e0e31d903f6475b0e4ece6e $

(base) mspreitz@mjs12 notime % go version
go version go1.20.2 darwin/amd64

(base) mspreitz@mjs12 notime % uname -a
Darwin mjs12 21.6.0 Darwin Kernel Version 21.6.0: Thu Mar  9 20:08:59 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_X86_64 x86_64
```

I am using https://github.com/MikeSpreitzer/dlv_issues/tree/5444aa77590a9eb9d40425f9fd6cce1a85e34554.  The following is done in the `notime` directory of that commit of my local clone of that repo.  I expected running the unit tests under `dlv` would produce the same logging as running them normally, but instead I found that `dlv test` crashes on one, but not the other, of the unit tests.

```console
(base) mspreitz@mjs12 notime % go test -v
=== RUN   TestGood
    time_test.go:18: mg={TheTime:<nil>}
--- PASS: TestGood (0.00s)
=== RUN   TestBad
    time_test.go:23: wpw={Point:<nil>}
--- PASS: TestBad (0.00s)
PASS
ok  	github.com/MikeSpreitzer/dlv_issues/notime	0.121s

(base) mspreitz@mjs12 notime % dlv test
Type 'help' for list of commands.

(dlv) c
> github.com/MikeSpreitzer/dlv_issues/notime.(*Time).String() <autogenerated>:1 (PC: 0x115782d)
Command failed: bad access

(dlv) stack
 0  0x000000000115782d in github.com/MikeSpreitzer/dlv_issues/notime.(*Time).String
    at <autogenerated>:1
 1  0x00000000010d3b43 in fmt.(*pp).handleMethods
    at /usr/local/Cellar/go/1.20.2/libexec/src/fmt/print.go:673
 2  0x00000000010d4d46 in fmt.(*pp).printValue
    at /usr/local/Cellar/go/1.20.2/libexec/src/fmt/print.go:770
 3  0x00000000010d5e1a in fmt.(*pp).printValue
    at /usr/local/Cellar/go/1.20.2/libexec/src/fmt/print.go:853
 4  0x00000000010d4b38 in fmt.(*pp).printArg
    at /usr/local/Cellar/go/1.20.2/libexec/src/fmt/print.go:759
 5  0x00000000010d7485 in fmt.(*pp).doPrintf
    at /usr/local/Cellar/go/1.20.2/libexec/src/fmt/print.go:1077
 6  0x00000000010d0c9d in fmt.Sprintf
    at /usr/local/Cellar/go/1.20.2/libexec/src/fmt/print.go:239
 7  0x00000000010f952a in testing.(*common).Logf
    at /usr/local/Cellar/go/1.20.2/libexec/src/testing/testing.go:1036
 8  0x00000000011575fb in github.com/MikeSpreitzer/dlv_issues/notime.TestBad
    at ./time_test.go:23
 9  0x00000000010fa48a in testing.tRunner
    at /usr/local/Cellar/go/1.20.2/libexec/src/testing/testing.go:1576
10  0x00000000010fc019 in testing.(*T).Run.func1
    at /usr/local/Cellar/go/1.20.2/libexec/src/testing/testing.go:1629
11  0x0000000001070121 in runtime.goexit
    at /usr/local/Cellar/go/1.20.2/libexec/src/runtime/asm_amd64.s:1598
```

**Comment by aarzilli** [comment] 2023-03-28 16:00
What do you see if you pass `--log --log-output=gdbwire`?

**Comment by aarzilli** [comment] 2023-03-28 17:24
What happens if you run `/Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver --unmask-signals`?

**Comment by MikeSpreitzer** [comment] 2023-03-28 17:31
```console
(base) mspreitz@mjs12 notime % /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver --unmask-signals
debugserver: unrecognized option `--unmask-signals'
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1200.0.44
 for x86_64.
Usage:
  debugserver host:port [program-name program-arg1 program-arg2 ...]
  debugserver /path/file [program-name program-arg1 program-arg2 ...]
  debugserver host:port --attach=<pid>
  debugserver /path/file --attach=<pid>
  debugserver host:port --attach=<process_name>
  debugserver /path/file --attach=<process_name>
```

**Comment by aarzilli** [comment] 2023-03-28 17:55
The version of xcode command line tools that you are using is old, with that version of debugserver this is the expected behavior.
Duplicate of #2753 and #852.

**Closed by aarzilli** 2023-03-28 17:55 UTC
Labels: os/macOS, kind/needs more info, area/proc/gdbserial, arch/amd64
