### ISSUE TITLE
Fail  debug wire DI dependency injection.

### ISSUE THREAD

**Issue by chenyangguang** [go-delve/delve#2626] opened 2021-07-28 14:43 UTC
Fail to Debug wire DI . 
Since I begin break endpoint on main function with 

```
b main.main 
```
command , after init my config file,  continue with 

```
n  
```
and  next step by 
```
n  
```
command  , it go to the go exit directly

**Comment by aarzilli** [comment] 2021-07-28 14:44
Please fill the issue form.

**Comment by aarzilli** [comment] 2021-08-04 08:06
Closing, no user feedback. Likely cause: the 'next' command used to not stop at breakpoints, which was by design.

**Closed by aarzilli** 2021-08-04 08:06 UTC
Labels: kind/needs more info
