### ISSUE TITLE
Install failed "invalid type assertion: s.conn.(net.Conn) (non-interface type *connection on left)"

### ISSUE THREAD

**Issue by philjones88** [go-delve/delve#2819] opened 2021-12-08 11:06 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

VS Code

2. What version of Go are you using? (`go version`)?

go version go1.17.3 darwin/amd64

3. What operating system and processor architecture are you using?

MacOS MBP BigSur 11.6.1

4. What did you do?

Followed getting started here: https://github.com/golang/vscode-go/blob/master/docs/debugging.md#getting-started

5. What did you expect to see?

It work

6. What did you see instead?

```
Tools environment: GOPATH=/Users/philjones/go
Installing 2 tools at /Users/philjones/go/bin in module mode.
  dlv
  dlv-dap

Installing github.com/go-delve/delve/cmd/dlv@latest (/Users/philjones/go/bin/dlv) SUCCEEDED
Installing github.com/go-delve/delve/cmd/dlv@master FAILED
{
 "killed": false,
 "code": 2,
 "signal": null,
 "cmd": "/usr/local/Cellar/go/1.17.3/libexec/bin/go build -o /Users/philjones/go/bin/dlv-dap github.com/go-delve/delve/cmd/dlv",
 "stdout": "",
 "stderr": "# github.com/go-delve/delve/service/dap\n/Users/philjones/go/pkg/mod/github.com/go-delve/delve@v1.7.4-0.20211207172355-a4ac69e87df3/service/dap/server.go:502:26: invalid type assertion: s.conn.(net.Conn) (non-interface type *connection on left)\n"
}

1 tools failed to install.

dlv-dap: failed to install dlv-dap(github.com/go-delve/delve/cmd/dlv@master): Error: Command failed: /usr/local/Cellar/go/1.17.3/libexec/bin/go build -o /Users/philjones/go/bin/dlv-dap github.com/go-delve/delve/cmd/dlv
# github.com/go-delve/delve/service/dap
/Users/philjones/go/pkg/mod/github.com/go-delve/delve@v1.7.4-0.20211207172355-a4ac69e87df3/service/dap/server.go:502:26: invalid type assertion: s.conn.(net.Conn) (non-interface type *connection on left)
```

**Comment by aarzilli** [comment] 2021-12-08 11:26
Duplicate of #2817

**Closed by aarzilli** 2021-12-08 11:26 UTC
