### ISSUE TITLE
我安装不了dlv

### ISSUE THREAD

**Issue by Alexliwenhao** [go-delve/delve#3889] opened 2024-12-25 14:22 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)?
我安装不了dlv
3. What version of Go are you using? (`go version`)?
go version go1.22.6 

4. What operating system and processor architecture are you using?
windows/386
5. What did you do?
安装delve 一直失败
6. What did you expect to see?
知道那个版本适配，windows/386
7. What did you see instead?
D:\Go\gopath\pkg\mod\github.com\go-delve\delve@v1.20.2\service\debugger\debugger.go:32:2: found packages native (followexec_other.go) and your_windows_architecture_is_not_supported_by_delve (support_sentinel_windows.go) in D:\Go\gopath\pkg\mod\github.com\go-delve\delve@v1.20.2\pkg\proc\native

**Comment by aarzilli** [comment] 2024-12-26 07:29
Closing, duplicate of #2401.

**Closed by aarzilli** 2024-12-26 07:29 UTC
