### ISSUE TITLE
'Access is denied' error on continue command (windows

### ISSUE THREAD

**Issue by nd** [go-delve/delve#2244] opened 2020-12-01 16:14 UTC
1. What version of Delve are you using (`dlv version`)?
```
Version: 1.5.0
Build: 775c923ec41e92db72122482d69343ef712546c7
```
2. What version of Go are you using? (`go version`)?
```
go 1.15 windows/amd64
```

3. What operating system and processor architecture are you using?

Windows 10

4. What did you do?

Tried to debug the program:

```
package main

import (
	"fmt"
	"time"
)

//func main2() {
//	flag := make(chan bool, 1024)
//	flag2 := make(chan bool, 1)
//
//	go func() {
//		for {
//			flag <- true
//			time.Sleep(time.Millisecond)
//		}
//	}()
//
//	for {
//		select {
//		case <- flag2:
//			break
//
//		case <- flag:
//			fmt.Println(1)
//			time.Sleep(time.Millisecond)
//		}
//	}
//}

func main() {

	i := 0
	for {
		i++
		fmt.Println(i)
		time.Sleep(time.Millisecond)
		fmt.Println(i)
	}
}

//var arrInt []int
//func main() {
//
//	arrInt = make([]int, 102400)
//
//	go func() {
//		for {
//			for _, v := range arrInt {
//				v++
//
//				time.Sleep(time.Millisecond)
//			}
//
//
//		}
//	}()
//
//	go func() {
//		for {
//			arrInt = append(arrInt, 1)
//			time.Sleep(time.Millisecond)
//
//			fmt.Println(len(arrInt))
//		}
//	}()
//
//	go func() {
//		for {
//			if len(arrInt) > 0 {
//				arrInt = arrInt[2:]
//			}
//
//			time.Sleep(time.Millisecond)
//		}
//	}()
//
//	time.Sleep(time.Hour)
//}
```

Got an 'Access denied' error after creating a breakpoint (https://gist.github.com/nd/ce53f5972a6ee847992bfe6429a50f46). 
Sorry for lots of commented code: I cannot reproduce it myself, it was reported by GoLand user. I didn't cleanup the program to keep breakpoint lines correct in the log.

5. What did you expect to see?

Breakpoint is created, program continues execution and stops when breakpoint is reached.

6. What did you see instead?

It looks like program doesn't stop at the breakpoint.

I wonder what can cause 'Access denied' errors? Reportedly there is no antivirus on the machine.

**Comment by aarzilli** [comment] 2020-12-03 09:26
A lot of things can cause 'Access denied' errors, it's a fairly generic thing on windows. Since we can't reproduce the problem the user has to, if willing. Judging from the log:

1. the problem is with the Continue method in target_exec.go, not with CreateBreakpoint
2. since there is a thread with the new breakpoint set it looks like delve made it all the way throught to the call to SetCurrentBreakpoint that happens in native.nativeProcess.stop in proc_windows.go
3. since the thread with the breakpoint set is not CurrentThread the call to pickCurrentThread further down inside Continue wasn't made
4. if I'm right there isn't a whole lot happening between point 3 and point 4 and the most likely culprit is something happening in native.nativeProcess.stop, which would have to be instrumented to figure out what's going wrong

**Comment by nd** [comment] 2020-12-12 13:38
I think I can reproduce it (although not reliably) by debugging 

```
package main

import (
	"fmt"
	"time"
)

func main() {
	i := 0
	for {
		i++
		time.Sleep(time.Microsecond)
		fmt.Print("")
	}
}
```

and adding and removing a breakpoint a few times (breakpoint line doesn't matter). I put a breakpoint in zsyscall_windows.go _SuspendThread() where it returns an error and once it happens Delve doesn't respond to commands anymore. Every time it happens Delve is calling suspend on a DbgUiRemoteBreakIn thread (checked that in ProcExplorer).

**Comment by nd** [comment] 2020-12-12 13:50
Not sure if that's matter, but I've added some logging to debugger event loop and it looks like _SuspendThread works fine on DbgUiRemoteBreakIn the last event is _EXCEPTION_BREAKPOINT on this thread. And when _SuspendThread fails with an error, _EXCEPTION_BREAKPOINT on DbgUiRemoteBreakIn is followed by 80000003 on some other thread.

**Comment by nd** [comment] 2020-12-13 08:59
Also found that when suspend fails, prevsuspcount is 2^32-1

**Comment by nd** [comment] 2020-12-14 06:55
@x13pixels, the author of [remedybg](https://remedybg.itch.io/remedybg), suggested that debugger shouldn't call suspend on a DbgUiRemoteBreakIn since it is a auxiliary thread created by OS for debugging purposes. He also shown how Visual Studio debugger detects DbgUiRemoteBreakIn threads:

```
HMODULE module_handle = GetModuleHandle("ntdll.dll");
if (module_handle) {
   FARPROC addr = GetProcAddress(module_handle, "DbgUiRemoteBreakin");
   if (addr == (FARPROC)evt->u.CreateThread.lpStartAddress) {
      // this is the breakin thread
   }
}
```

I've tried to do the same check in event loop, store a flag in a thread whether it is a DbgUiRemoteBreakIn, and then skip calling suspend if it is. With that I cannot reproduce the problem anymore.

**Comment by aarzilli** [comment] 2020-12-16 08:36
That sounds reasonable, since you have already done the change do you mind submitting it as a PR?

**Comment by aarzilli** [comment] 2020-12-16 08:37
PS This is also a duplicate of #1170.

**Comment by nd** [comment] 2020-12-28 09:41
Sorry for delay.

**Closed** 2020-12-28 17:07 UTC
Labels: area/proc/native, os/windows
