### ISSUE TITLE
Not compiling on raspberry pi 3b

### ISSUE THREAD

**Issue by jobo-zt** [go-delve/delve#3688] opened 2024-03-25 11:00 UTC
Not compiling on raspberry pi 3b

go install github.com/go-delve/delve/cmd/dlv@latest
../../go/pkg/mod/github.com/go-delve/delve@v1.22.1/service/debugger/debugger.go:32:2: found packages native (dump_linux.go) and your_linux_architecture_is_not_supported_by_delve (support_sentinel_linux.go) in /home/pi/go/pkg/mod/github.com/go-delve/delve@v1.22.1/pkg/proc/native

**Comment by aarzilli** [comment] 2024-03-25 11:32
Delve doesn't support arm32. You can install a 64bit OS and go toolchain. Duplicate of #2051.

**Closed by aarzilli** 2024-03-25 11:32 UTC
