### ISSUE TITLE
Apple M1 ARM : debug failed

### ISSUE THREAD

**Issue by a1binos** [go-delve/delve#2258] opened 2020-12-10 10:06 UTC
API server listening at: 127.0.0.1:21253
could not launch process: protocol error E74 during registers read for packet $g;thread:19134;
Process exiting with code: 1

go version go1.15.6 darwin/amd64
dlv version
Delve Debugger
Version: 1.2.0
Build: $Id: 068e2451004e95d0b042e5257e34f0f08ce01466 $

**Comment by aarzilli** [comment] 2020-12-10 10:08
Duplicate of #2246

**Closed by aarzilli** 2020-12-10 10:08 UTC
