### ISSUE TITLE
debugserver: (os/kern) invalid argument

### ISSUE THREAD

**Issue by liuhao2050** [go-delve/delve#2304] opened 2021-01-17 12:10 UTC
1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.5.1
Build: $Id: bca418ea7ae2a4dcda985e623625da727d4525b5 $
```
2. What version of Go are you using? (`go version`)?
```
go version go1.16beta1 darwin/arm64
```
3. What operating system and processor architecture are you using?
```
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
MacBook Pro (13-inch, M1, 2020)
```
4. What did you do?
```
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install

/Applications/GoLand.app/Contents/plugins/go/lib/dlv/mac/dlv --listen=0.0.0.0:49972 --headless=true --api-version=2 --check-go-version=false --only-same-user=false exec main
```
5. What did you expect to see?
debug server start
6. What did you see instead?
```
API server listening at: [::]:49972
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1200.0.44
 for x86_64.
error: failed to launch process /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver: (os/kern) invalid argument
Exiting.
could not launch process: stub exited while waiting for connection: exit status 0
```

**Comment by aarzilli** [comment] 2021-01-17 13:10
Closing, duplicate of #2302

**Closed by aarzilli** 2021-01-17 13:10 UTC
