### ISSUE TITLE
Stepping through the code invokes undefined behavior

### ISSUE THREAD

**Issue by rillig** [go-delve/delve#2305] opened 2021-01-17 19:55 UTC
As detailed in #1134, Delve shows variables as being in scope even though they are not.

1. What version of Delve are you using (`dlv version`)?
1.5.0 775c923ec41e92db72122482d69343ef712546c7
2. What version of Go are you using? (`go version`)?
go1.15
3. What operating system and processor architecture are you using?
amd64
4. What did you do?
5. What did you expect to see?
The file `evil file.txt` does not get created.
6. What did you see instead?
Delve incorrectly thinks that `local` is in scope before it is initialized.

~~~go
package main

import "os"

// How to produce an unintended function call during debugging because
// of a watch expression on an uninitialized variable that is nevertheless
// listed by Delve as being in scope.
//
// See https://github.com/go-delve/delve/issues/1134.
//
// Set a breakpoint in main().
// Add a watch expression "local.result()".
// Start the debugger and slowly step through the code, step by step.

func main() {
	demo()
}

type command struct {
	name   string
	action func()
}

func (c command) result() string {
	c.action()
	return c.name
}

func demo() {
	good := command{"good", func() { println("I'm good") }}
	bad := command{"bad", func() { _, _ = os.Create("evil file.txt") }}

	// 1. This call prepares the memory on the stack with the bad command.
	prepare(bad)

	// 4. Now the stack is filled with the bad command.
	// The function will do unexpected things with the watch expression.
	action(good)

	// Force command.result to be compiled into the binary.
	if len(os.Args) > 1000 {
		for _, c := range history {
			println(c.result())
		}
	}
}

// prepare has the same code and memory layout as the action.
// It doesn't have a breakpoint though.
//go:noinline
func prepare(x interface{}) {
	// 2. Copy the data from the bad command to the stack.
	dontTriggerTheWatchExpression := x.(command)
	// 3. Make sure that the local variable is not optimized away
	// by escape analysis and all the other magic.
	remember(&dontTriggerTheWatchExpression)
}

//go:noinline
func action(x interface{}) {
	// 5. The stack memory is still the same as when prepare() returned.
	// This means that "local" still contains the bad command.
	// Having the watch expression "local.result()" will therefore call the
	// function from the bad command, which creates the evil file.
	//
	// To actually see that the file has been created as soon as this line
	// is reached, press Ctrl+Alt+Y since GoLand doesn't receive any
	// filesystem change events (see IDEA-215900).
	//
	// The same technique can also be used for type confusion since the data
	// on the stack is interpreted as the type of the variable. That type
	// information is taken from the executable binary, not from the stack
	// memory.
	local := x.(command)
	remember(&local)
}

// Prevent the optimizer from eliminating the local variables.
var history []*command

// Force the command to escape from the stack to the heap.
//go:noinline
func remember(c *command) {
	history = append(history, c)
}
~~~

**Comment by aarzilli** [comment] 2021-01-17 20:34
Can't reproduce:

```
(dlv) b action
Breakpoint 1 set at 0x489d73 for main.action() ./test.go:50
(dlv) c
> main.action() ./test.go:50 (hits goroutine(1):1 total:1) (PC: 0x489d73)
    45:		// by escape analysis and all the other magic.
    46:		remember(&dontTriggerTheWatchExpression)
    47:	}
    48:	
    49:	//go:noinline
=>  50:	func action(x interface{}) {
    51:		local := x.(command)
    52:		remember(&local)
    53:	}
    54:	
    55:	// Prevent the optimizer from eliminating the local variables.
(dlv) locals
(no locals)
(dlv) s
> main.action() ./test.go:51 (PC: 0x489d81)
    46:		remember(&dontTriggerTheWatchExpression)
    47:	}
    48:	
    49:	//go:noinline
    50:	func action(x interface{}) {
=>  51:		local := x.(command)
    52:		remember(&local)
    53:	}
    54:	
    55:	// Prevent the optimizer from eliminating the local variables.
    56:	var history []*command
(dlv) locals
(no locals)
(dlv) args
x = interface {}(main.command) {name: "good", action: main.demo.func1}
(dlv) call local.result()
> main.action() ./test.go:51 (PC: 0x489d81)
Command failed: could not find symbol value for local
(dlv) n
> main.action() ./test.go:52 (PC: 0x489e02)
    47:	}
    48:	
    49:	//go:noinline
    50:	func action(x interface{}) {
    51:		local := x.(command)
=>  52:		remember(&local)
    53:	}
    54:	
    55:	// Prevent the optimizer from eliminating the local variables.
    56:	var history []*command
    57:	
(dlv) locals
local = main.command {name: "good", action: main.demo.func1}
(dlv) call local.result()
> main.action() ./test.go:52 (PC: 0x489e02)
Command failed: call not at safe point
(dlv) 
```

go version 1.15.6

**Comment by rillig** [comment] 2021-01-18 00:02
That's interesting. I tried it again using the current dlv.exe from 82fcd2cb268bd0ab2cb8d8a2f0050906f3d32b64:

~~~text
$ dlv version
Delve Debugger
Version: 1.5.1
Build: $Id: bca418ea7ae2a4dcda985e623625da727d4525b5 $

$ dlv exec go8530-delve-1334.exe
(dlv) b action
(dlv) c
> main.action() c:/users/rillig/go/src/github.com/rillig/go-playground/go8530-delve-1334/demo.go:40 (hits goroutine(1):1 total:1) (PC:
 0x46da5a)
Warning: debugging optimized function
    39: //go:noinline
=>  40: func action(x interface{}) {
(dlv) s
> main.action() c:/users/rillig/go/src/github.com/rillig/go-playground/go8530-delve-1334/demo.go:41 (PC: 0x46da68)
Warning: debugging optimized function
=>  41:         local := x.(command)
(dlv) args
x = interface {}(main.command) {name: "good", action: main.demo.func1}
(dlv) locals
local = main.command {name: "", action: nil}
(dlv) exit
~~~

Even though `local` is not yet in scope, its value is shown. I have no idea why `local` is in scope for me but not for you.

When I follow my instructions precisely, I get a different result:

~~~text
b main.main
s
s
s   # until you reach this line: local := x.(command)
> demo.go:41 (PC: 0x46da68)
Warning: debugging optimized function
    40: func action(x interface{}) {
=>  41:         local := x.(command)
    42:         remember(&local)
(dlv) args
x = interface {}(main.command) {name: "good", action: main.demo.func1}
(dlv) locals
local = (unreadable no address for escaped variable)
~~~

Again, `local` should not be in scope.
I don't understand the error message "unreadable no address" though. Is there a colon missing after the "unreadable"?

I inspected the code for both functions, and it is exactly the same.
This means the problem _should_ be reproducible.
I could only reproduce it from within GoLand though, with Delve 1.5.0 775c923ec41e92db72122482d69343ef712546c7.
From the command line `dlv.exe` I get some strange error messages and `local` is in scope, but the file `evil file.txt` doesn't get created.
I'll research the difference.

**Comment by aarzilli** [comment] 2021-01-18 06:24
If this only happens with a binary compiled with optimizations, then it's not a bug. The fact that variables can contain garbage when debugging optimized code is normal. You shouldn't blindly inject function calls and, really, you should keep an eye on a disassembly view to make sense of what's happening.

**Comment by rillig** [comment] 2021-01-18 23:43
Now that you mention it: I rebuilt the demo program with `go -gcflags '-N -l'`, and it shows exactly the same behavior as in GoLand, that is, when stepping through the code, it creates `evil file.txt`.

To me this means that it _is_ a bug since it is reliably reproducible with an unoptimized binary.

**Comment by aarzilli** [comment] 2021-01-20 08:30
Closing, not a bug in delve.

**Closed by aarzilli** 2021-01-20 08:30 UTC

**Comment by rillig** [comment] 2021-01-21 00:41
Why is this "not a bug"? I reproduced it with an unoptimized binary.
