### ISSUE TITLE
Xcode 16 tool chain (associated with macOS 15) appears to break delve ability to access debug data.

### ISSUE THREAD

**Issue by tucats** [go-delve/delve#3811] opened 2024-09-17 18:04 UTC
1. What version of Delve are you using (`dlv version`)?

   tom@Nomad ego % dlv version
   Delve Debugger
   Version: 1.22.1
   Build: $Id: 0c3470054da6feac5f6dcf3e3e5144a64f7a9a48 $

2. What version of Go are you using? (`go version`)?

   tom@Nomad ego % go version
   go version go1.23.1 darwin/arm64

3. What operating system and processor architecture are you using?

   macOS 15.0 (Sequoia) on Apple M1 Pro chip

   tom@Nomad ego % uname -a
   Darwin Nomad 24.0.0 Darwin Kernel Version 24.0.0: Mon Aug 12 20:51:54 PDT 2024;
   root:xnu-11215.1.10~2/RELEASE_ARM64_T6000 arm64

   ** This was experienced using Xcode 16.0, build 16A242. This is the new version
      of the tool chain just released to go with macOS 15.0

4. What did you do?

   Attempting to run debugger for Go project. Initially started using VS Code, but
   also found replicates in command line. Here is the command line to launch debugging
   that I used:

   tom@Nomad ego % ~/go/bin/dlv debug

5. What did you expect to see?

   Standard (dlv) prompt to start debugging.

6. What did you see instead?

   tom@Nomad ego % ~/go/bin/dlv debug
   2024-09-17T13:54:08-04:00 error layer=debugger error loading binary
   "/Users/tom/go/src/github.com/tucats/ego/__debug_bin3142403853": 
   error reading debug_info: 
   decoding dwarf section info at offset 0x21a05b: 
   DW_FORM_strx with no .debug_str_offsets section could not launch process: 
   error reading debug_info: 
   decoding dwarf section info at offset 0x21a05b: 
   DW_FORM_strx with no .debug_str_offsets section

Note that if I roll back my Xcode to the previous version (Xcode 15.x) then dlv works perfectly, as well as the rest of the golang tool chain. I would guess that Apple has made some further changes in the DWARF dSym processing; I note that when I did a build using the _new_
toolchain including Xcode 16, the resulting application file went from 20mb to 14mb, so I assume that a lot of the debug data was parked somewhere else, perhaps.

**Comment by tucats** [comment] 2024-09-17 18:11
I see I was running an old version of dlv; I've upgraded. My dlv version info now is:

```sh
Delve Debugger
Version: 1.23.0
Build: $Id: e673f2da02185a1c2b6dea52842b0a8c7e7a03b9 $
```

This does not change the result of the output error:

```sh
tom@Nomad ego % ~/go/bin/dlv debug
2024-09-17T14:09:21-04:00 error layer=debugger error loading binary "/Users/tom/go/src/github.com/tucats/ego/__debug_bin1897865194": error reading debug_info: decoding dwarf section info at offset 0x21a05b: DW_FORM_strx with no .debug_str_offsets section
could not launch process: error reading debug_info: decoding dwarf section info at offset 0x21a05b: DW_FORM_strx with no .debug_str_offsets section
```

**Comment by aarzilli** [comment] 2024-09-17 19:49
Duplicate of #3797

**Closed by aarzilli** 2024-09-17 19:49 UTC
