### ISSUE TITLE
How to upgrade delve?

### ISSUE THREAD

**Issue by RylanSchaeffer** [go-delve/delve#1512] opened 2019-03-15 21:15 UTC
How does one update their delve? I"m receiving the following error when I try to set the api version:

`unknown flag: --api-version`

My `dlv` looks out of date:

```
$dlv version
Delve Debugger
Version: 0.11.0-alpha
Build: 
```

But I can't figure out how to upgrade it. I've tried `go get -u github.com/go-delve/delve/cmd/dlv` and `go get -u github.com/derekparker/delve/cmd/dlv`, but neither worked. I also tried the suggestion to `make install`:

```
$ git clone https://github.com/go-delve/delve.git $GOPATH/src/github.com/go-delve/delve
$ cd $GOPATH/src/github.com/go-delve/delve
$ make install
```

But that appears to have no effect:

```
$ dlv version
Delve Debugger
Version: 0.11.0-alpha
Build:
```
My go version is `go version go1.10.1 linux/amd64` and my OS details are below:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.11 (jessie)
Release:	8.11
Codename:	jessie
```

**Comment by dlsniper** [comment] 2019-03-21 09:53
See where your delve binary currently is installed, run ` which dlv ` and use that output to compare it with your ` $GOPATH/bin ` location to see if they are the same or not.

**Comment by aarzilli** [comment] 2019-03-29 07:08
Closing, not a bug (also what @dlsniper said).

**Closed by aarzilli** 2019-03-29 07:08 UTC
