### ISSUE TITLE
Using Debugger.Restart tries to close ptrace chan while closed. causing panic

### ISSUE THREAD

**Issue by emad-elsaid** [go-delve/delve#3065] opened 2022-07-17 10:07 UTC
I'm working on a UI app for Delve. I'm using `delve/service/api` package and `delve/service/debugger` to start a debugger and build an interface around it that controls it. while writing a method that should restart the debugged process I found the following issue: 

- I have a function that uses an instance of `Debugger` 
- The debugged process is continued so it's running
- I want to rebuild and restart the process 
- so I execute `Restart` function as follows:

```go 
_, err := d.Debugger.Restart(false, "", false, []string{}, [3]string{}, true)
```
I get the following panic:

```
 panic: close of closed channel

 goroutine 8 [running]:
 github.com/go-delve/delve/pkg/proc/native.(*nativeProcess).postExit(0xc000035700)
    /home/emad/go/pkg/mod/github.com/go-delve/delve@v1.9.0/pkg/proc/native/proc.go:294 +0x2d
 github.com/go-delve/delve/pkg/proc/native.(*nativeProcess).kill(0xc000035700)
    /home/emad/go/pkg/mod/github.com/go-delve/delve@v1.9.0/pkg/proc/native/proc_linux.go:230 +0x225
 github.com/go-delve/delve/pkg/proc/native.(*nativeProcess).Detach(0xc000035700, 0x1)
    /home/emad/go/pkg/mod/github.com/go-delve/delve@v1.9.0/pkg/proc/native/proc.go:75 +0x65
 github.com/go-delve/delve/pkg/proc.(*Target).Detach(0xc001466000?, 0xc?)
    /home/emad/go/pkg/mod/github.com/go-delve/delve@v1.9.0/pkg/proc/target.go:355 +0x99
 github.com/go-delve/delve/service/debugger.(*Debugger).detach(...)
    /home/emad/go/pkg/mod/github.com/go-delve/delve@v1.9.0/service/debugger/debugger.go:440
 github.com/go-delve/delve/service/debugger.(*Debugger).Restart(0xc0000f0370, 0x0, {0x0, 0x0}, 0x0, {0xc0000db9b8, 0x0, 0x0?}, {{0x0, 0x0}, ...}, ...)
   /home/emad/go/pkg/mod/github.com/go-delve/delve@v1.9.0/service/debugger/debugger.go:472 +0x37a
```

I traced it to this line: 
https://github.com/go-delve/delve/blob/3fb2d49829187388d75c70fa46a18e0361a0292f/pkg/proc/native/proc.go#L294

I'm not sure what's this channel used for and why is it closed in my case.

1. What version of Delve are you using (`dlv version`)? in my go.mod `github.com/go-delve/delve v1.9.0` 
2. What version of Go are you using? (`go version`)? `1.18`
3. What operating system and processor architecture are you using? `Linux terra 5.18.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 22 Jun 2022 18:10:56 +0000 x86_64 GNU/Linux`
4. What did you do? tried to restart a debugged process using `Debugger` struct instance 
5. What did you expect to see? I expected the process to stop, recompile and wait to be continued
6. What did you see instead? panic

**Comment by aarzilli** [comment] 2022-07-17 11:01
Do you have a minimum reproducer? The channel only gets closed in that function, AFAICT, and that function also sets exited = true. If exited is true kill isn't called by Detach.

**Comment by emad-elsaid** [comment] 2022-07-17 17:44
Hi @aarzilli I managed to reproduce the issue with this example here 
https://github.com/emad-elsaid/delvetest
- `main.go` stands for the debugger. 
- when you run it it'll change current dir to `server` 
- Then compile the files in there to `debug` bin
- Then attach a debugger to it and continue with the execution
- After 5 seconds it'll try to restart the process

- `server/main.go` is an HTTP server. just one line

I'm getting this output
```
2022/07/17 19:39:38 Will start a server at 8090
panic: close of closed channel

goroutine 1 [running]:
github.com/go-delve/delve/pkg/proc/native.(*nativeProcess).postExit(0xc000035280)
        /home/emad/go/pkg/mod/github.com/go-delve/delve@v1.9.0/pkg/proc/native/proc.go:294 +0x2d
github.com/go-delve/delve/pkg/proc/native.(*nativeProcess).kill(0xc000035280)
        /home/emad/go/pkg/mod/github.com/go-delve/delve@v1.9.0/pkg/proc/native/proc_linux.go:230 +0x225
github.com/go-delve/delve/pkg/proc/native.(*nativeProcess).Detach(0xc000035280, 0x1)
        /home/emad/go/pkg/mod/github.com/go-delve/delve@v1.9.0/pkg/proc/native/proc.go:75 +0x65
github.com/go-delve/delve/pkg/proc.(*Target).Detach(0xc0000c6000?, 0x18?)
        /home/emad/go/pkg/mod/github.com/go-delve/delve@v1.9.0/pkg/proc/target.go:355 +0x99
github.com/go-delve/delve/service/debugger.(*Debugger).detach(...)
        /home/emad/go/pkg/mod/github.com/go-delve/delve@v1.9.0/service/debugger/debugger.go:440
github.com/go-delve/delve/service/debugger.(*Debugger).Restart(0xc0000a4000, 0x0, {0x0, 0x0}, 0x0, {0xc000235e18, 0x0, 0x7fb72a435e60?}, {{0x0, 0x0}, ...}, ...)
        /home/emad/go/pkg/mod/github.com/go-delve/delve@v1.9.0/service/debugger/debugger.go:472 +0x37a
main.main()
        /home/emad/code/delvetest/main.go:43 +0x465
exit status 2
```

**Comment by aarzilli** [comment] 2022-07-17 18:31
You can't manipulate the target directly without holding targetMutex. The problem is the line that says `go d.Target().Continue()`, furthermore Restat can only be called if the target is stopped. You can rewrite this using `d.Command(api.Continue)` instead of calling Continue directly, and `d.Command(halt); d.Restart()` instead of just Restart.

**Closed by aarzilli** 2022-07-17 18:31 UTC
Labels: kind/needs more info

**Comment by emad-elsaid** [comment] 2022-07-17 22:09
I see. when I tried to do that. I found out that the `debugger` instance won't respond (just hangs waiting for the process to break/trap) to any method like 
```
reason := d.StopReason()
```
as long as the debugged process is running. is it possible to have the debugged process running while I'm still able to ask the debugger? or should I go lower and manipulate the target in my code instead of using the high level `command` function?

**Comment by aarzilli** [comment] 2022-07-18 04:49
In general, the os won't let you do much with a running process except stopping it.

**Comment by emad-elsaid** [comment] 2022-07-18 13:14
I was hoping of getting the list of files, funcs, types, go routines, stack frames for each and switching between go routines while the process is running. right now I'm circumventing the Debugger service and using the target directly. 
do you think there is danger for doing that? is locking the target actually was for a reason that concerns my usecase?

**Comment by emad-elsaid** [comment] 2022-07-18 22:38
That's really helpful, thanks for all your effort.

one last thing I want to clarify in the second part of your comment :
> you can't read the memory of a running process

Right now on my linux machine I'm able to run the process and while it's running I can ask for the list of go routines and each stack trace and for each stack frame I can ask for local variables. 
So should I assume you're talking about a different system that doesn't allow that? and also is there any material I can read about that to help me understand how Delve works and the design decisions?

**Comment by aarzilli** [comment] 2022-07-19 04:43
> Right now on my linux machine I'm able to run the process and while it's running I can ask for the list of go routines and each stack trace and for each stack frame I can ask for local variables.

That's interesting. Are you sure? The man page of ptrace(2) states that:

> For requests other than PTRACE_ATTACH, PTRACE_SEIZE, PTRACE_INTERRUPT, and PTRACE_KILL, the tracee must be stopped.

And the implementation of the ptrace system call matches this:

https://elixir.bootlin.com/linux/v5.18.12/source/kernel/ptrace.c#L1321
https://elixir.bootlin.com/linux/v5.18.12/source/kernel/ptrace.c#L246

you might be using a cached copy of the registers.

**Comment by emad-elsaid** [comment] 2022-07-22 08:41
Yes, I believe you're right. it's probably the cached data I'm getting back.
