### ISSUE TITLE
panic in proc.FirstPCAfterPrologue

### ISSUE THREAD

**Issue by JAicewizard** [go-delve/delve#1618] opened 2019-07-16 10:54 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linkted gists.

1. What version of Delve are you using (`dlv version`)?
Version: 1.1.0
Build: 4e4ed0294807c7be65513112bde18dd70c0f165f
2. What version of Go are you using? (`go version`)?
go version go1.12.7 linux/amd64
3. What operating system and processor architecture are you using?
linux AMD64
4. What did you do?
press 'n'
5. What did you expect to see?
dlv going to the next line
6. What did you see instead?
https://gist.github.com/JAicewizard/c26b22dd55233623219773136cd9b928

looks very similar to https://github.com/go-delve/delve/issues/754

for some reason this only happens in the following function(for me):
https://gist.github.com/JAicewizard/0b7e3819490784eb11595c5870793e57

**Comment by aarzilli** [comment] 2019-07-16 14:34
I can't reproduce this, even with the exact same version of delve and go. Can you update to the latest version of delve (clone the repository and build it) and see if it still happens? Can I see the binary that causes this problem?

**Comment by JAicewizard** [comment] 2019-07-16 15:56
It might not be that function on its own, but if I breakpoint at the first line of that function, continue until that breakpoint, and then do anything it happens. I don't have time to dive deeper into this ATM, I will continue when I'm back from vacation.

**Comment by aarzilli** [comment] 2019-08-14 12:48
Closing, no feedback.

**Closed by aarzilli** 2019-08-14 12:48 UTC
Labels: kind/needs more info
