### ISSUE TITLE
How to use dlv core with go test runs

### ISSUE THREAD

**Issue by abergmeier** [go-delve/delve#2205] opened 2020-10-19 13:49 UTC
Please answer the following before submitting your issue:

1. What version of Delve are you using (`dlv version`)? 
1.5.0
2. What version of Go are you using? (`go version`)?
1.15.2
3. What operating system and processor architecture are you using?
Ubuntu 20.04
4. What did you do?
```
GOTRACEBACK=crash go test ./...
dlv core $(which go) /tmp/coredump
```
5. What did you expect to see?
dlv should either figure out automatically where these tests came from.
In a less perfect world it would also be ok to have some documentation how to make this dlv work in this scenario.
6. What did you see instead?
```
could not open debug info
```

I noticed that in `/tmp/coredump` there are references to temporary build directories (`/tmp/go-build113399960/b522`). "Sadly" these get properly cleaned up in the crash mode.

**Comment by aarzilli** [comment] 2020-10-19 14:59
The only way to do this is to compile the tests with `-c` and then do `dlv core /path/to/test/executable /tmp/coredump`

**Comment by abergmeier** [comment] 2020-10-19 15:03
> The only way to do this is to compile the tests with go test -c and then do dlv core /path/to/test/executable /tmp/coredump

Learned something new today. Thanks.

**Comment by aarzilli** [comment] 2020-10-19 15:24
Regarding finding the executable automatically, as you noticed `go test` cleans up the output of its compilation automatically and, even if it didn't, I believe it behaves like `go run` in that it does not generate debug info while compiling.

**Comment by abergmeier** [comment] 2020-10-19 19:51
Yes it seems debug info is at least not fully there.
For my case, it seems somehow I triggered some corruptions. Not clear whether dlv would have helped even with debug info.
Nevertheless - is there a way of adding debug info with `go test -c`?

**Comment by aarzilli** [comment] 2020-10-19 19:56
> Yes it seems debug info is at least not fully there.
> For my case, it seems somehow I triggered some corruptions. Not clear whether dlv would have helped even with debug info.
> Nevertheless - is there a way of adding debug info with `go test -c`?

`go test -c -gcflags='all=-N -l'`. Is there any particular reason why you can't use `dlv test`?

**Comment by abergmeier** [comment] 2020-10-19 20:01
> Is there any particular reason why you can't use dlv test?

`dlv test` does not seem to support recursion (e.g. ./...). Which in my concurrency test is what I need.

**Comment by aarzilli** [comment] 2020-10-21 12:18
Closing, not a bug.

**Closed by aarzilli** 2020-10-21 12:18 UTC

**Comment by abergmeier** [comment] 2020-10-21 12:50
Is all the information you provided a case for FAQ or documentation?

**Comment by aarzilli** [comment] 2020-10-22 13:43
> Is all the information you provided a case for FAQ or documentation?

I've thought about it and I'm not sure where to put it.
