### ISSUE TITLE
Prompt error when installing dlv in Termux

### ISSUE THREAD

**Issue by Droid-MAX** [go-delve/delve#1697] opened 2019-09-24 14:22 UTC
I just installed dlv on the termux as written in the README, but there was an error like the described below.

1. OS Info:
Android 7.0 & Arch is aarch64/armv8a

2. Go Version:
go1.12.7

3. Output Result:
go/src/github.com/go-delve/delve/pkg/proc/disasm.go:10:14: undefined: archInst

**Comment by chainhelen** [comment] 2019-09-26 03:36
https://github.com/go-delve/delve/pull/1690  

AARCH64 platform is not supported currently, but soon.

**Comment by aarzilli** [comment] 2019-09-27 11:12
Duplicate of #118

**Closed by aarzilli** 2019-09-27 11:12 UTC
