### ISSUE TITLE
Can't evaluate struct creation

### ISSUE THREAD

**Issue by kmillikin** [go-delve/delve#3177] opened 2022-10-27 11:10 UTC
Delve `Version: 1.9.1` and Go `go version go1.20-pre3 cl/474093167 +a813be86df linux/amd64`.

Test case is simple:

```go
package main

import "fmt"

type Options struct {
        WithBreakfast bool
        WithLunch     bool
        WIthDinner    bool
}

func main() {
        x := Options{}
        fmt.Sprintf("%v", x)
}
```
Set a breakpoint in main and try to evaluate `Options{}`:

```
(dlv) break main.go:13
Breakpoint 1 set at 0x49cca4 for main.main() ./main.go:13
(dlv) c
> main.main() ./main.go:13 (hits goroutine(1):1 total:1) (PC: 0x49cca4)
     8:         WIthDinner    bool
     9: }
    10:
    11: func main() {
    12:         x := Options{}
=>  13:         fmt.Sprintf("%v", x)
    14: }
(dlv) call Options{}
> main.main() ./main.go:13 (hits goroutine(1):1 total:1) (PC: 0x49cca4)
Command failed: expression *ast.CompositeLit not implemented
```
I should be able to evaluate this here, it's on a line just after an identical expression.  (The error message is also really cryptic.)

**Comment by aarzilli** [comment] 2022-10-28 13:01
Duplicate of #1465

**Closed by aarzilli** 2022-10-28 13:01 UTC
