### ISSUE TITLE
Allow users to pause and resume the execution of a goroutine

### ISSUE THREAD

**Issue by pellared** [go-delve/delve#2262] opened 2020-12-11 21:46 UTC
One of the features that I miss the most is the possibility of pausing and then resuming the execution of a goroutine.

The race detector does not cover all possible cases - e.g. when the issue is "correct" from memory+execution perspective but invalid from "acceptance" perspective. Meaning there can be a valid concurrent program which simply does not what we expected.

Before I was developing mainly in C# and I was using https://docs.microsoft.com/pl-pl/visualstudio/debugger/how-to-use-the-threads-window?view=vs-2019#freeze-and-thaw-thread-execution to analyze such problems.

If pausing/resuming the execution of a goroutine is not possible maybe it would be enough even to allow doing it for the thread running current goroutine?

**Comment by aarzilli** [comment] 2020-12-12 14:00
This is basically a duplicate of #1529 (technically it's a superset of that, but I'm still going to close it as duplicate). The bottom line is that it can't be done without [assistance from the runtime](https://github.com/golang/go/issues/31132), even freezing a single thread.

**Closed by aarzilli** 2020-12-12 14:00 UTC
