### ISSUE TITLE
panic when debugging golang compiler code

### ISSUE THREAD

**Issue by dragonly** [go-delve/delve#3208] opened 2022-12-04 09:04 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.9.1
Build: $Id: d81b9fd12bfa603f3cf7a4bc842398bd61c42940 $
2. What version of Go are you using? (`go version`)?
Installed go is `go version go1.19.3 darwin/arm64`
However, I am debugging the latest golang code `go version devel go1.20-d5de62df15 Thu Nov 24 06:48:07 2022 +0000 darwin/arm64`
3. What operating system and processor architecture are you using?
Darwin Macbook-Air-M1 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64
4. What did you do?
Use vscode, configure `"go.goroot": "/Users/dragonly/github/go"` and debug the test `ExampleScope` in `cmd/compile/internal/types2/example_test.go`.
5. What did you expect to see?
Debugger stops at the break point
6. What did you see instead?
Debugger panics with the following log
```
Starting: /Users/dragonly/go/bin/dlv dap --check-go-version=false --listen=127.0.0.1:58299 --log-dest=3 from /Users/dragonly/github/go/src/cmd/compile/internal/types2
DAP server listening at: 127.0.0.1:58299
Type 'dlv help' for list of commands.
2022-12-04T17:02:48+08:00 error layer=dap recovered panic: <nil> not an Int
goroutine 10 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/go-delve/delve/service/dap.(*Session).recoverPanic(0x140000c6000, {0x103664838, 0x14000cc68d0})
	/Users/dragonly/go/pkg/mod/github.com/go-delve/delve@v1.9.1/service/dap/server.go:557 +0x48
panic({0x10359eb00, 0x1400011b550})
	/usr/local/go/src/runtime/panic.go:884 +0x204
go/constant.Int64Val({0x0?, 0x0?})
	/usr/local/go/src/go/constant/value.go:503 +0x128
github.com/go-delve/delve/pkg/proc.(*Variable).parseG.func2({0x1034710a9?, 0x1400103a8e0?})
	/Users/dragonly/go/pkg/mod/github.com/go-delve/delve@v1.9.1/pkg/proc/variables.go:885 +0x4c
github.com/go-delve/delve/pkg/proc.(*Variable).parseG(0x10366dfd8?)
	/Users/dragonly/go/pkg/mod/github.com/go-delve/delve@v1.9.1/pkg/proc/variables.go:921 +0x77c
github.com/go-delve/delve/pkg/proc.GetG({0x10366dfd8, 0x1400026e2a0})
	/Users/dragonly/go/pkg/mod/github.com/go-delve/delve@v1.9.1/pkg/proc/variables.go:259 +0xc8
github.com/go-delve/delve/pkg/proc.(*BreakpointState).checkCond(0x1400026e318, 0x1400030c690?, 0x14001264ff0, {0x10366dfd8, 0x1400026e2a0})
	/Users/dragonly/go/pkg/mod/github.com/go-delve/delve@v1.9.1/pkg/proc/breakpoints.go:270 +0x10c
github.com/go-delve/delve/pkg/proc.(*Breakpoint).checkCondition(0x140002ba000?, 0x14000749b00?, {0x10366dfd8, 0x1400026e2a0}, 0x1400026e318)
	/Users/dragonly/go/pkg/mod/github.com/go-delve/delve@v1.9.1/pkg/proc/breakpoints.go:247 +0xbc
github.com/go-delve/delve/pkg/proc.(*TargetGroup).Continue(0x14001a4e180)
	/Users/dragonly/go/pkg/mod/github.com/go-delve/delve@v1.9.1/pkg/proc/target_exec.go:92 +0x8e0
github.com/go-delve/delve/service/debugger.(*Debugger).Command(0x1400015c6e0, 0x14001a57af0, 0x1400127a5a0)
	/Users/dragonly/go/pkg/mod/github.com/go-delve/delve@v1.9.1/service/debugger/debugger.go:1228 +0x9d8
github.com/go-delve/delve/service/dap.(*Session).resumeOnce(0x140000c6000, {0x10346dfa2, 0x8}, 0x1400127a420)
	/Users/dragonly/go/pkg/mod/github.com/go-delve/delve@v1.9.1/service/dap/server.go:3456 +0x1d4
github.com/go-delve/delve/service/dap.(*Session).resumeOnceAndCheckStop(0x140000c6000, {0x10346dfa2, 0x8}, 0x14001a57bc0?)
	/Users/dragonly/go/pkg/mod/github.com/go-delve/delve@v1.9.1/service/dap/server.go:3599 +0x28
github.com/go-delve/delve/service/dap.glob..func1(0x14000345ee0?, {0x10346dfa2?, 0x58?}, 0x58?)
	/Users/dragonly/go/pkg/mod/github.com/go-delve/delve@v1.9.1/service/dap/server.go:3595 +0x20
github.com/go-delve/delve/service/dap.(*Session).runUntilStop(0x140000c6000, {0x10346dfa2, 0x8}, 0x103096dc0?)
	/Users/dragonly/go/pkg/mod/github.com/go-delve/delve@v1.9.1/service/dap/server.go:3587 +0xb4
github.com/go-delve/delve/service/dap.(*Session).runUntilStopAndNotify(0x140000c6000, {0x10346dfa2, 0x8}, 0x102fd67b8?)
	/Users/dragonly/go/pkg/mod/github.com/go-delve/delve@v1.9.1/service/dap/server.go:3467 +0x30
github.com/go-delve/delve/service/dap.(*Session).onConfigurationDoneRequest(0x140000c6000, 0x14000cc68d0, 0x1400127a420)
	/Users/dragonly/go/pkg/mod/github.com/go-delve/delve@v1.9.1/service/dap/server.go:1565 +0x264
github.com/go-delve/delve/service/dap.(*Session).handleRequest.func1()
	/Users/dragonly/go/pkg/mod/github.com/go-delve/delve@v1.9.1/service/dap/server.go:684 +0x68
created by github.com/go-delve/delve/service/dap.(*Session).handleRequest
	/Users/dragonly/go/pkg/mod/github.com/go-delve/delve@v1.9.1/service/dap/server.go:682 +0xbb8
```

**Comment by aarzilli** [comment] 2022-12-05 12:57
Duplicate of #3129, also #3058
You have to build delve from master, or go install ...@latest to debug code compiled with 1.20. Reopen if it still doesn't work.

**Closed by aarzilli** 2022-12-05 12:57 UTC
