### ISSUE TITLE
Partial license

### ISSUE THREAD

**Issue by oz123** [go-delve/delve#1743] opened 2019-11-06 06:09 UTC
Please answer the following before submitting your issue:

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.2.0
Build: $Id: 068e2451004e95d0b042e5257e34f0f08ce01466 $
2. What version of Go are you using? (`go version`)?
go version go1.12.9 linux/amd64

Delve bundles software under more restrictive licenses than the MIT, hence it should
mentioned those in its own LICENSE file. 
See discussion here:

https://bugs.gentoo.org/694382

Thanks for making this wonderful software available.

**Comment by aarzilli** [comment] 2019-11-06 08:26
What would a satisfactory LICENSE file look like? Just list all the other licenses from vendored dependencies there? Or should it also say indicate which license applies to which part? What if we just said "Code inside the vendor directory is covered by different licenses, please see the LICENSE files in the subdirectories of vendor"?

**Comment by oz123** [comment] 2019-11-06 08:30
According to the terms of each license you should put the correct notification in the license. 
For example in if a project is using Apache 2, you have to put the notification in the license. 

See for example how [Django does it](https://github.com/django/django/blob/master/LICENSE.python).

**Comment by aarzilli** [comment] 2019-11-06 12:32
I don't get it, you'll have to explain it to me in simpler words. Broadly speaking we are using sources within four different licenses, MIT, BSD3, BSD2 and Apache-2.0. Of these:

1. MIT isn't a problem
2. I believe that we are complying with BSD2 and BSD3 by including their LICENSE file. It seems to me that this satisfies the "Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer" clause.
3. As for Apache-2.0 it lists four conditions for redistribution:

```
      (a) You must give any other recipients of the Work or
          Derivative Works a copy of this License; and

      (b) You must cause any modified files to carry prominent notices
          stating that You changed the files; and

      (c) You must retain, in the Source form of any Derivative Works
          that You distribute, all copyright, patent, trademark, and
          attribution notices from the Source form of the Work,
          excluding those notices that do not pertain to any part of
          the Derivative Works; and

      (d) If the Work includes a "NOTICE" text file as part of its
          distribution, then any Derivative Works that You distribute must
          include a readable copy of the attribution notices contained
          within such NOTICE file, excluding those notices that do not
          pertain to any part of the Derivative Works, in at least one
          of the following places: within a NOTICE text file distributed
          as part of the Derivative Works; within the Source form or
          documentation, if provided along with the Derivative Works; or,
          within a display generated by the Derivative Works, if and
          wherever such third-party notices normally appear. The contents
          of the NOTICE file are for informational purposes only and
          do not modify the License. You may add Your own attribution
          notices within Derivative Works that You distribute, alongside
          or as an addendum to the NOTICE text from the Work, provided
          that such additional attribution notices cannot be construed
          as modifying the License.
```

I think that we are complying with all four since we do not change any of the files and do not remove either the LICENSE or the NOTICE files.

You give me django as an example and from what I can see they have a LICENSE file for their source and an additional LICENSE.python file, reproducing python's license, for the source they took from python's standard library. 

From what I can see the difference from what we are doing and what they are doing is that they have a file in the root directory and we have them inside subdirectories. Why is that relevant?

**Comment by aarzilli** [comment] 2019-12-04 10:18
Closing, no feedback and downstream bug was closed.

**Closed by aarzilli** 2019-12-04 10:18 UTC
Labels: kind/discussion
