### ISSUE TITLE
Goland Debug Problem: protocol error E09 during set breakpoint for packet

### ISSUE THREAD

**Issue by penguin219** [go-delve/delve#3537] opened 2023-10-24 12:07 UTC
i try to local debug on goland, and breakpoint  wont work show error: protocol error E09 during set breakpoint for packet
here is my related versions, i try some solution other people mentioned before ,did't work for me. help!!!

dlv version:  Delve Debugger Version: 1.21.1
go version: go version go1.18.10 darwin/arm64
system: apple m2

![image](https://github.com/go-delve/delve/assets/26891388/4509d765-cb55-4530-bec9-449402e2c47f)

**Comment by aarzilli** [comment] 2023-10-24 12:29
See #1116

**Comment by penguin219** [comment] 2023-10-24 12:36
> See #1116

still didnt work,i try to add this on goland too ,doesnt help 
![image](https://github.com/go-delve/delve/assets/26891388/9d0db24a-f344-4165-aad5-72babee03d74)

here is some more infos, my go and goland version are both arm64
![image](https://github.com/go-delve/delve/assets/26891388/01822863-7303-4a01-b36d-d5cd55438dc1)

**Comment by aarzilli** [comment] 2023-10-24 13:32
Try setting a breakpoint using the command line interface (dlv) and passing `--log --log-output=rpc` as arguments. Post the output.

**Comment by penguin219** [comment] 2023-10-25 02:52
> Try setting a breakpoint using the command line interface (dlv) and passing `--log --log-output=rpc` as arguments. Post the output.

when i try "dlv debug" i got this output "could not launch process: can not run under Rosetta, check that the installed build of Go is right for your CPU architecture" , but my go version is arm64..

**Comment by aarzilli** [comment] 2023-10-25 14:03
Check the value of GOOS/GOARCH.

**Comment by penguin219** [comment] 2023-10-26 03:55
> Check the value of GOOS/GOARCH.

GOARCH="amd64"
GOOS="darwin"

i try to change GORACH to arm64 then run debug ,i got this output "could not launch process: can not run under Rosetta, check that the installed build of Go is right for your CPU architecture",and when i restart goland  the value of GOARCH change back to amd64 automatically

**Comment by aarzilli** [comment] 2023-10-26 05:11
Because GOARCH was set incorrectly the dlv executable is compiled for the wrong architecture which causes it to run under rosetta. Possibly the entire goland install is for the wrong version of the OS.

**Comment by ExcitingFrog** [comment] 2023-10-26 08:31
you can try to reinstall xcode

**Comment by penguin219** [comment] 2023-10-26 09:13
> Because GOARCH was set incorrectly the dlv executable is compiled for the wrong architecture which causes it to run under rosetta. Possibly the entire goland install is for the wrong version of the OS.

i install this version ,is this wrong version? 
![image](https://github.com/go-delve/delve/assets/26891388/a5608b28-7ae5-42b6-aa91-918d4a21f0d1)

**Comment by penguin219** [comment] 2023-10-26 09:15
actually i try both version but still wont work，ps reinstall i delete those files that contains goland ，am i missing something？

~/Library/Preferences/
~/Library/Caches/
~/Library/Application Support/
~/Library/Logs/

**Comment by aarzilli** [comment] 2023-11-12 07:08
Closing, multiple problems caused by misconfiguration.

**Closed by aarzilli** 2023-11-12 07:08 UTC
Labels: os/macOS, kind/needs more info, arch/arm64
