### ISSUE TITLE
Cannot debug with recover

### ISSUE THREAD

**Issue by nejisama** [go-delve/delve#1759] opened 2019-11-15 10:24 UTC
Please answer the following before submitting your issue:

1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.3.2
Build: $Id: 569ccbd514fc47c8b4c521b142556867ec5e6917 $
```
2. What version of Go are you using? (`go version`)?
```
go version go1.12.7 darwin/amd64
```
3. What operating system and processor architecture are you using?
macos x86
4. What did you do?
use dlv debug with a program which contains a nil point panic and recover
```
go build test.go
dlv exec ./test
```
code:
```
package main

import "fmt"

type A struct {
        Value int 
}

func main() {
        defer func() {
                if r := recover(); r != nil {
                        fmt.Println("ok")
                }   
        }() 
        var a *A
        fmt.Println(a.Value)

}
```
5. What did you expect to see?
the output should be "ok"
6. What did you see instead?
```
Type 'help' for list of commands.
(dlv) c
> main.main() ./test.go:16 (PC: 0x1092f1f)
Warning: debugging optimized function
Command failed: bad access
```

**Comment by aarzilli** [comment] 2019-11-16 07:00
Duplicate of #852

**Closed by aarzilli** 2019-11-16 07:00 UTC
