### ISSUE TITLE
breakpoint not hit and missing stack frames from runtime

### ISSUE THREAD

**Issue by andreimatei** [go-delve/delve#3233] opened 2022-12-30 17:27 UTC
I'm seeing two different behaviors that seem bugs (I don't know if bugs in Delve or faulty debug info); they're both around the same runtime function, so I'm reporting both of them here and I'll let someone else split them in different issues if they are indeed different.

Problem 1: placing a breakpoint by line number in `traceback.go:457` ([this line](https://github.com/golang/go/blob/go1.19.4/src/runtime/traceback.go#L457)) doesn't work. The breakpoint is never hit. The pc at which Delve places the breakpoint is jumped over in some executions. Placing the breakpoint by hand at different pc's associated with the same source line works.

Repro:
Consider the following program:
```
package main

import (
	"net/http"
	_ "net/http/pprof" // For the pprof http handler
)

func main() {
	http.ListenAndServe("localhost:8080", nil)
}
```

Compile it with go 1.19.4 (default gcflags, optimizations enabled), on Linux, and then 
```
$ dlv attach `pidof repro`

(dlv) break traceback.go:457
Breakpoint 1 set at 0x45f260 for runtime.gentraceback() /home/andrei/goroot/src/runtime/traceback.go:457
```
Notice the `0x45f260`. A reference from `objdump --dwarf=decodedline testprog | grep 'traceback.go.'`:
```
traceback.go                                 457            0x45f1d9        
traceback.go                                 453            0x45f1e6               x
traceback.go                                 453            0x45f1eb        
traceback.go                                 453            0x45f200               x
traceback.go                                 453            0x45f205        
traceback.go                                 454            0x45f219               x
traceback.go                                 454            0x45f21e        
traceback.go                                 457            0x45f260               x
traceback.go                                 457            0x45f262        
traceback.go                                 457            0x45f26a               x
traceback.go                                 457            0x45f26f        
traceback.go                                 457            0x45f277               x
traceback.go                                 457            0x45f27c        
```
`0x45f260` is not the first PC associated with line 457, but seems to be the first pc that is marked as `Stmt` (in case that's relevant).
Now exercise the code through the pprof endpoint, for example through:
```
http://localhost:8080/debug/pprof/goroutine?debug=2
```
Our breakpoint is in a helper function around printing the goroutine dump, and it should be hit. However, you'll see that it is not hit.
If we place our breakpoint slightly earlier in this function, we can trace and see how the PC progresses:
```
(dlv) break traceback.go:454
Breakpoint 2 set at 0x45f219 for runtime.gentraceback() /home/andrei/goroot/src/runtime/traceback.go:454
(dlv) c
> runtime.gentraceback() /home/andrei/goroot/src/runtime/traceback.go:454 (hits goroutine(12):1 total:1) (PC: 0x45f219)
si
si
...
```
The PC goes:
```
0x45f219
0x45f21e
0x45f220
0x45f224 -> The instruction here is jnz 0x45f262
0x45f262 -> So we jumped over 0x45f260
0x45f26a  -> This is where an `n` brings me, probably because this instruction is the next one marked as `Stmt`.
```

So, it seems to me that the pc `0x45f260` is the wrong one to put the breakpoint in; some code paths jump over it.

---

Problem 2: Delve seems to not generate a correct backtrace when starting from inside this `runtime.genbacktrace()` function. If you do `bt` from the pc's referenced above, you get the following. Stack frames are missing between the `runtime.gentraceback` and the `runtime.systemstack_switch` frames: there's supposed to be a couple of functions in there.
By poking around with other tools, the stack unwinding debug info seems to exist, and to be correct for the `gentraceback` locations. But don't take my word for it.

```
0  0x000000000045f26a in runtime.gentraceback
    at /home/andrei/goroot/src/runtime/traceback.go:457
 1  0x0000000000469020 in runtime.systemstack_switch
    at /home/andrei/goroot/src/runtime/asm_amd64.s:459
 2  0x00000000004313af in runtime.Stack
    at /home/andrei/goroot/src/runtime/mprof.go:1203
 3  0x0000000000661a90 in runtime/pprof.writeGoroutineStacks
    at /home/andrei/goroot/src/runtime/pprof/pprof.go:692
 4  0x00000000006619cb in runtime/pprof.writeGoroutine
    at /home/andrei/goroot/src/runtime/pprof/pprof.go:681
 5  0x000000000065e94b in runtime/pprof.(*Profile).WriteTo
    at /home/andrei/goroot/src/runtime/pprof/pprof.go:330
 6  0x000000000066db25 in net/http/pprof.handler.ServeHTTP
    at /home/andrei/goroot/src/net/http/pprof/pprof.go:253
...
```

**Comment by aarzilli** [comment] 2022-12-31 09:20
> So, it seems to me that the pc 0x45f260 is the wrong one to put the breakpoint in; some code paths jump over it.

We do, in fact, pick the first instruction marked is_stmt in debug_line. Which means that this is intended behavior for delve and possibly a bug in the compiler. If this problem still happens with go1.20 it could be worth reporting but note that since the code in runtime is always optimized it will have low priority.

> Problem 2: Delve seems to not generate a correct backtrace when starting from inside this runtime.genbacktrace()

When executing a stacktrace starting from g0 inside the runtime delve will always immediately switch to the goroutine stack after a single frame, see https://github.com/go-delve/delve/blob/a6e3d144553682f83b8acd6b9b852378ebfed1a5/pkg/proc/amd64_arch.go#L230 for an explanation. If you want to see the runtime stacktrace you can use `stack -mode simple` which will just use the unwind information.

**Comment by aarzilli** [comment] 2023-01-04 09:31
Closing since this is essentially working as intended / a bug in the compiler.

**Closed by aarzilli** 2023-01-04 09:31 UTC

**Comment by aarzilli** [comment] 2023-01-04 15:58
> What exactly does is_stmt mean?

From DWARF, is_stmt is *A boolean indicating that the current instruction is a recommended breakpoint location. A recommended breakpoint location is intended to "represent" a line, a statement and/or a semantically distinct subpart of a statement.*

> Have you seen other cases like this where breakpoints are placed at a surprising address?

There were a smattering of those when generics were introduced: [#49628](https://github.com/golang/go/issues/49628), see also: https://github.com/golang/go/issues?q=is%3Aissue+debug_line+author%3Aaarzilli and https://github.com/golang/go/issues?q=is%3Aissue+pcln+author%3Aaarzilli+
