### ISSUE TITLE
Constant "Unable to step while the previous step is interrupted by a breakpoint." errors

### ISSUE THREAD

**Issue by txgruppi** [go-delve/delve#3859] opened 2024-11-13 15:26 UTC
1. What version of Delve are you using (`dlv version`)? 1.23.1
2. What version of Go are you using? (`go version`)? 1.23.3
3. What operating system and processor architecture are you using? Linux x86_64
4. What did you do? I opened VSCode to work on a project I work for years. There were a couple months I didn't work on this project. So I updated Go and the tools via VSCode's "Go: Install/Update Tools".
5. What did you expect to see? A normal interactive debugging session.
6. What did you see instead? Not the error `Unable to step while the previous step is interrupted by a breakpoint. Use 'Continue' to resume the original step command.`.

I'm constantly getting the error `Unable to step while the previous step is interrupted by a breakpoint. Use 'Continue' to resume the original step command.`.
I can't see to figure out a pattern for it and I'm not sure what changed in Go or Delve, but this is happening so often that it is hard to debug the code I'm working on.

Anyone with the same issue?
Is there something I should update in environment?

**Comment by aarzilli** [comment] 2024-11-13 15:43
Closing, working as intended. You used the step command and the debugger stopped on a breakpoint on a different goroutine before the step command could complete.

**Closed by aarzilli** 2024-11-13 15:43 UTC

**Comment by aarzilli** [comment] 2024-11-13 16:11
> the closer I can have to other goroutine running are defer functions.

No, defers do not run in a different goroutine.

> Another thing, this wasn't the behavior a couple months ago

This has been the behavior since november of 2015.

**Comment by txgruppi** [comment] 2024-11-13 17:12
@aarzilli 

> > Another thing, this wasn't the behavior a couple months ago
> 
> This has been the behavior since november of 2015.

Interesting. I've been using Go and the interactive debugger in VSCode for years. Just with this project I have 4 years and 8 months of Go and delve.

This is the very first time I see this message. I understand it is there in the code for a while, but it may be good to keep an eye open for an increase occurrence of this error. I'm having to create a breakpoint for each line of code because of this error, otherwise the code just continues beyond the place where I asked for a step.

**Comment by aarzilli** [comment] 2024-11-13 17:45
You should enable the logs for DAP and post them if it happens again. Another possibility is that you have a watch expression that executes a function call that hits a breakpoint.

**Comment by txgruppi** [comment] 2024-11-14 15:50
I'm still looking into it. It may be caused by Echo (https://echo.labstack.com/) starting a goroutine for the request.
I still think it is weird because all the processing happens in one goroutine, but I can see some repeated log lines.
Something is going on.
