### ISSUE TITLE
Out of memory error on attempt to evaluate function call

### ISSUE THREAD

**Issue by nd** [go-delve/delve#1791] opened 2019-12-09 13:50 UTC
1. What version of Delve are you using (`dlv version`)?

```
Delve Debugger
Version: 1.3.2
Build: 3c266810757cd4abafe46fc6c9203aeeef5e15bf
```

2. What version of Go are you using? (`go version`)?

```
go version go1.13.4 linux/amd64
```

3. What operating system and processor architecture are you using?

linux/amd64

4. What did you do?

Debug the following program with breakpoint on the line 13:

```
package main

import (
	"fmt"
	"os"
)

func deleteAll(dir string) {
	fmt.Printf("Deleting %s\n", dir)
}

func main() {
	dir := "/" // break
	if len(os.Args) > 1 {
		dir = os.Args[1]
	}
	deleteAll(dir)
}
```

Once the breakpoint is reached, evaluated the `deleteAll(dir)` call.

5. What did you expect to see?

Some error since evaluation is not possible.

6. What did you see instead?

Crash with out of memory error:

```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x4e8228, 0x16)
	/home/nd/go/go1.13.4/src/runtime/panic.go:774 +0x72
runtime.sysMap(0xc004000000, 0xc004000000, 0x5a0a38)
	/home/nd/go/go1.13.4/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x589360, 0xc004000000, 0x18000124000, 0x5849d0)
	/home/nd/go/go1.13.4/src/runtime/malloc.go:701 +0x510
runtime.(*mheap).grow(0x589360, 0x6000045, 0x7fffffffffff)
	/home/nd/go/go1.13.4/src/runtime/mheap.go:1255 +0xaf
runtime.(*mheap).allocSpanLocked(0x589360, 0x6000045, 0x5a0a48, 0xffffffff00000380)
	/home/nd/go/go1.13.4/src/runtime/mheap.go:1170 +0x256
runtime.(*mheap).alloc_m(0x589360, 0x6000045, 0x70101, 0x1)
	/home/nd/go/go1.13.4/src/runtime/mheap.go:1022 +0xc2
runtime.(*mheap).alloc.func1()
	/home/nd/go/go1.13.4/src/runtime/mheap.go:1093 +0x4c
runtime.(*mheap).alloc(0x589360, 0x6000045, 0x101, 0x0)
	/home/nd/go/go1.13.4/src/runtime/mheap.go:1092 +0x8a
runtime.largeAlloc(0xc00008a000, 0x100, 0x0)
	/home/nd/go/go1.13.4/src/runtime/malloc.go:1138 +0xa9
runtime.mallocgc.func1()
	/home/nd/go/go1.13.4/src/runtime/malloc.go:1033 +0x46
runtime.systemstack(0x0)
	/home/nd/go/go1.13.4/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	/home/nd/go/go1.13.4/src/runtime/proc.go:1146

goroutine 1 [running]:
runtime.systemstack_switch()
	/home/nd/go/go1.13.4/src/runtime/asm_amd64.s:330 fp=0xc000053668 sp=0xc000053660 pc=0x458c80
runtime.mallocgc(0xc00008a000, 0x0, 0xc000090800, 0xc000090940)
	/home/nd/go/go1.13.4/src/runtime/malloc.go:1032 +0x719 fp=0xc000053710 sp=0xc000053668 pc=0x40c309
runtime.growslice(0x4bf520, 0xc0000160e0, 0x9, 0x10, 0xc000088061, 0xc000090938, 0xc000090868, 0xc000090bc8)
	/home/nd/go/go1.13.4/src/runtime/slice.go:175 +0x148 fp=0xc000053778 sp=0xc000053710 pc=0x442aa8
fmt.(*buffer).writeString(0xc00008ca90, 0xc00007c000, 0xc000088058)
	/home/nd/go/go1.13.4/src/fmt/print.go:82 +0xb9 fp=0xc000053810 sp=0xc000053778 pc=0x4a3a09
fmt.(*fmt).padString(0xc00008cad0, 0xc00007c000, 0xc000088058)
	/home/nd/go/go1.13.4/src/fmt/format.go:110 +0x86 fp=0xc000053868 sp=0xc000053810 pc=0x4a04d6
fmt.(*fmt).fmtS(0xc00008cad0, 0xc00007c000, 0xc000088058)
	/home/nd/go/go1.13.4/src/fmt/format.go:359 +0x6b fp=0xc0000538a0 sp=0xc000053868 pc=0x4a191b
fmt.(*pp).fmtString(0xc00008ca90, 0xc00007c000, 0xc000088058, 0x7f0c00000073)
	/home/nd/go/go1.13.4/src/fmt/print.go:450 +0x123 fp=0xc000053910 sp=0xc0000538a0 pc=0x4a5933
fmt.(*pp).printArg(0xc00008ca90, 0x4bf3e0, 0xc000010200, 0xc000000073)
	/home/nd/go/go1.13.4/src/fmt/print.go:698 +0xea6 fp=0xc000053a80 sp=0xc000053910 pc=0x4a8046
fmt.(*pp).doPrintf(0xc00008ca90, 0x4e659b, 0xc, 0xc000053da8, 0x1, 0x1)
	/home/nd/go/go1.13.4/src/fmt/print.go:1030 +0x726 fp=0xc000053c48 sp=0xc000053a80 pc=0x4ab1a6
fmt.Fprintf(0x4f4b40, 0xc00000e018, 0x4e659b, 0xc, 0xc000053da8, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/nd/go/go1.13.4/src/fmt/print.go:204 +0x90 fp=0xc000053cc8 sp=0xc000053c48 pc=0x4a43c0
fmt.Printf(0x4e659b, 0xc, 0xc000053da8, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/nd/go/go1.13.4/src/fmt/print.go:213 +0xab fp=0xc000053d58 sp=0xc000053cc8 pc=0x4a452b
main.deleteAll(0xc00007c000, 0xc000088058)
	/home/nd/go/src/github.com/nd/hoverDebug/main.go:9 +0xc3 fp=0xc000053de0 sp=0xc000053d58 pc=0x4ac083
debugCall32()
	/home/nd/go/go1.13.4/src/runtime/asm_amd64.s:1630 +0x28 fp=0xc000053e10 sp=0xc000053de0 pc=0x45af98
runtime.debugCallWrap(0x45af70)
	/home/nd/go/go1.13.4/src/runtime/debugcall.go:112 +0x94 fp=0xc000053e80 sp=0xc000053e10 pc=0x4066e4
runtime.debugCallV1()
	/home/nd/go/go1.13.4/src/runtime/asm_amd64.s:1571 +0xc9 fp=0xc000053f28 sp=0xc000053e80 pc=0x45ada9
main.main()
	/home/nd/go/src/github.com/nd/hoverDebug/main.go:12 +0x21 fp=0xc000053f60 sp=0xc000053f28 pc=0x4ac0c1
runtime.main()
	/home/nd/go/go1.13.4/src/runtime/proc.go:203 +0x1d4 fp=0xc000053fe0 sp=0xc000053f60 pc=0x42f924
runtime.goexit()
	/home/nd/go/go1.13.4/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000053fe8 sp=0xc000053fe0 pc=0x45abd1
```

Rpc log: https://gist.github.com/nd/b76424ab39530eae01917a6615cac526.

Originally from https://youtrack.jetbrains.com/issue/GO-8563.

**Comment by rillig** [comment] 2019-12-09 15:58
See also #1134 for the underlying problem.

**Comment by aarzilli** [comment] 2019-12-10 09:25
Duplicate of  #1134

**Closed by aarzilli** 2019-12-10 09:25 UTC
