### ISSUE TITLE
Getting: Command failed: protocol error E09 during set breakpoint for packet when trying to set break point

### ISSUE THREAD

**Issue by kkrime** [go-delve/delve#2936] opened 2022-03-19 03:04 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.8.2
3. What version of Go are you using? (`go version`)?
go version go1.18 darwin/amd64
5. What operating system and processor architecture are you using?
OSX M1
7. What did you do?
I opened dlv and tried to add a break point
9. What did you expect to see?
a message saying break point added
11. What did you see instead?
Command failed: protocol error E09 during set breakpoint for packet $Z0,7ff700d9e06f,4

**Comment by aarzilli** [comment] 2022-03-19 06:20
Duplicate of #1116. All the people in that thread had some problem with their local setup. Closing, this is likely not a bug in delve.

**Closed by aarzilli** 2022-03-19 06:20 UTC
