### ISSUE TITLE
Debugger hangs waiting for process state change on wsl1

### ISSUE THREAD

**Issue by nd** [go-delve/delve#3124] opened 2022-08-25 15:44 UTC
1. What version of Delve are you using (`dlv version`)?

Delve built on revision e2ec3eb6339709c4c56b28978d8b1b5bf79f46f0

2. What version of Go are you using? (`go version`)?

go version go1.19 linux/amd64

3. What operating system and processor architecture are you using?

WSL1 on windows 10

4. What did you do?

Tried to debug hello world on WSL1. It looks like delve is hanging in this loop https://github.com/go-delve/delve/blob/e2ec3eb6339709c4c56b28978d8b1b5bf79f46f0/pkg/proc/native/proc_linux.go#L495 because sys.Wait4 always return 0.

I've also noticed that reading status fails as well, because when `status` is called in the loop dpb.os.comm is not yet initialized, so scanf pattern looks for `%d ()  %c`. BTW in Ubuntu 20.04 LTS in WSL1 there is only one space after closing parenthesis, not two.

**Comment by aarzilli** [comment] 2022-08-25 17:40
Closing, duplicate of #1235. Someone would have to port delve to WSL1 but:

- Go does not officially support WSL1
- There are no build tags to distinguish WSL1 from normal linux
- arguably any discrepancy between linux behavior and WSL1 behavior is a WSL1 bug
- my impression is that WSL1 is on life support and not worth spending time on

**Closed** 2022-08-25 17:40 UTC
