### ISSUE TITLE
could not launch process: fork/exec /xxxx/__debug_bin: function not implemented

### ISSUE THREAD

**Issue by keqingyuan** [go-delve/delve#3097] opened 2022-08-09 03:57 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.
```
LaunchRequest
Using GOPATH: /go
Using GOROOT: /usr/local/go
Using PATH: /vscode/vscode-server/bin/linux-x64/3b889b090b5ad5793f524b5d1d39fda662b96a2a/bin/remote-cli:/usr/local/go/bin:/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Current working directory: /workspaces/mosn
Running: /go/bin/dlv exec /workspaces/mosn/__debug_bin --headless=true --listen=127.0.0.1:41488 --api-version=2 --log=true --log-output=debugger -- start -c /workspaces/mosn/configs/mosn_config.json
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stdout","output":"API server listening at: 127.0.0.1:41488\n"}}
API server listening at: 127.0.0.1:41488
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-08-09T13:42:09+08:00 info layer=debugger launching process with args: [/workspaces/mosn/__debug_bin start -c /workspaces/mosn/configs/mosn_config.json]\n"}}
2022-08-09T13:42:09+08:00 info layer=debugger launching process with args: [/workspaces/mosn/__debug_bin start -c /workspaces/mosn/configs/mosn_config.json]
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"could not launch process: fork/exec /workspaces/mosn/__debug_bin: function not implemented\n"}}
could not launch process: fork/exec /workspaces/mosn/__debug_bin: function not implemented
Process exiting with code: 1
To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":false,"message":"Failed to continue: Check the debug console for details.","body":{"error":{"id":3000,"format":"Failed to continue: Check the debug console for details.","showUser":true}}}
```
cat /tmp/vscode-go-debug.txt
```
2022-8-9, 05:42:08.794 UTC
[05:42:08.795 UTC] From client: initialize({"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"go","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"zh-cn","supportsProgressReporting":true,"supportsInvalidatedEvent":true,"supportsMemoryReferences":true})
[05:42:08.796 UTC] InitializeRequest
[05:42:08.796 UTC] To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConditionalBreakpoints":true,"supportsConfigurationDoneRequest":true,"supportsSetVariable":true}}
[05:42:08.797 UTC] InitializeResponse
[05:42:08.799 UTC] From client: launch({"name":"Launch executable","type":"go","request":"launch","mode":"exec","trace":"verbose","showLog":true,"debugAdapter":"legacy","program":"/workspaces/mosn/__debug_bin","args":["start","-c","/workspaces/mosn/configs/mosn_config.json"],"preLaunchTask":"go: build (debug)","__configurationTarget":5,"packagePathToGoModPathMap":{},"showRegisters":false,"showGlobalVariables":false,"substitutePath":[],"logOutput":"debugger","dlvFlags":[],"hideSystemGoroutines":false,"dlvLoadConfig":{"followPointers":true,"maxVariableRecurse":1,"maxStringLen":64,"maxArrayValues":64,"maxStructFields":-1},"dlvToolPath":"/go/bin/dlv","env":{"BROWSER":"/vscode/vscode-server/bin/linux-x64/3b889b090b5ad5793f524b5d1d39fda662b96a2a/bin/helpers/browser.sh","REMOTE_CONTAINERS":"true","SSH_AUTH_SOCK":"/tmp/vscode-ssh-auth-66b47f369c8e928eff24d4dfe0f939260b45f831.sock","REMOTE_CONTAINERS_SOCKETS":"[\"/tmp/vscode-ssh-auth-66b47f369c8e928eff24d4dfe0f939260b45f831.sock\"]","REMOTE_CONTAINERS_IPC":"/tmp/vscode-remote-containers-ipc-66b47f369c8e928eff24d4dfe0f939260b45f831.sock","VSCODE_NLS_CONFIG":"{\"locale\":\"zh-cn\",\"availableLanguages\":{\"*\":\"zh-cn\"},\"_languagePackId\":\"1d735750dbb1b9066c7513078396ba0f.zh-cn\",\"_translationsConfigFile\":\"/home/code/.vscode-server/data/clp/1d735750dbb1b9066c7513078396ba0f.zh-cn/tcf.json\",\"_cacheRoot\":\"/home/code/.vscode-server/data/clp/1d735750dbb1b9066c7513078396ba0f.zh-cn\",\"_resolvedLanguagePackCoreLocation\":\"/home/code/.vscode-server/data/clp/1d735750dbb1b9066c7513078396ba0f.zh-cn/3b889b090b5ad5793f524b5d1d39fda662b96a2a\",\"_corruptedFile\":\"/home/code/.vscode-server/data/clp/1d735750dbb1b9066c7513078396ba0f.zh-cn/corrupted.info\",\"_languagePackSupport\":true}","VSCODE_HANDLES_UNCAUGHT_ERRORS":"true","VSCODE_AMD_ENTRYPOINT":"vs/workbench/api/node/extensionHostProcess","VSCODE_HANDLES_SIGPIPE":"true","DOCKER_BUILDKIT":"1","USER":"code","HOSTNAME":"docker-desktop","HOME":"/home/code","PATH":"/vscode/vscode-server/bin/linux-x64/3b889b090b5ad5793f524b5d1d39fda662b96a2a/bin/remote-cli:/usr/local/go/bin:/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","VSCODE_AGENT_FOLDER":"/home/code/.vscode-server","GOPATH":"/go","SHELL":"/bin/sh","PWD":"/vscode/vscode-server/bin/linux-x64/3b889b090b5ad5793f524b5d1d39fda662b96a2a","VSCODE_CWD":"/vscode/vscode-server/bin/linux-x64/3b889b090b5ad5793f524b5d1d39fda662b96a2a","ELECTRON_RUN_AS_NODE":"1","VSCODE_IPC_HOOK_CLI":"/tmp/vscode-ipc-793f4596-c5d0-4d15-9ab9-db9d941a8104.sock","GOMODCACHE":"/go/pkg/mod","GOPROXY":"https://goproxy.cn,direct"},"__sessionId":"884e2724-5689-405a-b5ab-3555fbf1ae3e"})
[05:42:08.800 UTC] LaunchRequest
[05:42:08.892 UTC] Using GOPATH: /go
[05:42:08.894 UTC] Using GOROOT: /usr/local/go
[05:42:08.896 UTC] Using PATH: /vscode/vscode-server/bin/linux-x64/3b889b090b5ad5793f524b5d1d39fda662b96a2a/bin/remote-cli:/usr/local/go/bin:/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[05:42:08.899 UTC] Current working directory: /workspaces/mosn
[05:42:08.899 UTC] Running: /go/bin/dlv exec /workspaces/mosn/__debug_bin --headless=true --listen=127.0.0.1:41488 --api-version=2 --log=true --log-output=debugger -- start -c /workspaces/mosn/configs/mosn_config.json
[05:42:09.096 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"stdout","output":"API server listening at: 127.0.0.1:41488\n"}}
[05:42:09.104 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-08-09T13:42:09+08:00 info layer=debugger launching process with args: [/workspaces/mosn/__debug_bin start -c /workspaces/mosn/configs/mosn_config.json]\n"}}
[05:42:09.114 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"could not launch process: fork/exec /workspaces/mosn/__debug_bin: function not implemented\n"}}
[05:42:09.121 UTC] [Error] Process exiting with code: 1
[05:42:09.125 UTC] To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":false,"message":"Failed to continue: Check the debug console for details.","body":{"error":{"id":3000,"format":"Failed to continue: Check the debug console for details.","showUser":true}}}
[05:42:09.127 UTC] Sending TerminatedEvent as delve is closed
[05:42:09.130 UTC] To client: {"seq":0,"type":"event","event":"terminated"}
[05:42:09.202 UTC] From client: disconnect({"restart":false})
[05:42:09.208 UTC] DisconnectRequest
[05:42:09.210 UTC] Closing Delve.
[05:42:09.213 UTC] HaltRequest
[05:42:09.325 UTC] To client: {"seq":24,"type":"response","request_seq":2,"command":"launch","success":false,"message":"Failed to continue: \"{e}\"","body":{"error":{"id":3000,"format":"Failed to continue: \"{e}\"","variables":{"e":"Error: connect ECONNREFUSED 127.0.0.1:41488"},"showUser":true}}}
[05:42:09.326 UTC] ContinueResponse
[05:42:09.328 UTC] HaltResponse
[05:42:09.330 UTC] Failed to halt - Error: connect ECONNREFUSED 127.0.0.1:41488
[05:42:09.331 UTC] DetachRequest
[05:42:09.331 UTC] DetachResponse
[05:42:09.332 UTC] [Error] Failed to detach - Error: connect ECONNREFUSED 127.0.0.1:41488
[05:42:09.332 UTC] killing debugee (pid: 1299)...
[05:42:09.336 UTC] [Error] Socket connection to remote was closed
[05:42:09.337 UTC] To client: {"seq":24,"type":"response","request_seq":2,"command":"launch","success":false,"message":"Failed to continue: Check the debug console for details.","body":{"error":{"id":3000,"format":"Failed to continue: Check the debug console for details.","showUser":true}}}
[05:42:09.337 UTC] Sending TerminatedEvent as delve is closed
[05:42:09.338 UTC] To client: {"seq":0,"type":"event","event":"terminated"}
[05:42:09.343 UTC] DisconnectRequest to parent to shut down protocol server.
[05:42:09.344 UTC] To client: {"seq":0,"type":"response","request_seq":3,"command":"disconnect","success":true}
[05:42:09.344 UTC] DisconnectResponse
```

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)? 
Delve Debugger
Version: 1.9.0
Build: $Id: 69310c2f438e492f892d6af22e8e62c8ea1e9d8d

2. What version of Go are you using? (`go version`)?
go version go1.18.5 linux/amd64

3. What operating system and processor architecture are you using?
debug env: dev container(linux/amd64) , dockerfile is :
```
ARG GO_VERSION=1.18
##
## Base
##

FROM docker.io/debian:stable-slim as base
RUN apt update && apt upgrade -y --autoremove \
    && apt install -y \
        curl \
        file \
        git \
        jo \
        jq \
        time \
        unzip \
        xz-utils \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
COPY bin/scurl /usr/local/bin/scurl

FROM base as just
ARG JUST_VERSION=1.2.0
RUN url="https://github.com/casey/just/releases/download/${JUST_VERSION}/just-${JUST_VERSION}-x86_64-unknown-linux-musl.tar.gz" ; \
    scurl "$url" | tar zvxf - -C /usr/local/bin just

FROM base as yq
ARG YQ_VERSION=v4.25.1
RUN url="https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64" ; \
    scurl -o /usr/local/bin/yq "$url" && chmod +x /usr/local/bin/yq

##
## Go image
##

FROM docker.io/golang:${GO_VERSION} as go
ENV GOPROXY="https://goproxy.cn"
RUN apt update && apt upgrade -y --autoremove \
    && apt install -y \
        curl \
        file \
        jq \
        time \
        unzip \
        xz-utils \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN for p in \
    github.com/cweill/gotests/gotests@latest \
    github.com/go-delve/delve/cmd/dlv@latest \
    github.com/golangci/golangci-lint/cmd/golangci-lint@v1.46.2 \
    github.com/fatih/gomodifytags@latest \
    github.com/haya14busa/goplay/cmd/goplay@latest \
    github.com/josharian/impl@latest \
    github.com/ramya-rao-a/go-outline@latest \
    github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest \
    golang.org/x/tools/gopls@latest \
    gotest.tools/gotestsum@v0.4.2 \
    ; do go install -mod=readonly "$p" ; done \
    && rm -rf /go/pkg/* /go/src/*
COPY bin/scurl /usr/local/bin/scurl
COPY --from=just /usr/local/bin/just /usr/local/bin/

##
## Other tools
##

FROM base as checksec
ARG CHECKSEC_VERSION=2.5.0
RUN url="https://raw.githubusercontent.com/slimm609/checksec.sh/${CHECKSEC_VERSION}/checksec" ; \
    scurl -o /usr/local/bin/checksec "$url" && chmod 755 /usr/local/bin/checksec

FROM base as shellcheck
ARG SHELLCHECK_VERSION=v0.8.0
RUN url="https://github.com/koalaman/shellcheck/releases/download/${SHELLCHECK_VERSION}/shellcheck-${SHELLCHECK_VERSION}.linux.x86_64.tar.xz" ; \
    scurl "$url" | tar xJvf - --strip-components=1 -C /usr/local/bin "shellcheck-${SHELLCHECK_VERSION}/shellcheck"

FROM shellcheck as actionlint
ARG ACTIONLINT_VERSION=v1.6.15
RUN url="https://github.com/rhysd/actionlint/releases/download/${ACTIONLINT_VERSION}/actionlint_${ACTIONLINT_VERSION#v}_linux_amd64.tar.gz" ; \
    scurl "$url" | tar xzvf - -C /usr/local/bin actionlint

##
## Tools: Everything needed for a development environment, minus non-root settings.
##

FROM base as tools
COPY --from=actionlint /usr/local/bin/actionlint /usr/local/bin/
COPY --from=checksec /usr/local/bin/checksec /usr/local/bin/che
COPY --from=just /usr/local/bin/just /usr/local/bin/
COPY --from=shellcheck /usr/local/bin/shellcheck /usr/local/bin/
COPY --from=yq /usr/local/bin/yq /usr/local/bin/

##
## Runtime
##

FROM docker.io/debian:stable as runtime
RUN apt update && apt upgrade -y --autoremove \
    && apt install -y \
        clang curl \
        cmake \
        file \
        jo \
        jq \
        libssl-dev \
        locales \
        lsb-release \
        npm \
        pkg-config \
        sudo \
        time \
        unzip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN sed -i 's/^# *\(zh_CN.UTF-8\)/\1/' /etc/locale.gen && locale-gen
RUN (echo "LC_ALL=zh_CN.UTF-8" \
    && echo "LANGUAGE=zh_CN.UTF-8") >/etc/default/locale \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ARG MARKDOWNLINT_VERSION=0.4.0
RUN npm install "markdownlint-cli2@${MARKDOWNLINT_VERSION}" --global

ENV GOPATH=/go
COPY --from=go /go/bin $GOPATH/bin
COPY --from=go /usr/local/go /usr/local/go
RUN chmod 777 /go
ENV PATH=/usr/local/go/bin:$GOPATH/bin:$PATH

COPY --from=tools /usr/local/bin/* /usr/local/bin/

ENV DOCKER_BUILDKIT=1
RUN groupadd --gid=1000 code \
    && useradd --create-home --uid=1000 --gid=1000 code \
    && echo "code ALL=(root) NOPASSWD:ALL" >/etc/sudoers.d/code \
    && chmod 0440 /etc/sudoers.d/code \
    && scurl https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/docker-debian.sh | bash -s \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV USER=code
ENV HOME=/home/code
USER code

ENTRYPOINT ["/usr/local/share/docker-init.sh"]
CMD ["sleep", "infinity"]
```

IDE :vscoe
Host: macOS Monterey 12.5, Apple M2

4. What did you do?
debug in dev container(linux/amd64)

5. What did you expect to see?
debug in dev container(linux/amd64) that host is M2 chip

6. What did you see instead?
```
could not launch process: fork/exec /workspaces/mosn/__debug_bin: function not implemented
Process exiting with code: 1
```
/workspaces/mosn/__debug_bin Binary with go build -c -gcflags='all=-N -l'

**Comment by aarzilli** [comment] 2022-08-09 06:05
Closing, duplicate of #2910

**Closed by aarzilli** 2022-08-09 06:05 UTC
