### ISSUE TITLE
nil exception from fmt package when running delve 

### ISSUE THREAD

**Issue by baturozgur** [go-delve/delve#2166] opened 2020-09-08 11:27 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Version: 1.5.0
Build: $Id: ca5318932770ca063fc9885b4764c30bfaf8a199 $
2. What version of Go are you using? (`go version`)?
go version go1.15.1 darwin/amd64
3. What operating system and processor architecture are you using?
MacOSX Catalina 10.15.6 amd64
4. What did you do?
```
$ cat go/src/local/main.go
package main

import (
        "fmt"
        "regexp"
)

func main() {
        var r *regexp.Regexp
        s := fmt.Sprintf("regex:%v", r)
        fmt.Println(s)
}

$ go run go/src/local/main.go
regex:<nil>

$ dlv debug go/src/local/main.go
Type 'help' for list of commands.
(dlv) continue
> regexp.(*Regexp).String() /usr/local/go/src/regexp/regexp.go:106 (PC: 0x10d718d)
Command failed: bad access
(dlv) stack
0  0x00000000010d718d in regexp.(*Regexp).String
   at /usr/local/go/src/regexp/regexp.go:106
1  0x00000000010ce362 in fmt.(*pp).handleMethods
   at /usr/local/go/src/fmt/print.go:630
2  0x00000000010ce77e in fmt.(*pp).printArg
   at /usr/local/go/src/fmt/print.go:713
3  0x00000000010d2434 in fmt.(*pp).doPrintf
   at /usr/local/go/src/fmt/print.go:1030
4  0x00000000010cb3fe in fmt.Sprintf
   at /usr/local/go/src/fmt/print.go:219
5  0x00000000010d7387 in main.main
   at ./go/src/local/main.go:10
6  0x000000000103aacf in runtime.main
   at /usr/local/go/src/runtime/proc.go:204
7  0x000000000106d021 in runtime.goexit
```

5. What did you expect to see?
"go run" and "delve debug" should behave same for main.go above. 
 
6. What did you see instead?
Nil exception inexplicably occurs when running with dlv.

**Comment by aarzilli** [comment] 2020-09-08 11:32
This is a duplicate of #852, fmt recovers form a SIGSEGV when printing nil pointers but we can't propagate exceptions back to the target on macOS.

**Closed by aarzilli** 2020-09-08 11:32 UTC
