### ISSUE TITLE
sometimes failed to run goroutines in euleros arm64 container

### ISSUE THREAD

**Issue by tom-shan** [go-delve/delve#1812] opened 2020-01-07 03:00 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

**It should be noted that this issue happens occasionally**.

1. What version of Delve are you using (`dlv version`)?
1.3.2
2. What version of Go are you using? (`go version`)?
go1.13.5 linux/arm64
3. What operating system and processor architecture are you using?
EulerOS which is based on centos https://en.wikipedia.org/wiki/EulerOS
arm64
docker container
4. What did you do?

-  create file: main.go

```
cat << 'EOF' > main.go
package main

import "fmt"

func main() {
        fmt.Println("Hello World!")
}
EOF
```
- `dlv debug --headless=true --listen=127.0.0.1:7184 --api-version=2`
- `dlv connect 127.0.0.1:7184`
- set break point in line 6 of main.go
- `continue`
- `goroutines`
5. What did you expect to see?
```
(dlv) grs
* Goroutine 1 - User: ./main.go:6 main.main (0xaecac) (thread 13864)
  Goroutine 2 - User: /root/go/src/runtime/proc.go:305 runtime.gopark (0x3d6d8)
  Goroutine 3 - User: /root/go/src/runtime/proc.go:305 runtime.gopark (0x3d6d8)
  Goroutine 17 - User: /root/go/src/runtime/proc.go:305 runtime.gopark (0x3d6d8)
  Goroutine 18 - User: /root/go/src/runtime/proc.go:305 runtime.gopark (0x3d6d8)
```
6. What did you see instead?
```
(dlv) grs
Command failed: Internal debugger error: runtime error: invalid memory address or nil pointer dereference
runtime.gopanic (0x3ddcb)
        /root/go/src/runtime/panic.go:679
runtime.panicmem (0x536ff)
        /root/go/src/runtime/panic.go:199
runtime.sigpanic (0x53550)
        /root/go/src/runtime/signal_unix.go:394
github.com/go-delve/delve/pkg/dwarf/op.(*DwarfRegisters).Reg (0x2bc3cb)
        /root/gotools/src/github.com/go-delve/delve/pkg/dwarf/op/regs.go:53
github.com/go-delve/delve/pkg/proc.(*stackIterator).advanceRegs (0x2bbfb7)
        /root/gotools/src/github.com/go-delve/delve/pkg/proc/stack.go:567
github.com/go-delve/delve/pkg/proc.(*stackIterator).Next (0x2ba1cb)
        /root/gotools/src/github.com/go-delve/delve/pkg/proc/stack.go:245
github.com/go-delve/delve/pkg/proc.(*G).UserCurrent (0x2c5697)
        /root/gotools/src/github.com/go-delve/delve/pkg/proc/variables.go:236
github.com/go-delve/delve/service/api.ConvertGoroutine (0x2d6dbb)
        /root/gotools/src/github.com/go-delve/delve/service/api/conversions.go:262
github.com/go-delve/delve/service/debugger.(*Debugger).Goroutines (0x32366b)
        /root/gotools/src/github.com/go-delve/delve/service/debugger/debugger.go:1048
github.com/go-delve/delve/service/rpc2.(*RPCServer).ListGoroutines (0x4f4a33)
        /root/gotools/src/github.com/go-delve/delve/service/rpc2/server.go:549
reflect.Value.call (0xc5bcb)
        /root/go/src/reflect/value.go:460
reflect.Value.Call (0xc553b)
        /root/go/src/reflect/value.go:321
github.com/go-delve/delve/service/rpccommon.(*ServerImpl).serveJSONCodec.func2 (0x52c023)
        /root/gotools/src/github.com/go-delve/delve/service/rpccommon/server.go:324
github.com/go-delve/delve/service/rpccommon.(*ServerImpl).serveJSONCodec (0x52a9ab)
        /root/gotools/src/github.com/go-delve/delve/service/rpccommon/server.go:326
runtime.goexit (0x6aa3b)
        /root/go/src/runtime/asm_arm64.s:1128
```

**Comment by xieyuanhuata** [comment] 2020-01-07 03:24
This problem also bothers me！

**Comment by aarzilli** [comment] 2020-01-07 07:49
Duplicate of #1770

**Closed by aarzilli** 2020-01-07 07:49 UTC
