### ISSUE TITLE
debugger fails with could not launch process: stub exited while waiting for connection: exit status 0 on M1 Pro

### ISSUE THREAD

**Issue by thidasapankaja** [go-delve/delve#3059] opened 2022-07-10 06:08 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.9.0
Build: $Id: 69310c2f438e492f892d6af22e8e62c8ea1e9d8d $
```

2. What version of Go are you using? (`go version`)?
`go version go1.18.3 darwin/arm64
`
3. What operating system and processor architecture are you using?
```
MacBook Pro (14-inch, 2021)
Apple M1 Pro
```

4. What did you do?
```
package main

import "fmt"

func main() {
	fmt.Println("Hello, World")
}
```

5. What did you expect to see?

run the dlv without any error

6. What did you see instead?

`could not launch process: stub exited while waiting for connection: exit status 0
`

![Screenshot 2022-07-10 at 11 34 44](https://user-images.githubusercontent.com/7170183/178133400-e3a68440-2b1a-4e89-8beb-09f0eb77419a.png)

Already followed the [installation guide](https://github.com/go-delve/delve/tree/master/Documentation/installation) and already had xcode-select installed, enabled Developer Mode and added the user to the Developer Group

**Comment by aarzilli** [comment] 2022-07-10 07:53
This is almost certainly a problem with your computer. You can confirm it by locating the executable of debugserver (it should be `/Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver`) and running it manually on an executable file: `path_to_debugserver 127.0.0.1:31337 path_to_some_executable`.
It will fail instead of waiting for a connection.

**Comment by thidasapankaja** [comment] 2022-07-10 15:50
It returns this

```
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1316.0.9.46
 for x86_64 (running under translation).
Usage:
  debugserver host:port [program-name program-arg1 program-arg2 ...]
  debugserver /path/file [program-name program-arg1 program-arg2 ...]
  debugserver host:port --attach=<pid>
  debugserver /path/file --attach=<pid>
  debugserver host:port --attach=<process_name>
  debugserver /path/file --attach=<process_name>

```

**Comment by aarzilli** [comment] 2022-07-10 15:54
You didn't call it correctly, please see my message or the usage message it's printing.

**Comment by thidasapankaja** [comment] 2022-07-10 16:03
I ran it from the path of main.go
`sudo /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver 127.0.0.1:31337 .`

and getting this error

```
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1316.0.9.46
 for x86_64 (running under translation).
error: failed to launch process /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver: Permission denied
Exiting.
```

I already added user to the Developer group following this command

`sudo dscl . append /Groups/_developer GroupMembership $(whoami)`

**Comment by aarzilli** [comment] 2022-07-10 16:06
The second argument needs to be the path to an executable, even better if it's a go executable you built to rule out the case were the problem is with permissions. Also no sudo.

**Comment by thidasapankaja** [comment] 2022-07-10 16:18
Getting the same error running this
`/Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver 127.0.0.1:31337 main.go`
![Screenshot 2022-07-10 at 21 46 15](https://user-images.githubusercontent.com/7170183/178152986-639d246c-e9c1-41c6-bb67-bc0510bb4d7f.png)

**Comment by aarzilli** [comment] 2022-07-10 16:18
main.go isn't an executable.

**Comment by thidasapankaja** [comment] 2022-07-10 16:28
@aarzilli sorry. I'm a bit confused. Shouldn't this be .go  file ?

Anyway I tried running it on a .dmg file (which is executable, right) and getting the same error ?

**Comment by aarzilli** [comment] 2022-07-10 16:53
No, dmg files aren't executable either. An executable is the output file of `go build`, for example.

**Comment by thidasapankaja** [comment] 2022-07-10 16:55
@aarzilli Yea, I updated the answer, getting this as the error now

```
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1316.0.9.46
 for x86_64 (running under translation).
error: failed to launch process /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver: (os/kern) invalid argument
Exiting.

```

**Comment by aarzilli** [comment] 2022-07-10 17:05
Ok, debugserver is failing on its own, without any interaction with delve. This is a problem with your setup. Closing.

**Closed by aarzilli** 2022-07-10 17:05 UTC

**Comment by aarzilli** [comment] 2022-07-10 17:32
PS. I noticed this:

```
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1316.0.9.46
 for x86_64 (running under translation).
```

**Comment by thidasapankaja** [comment] 2022-07-11 02:40
@aarzilli 
I ran this 
```
arch -arm64 /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver 127.0.0.1:31337 ./hello
```

and it is waiting for a connection

```
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1316.0.9.46
 for arm64.
Listening to port 31337 for a connection from 127.0.0.1...
```

**Comment by exosyphon** [comment] 2024-08-31 15:27
@thidasapankaja did you ever get this working? I am at the same point right now that you left off

**Comment by exosyphon** [comment] 2024-08-31 15:57
I figured out my issue. https://github.com/go-delve/delve/issues/3804
