### ISSUE TITLE
use the dlv on m1:could not launch process: stub exited while waiting for connection: exit status 0

### ISSUE THREAD

**Issue by lsk569937453** [go-delve/delve#3056] opened 2022-07-05 08:30 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)?

Delve Debugger
Version: 1.7.3
Build: $Id: 4c81a2a322716591167f0bd690f7ef656781b6f4 $

2. What version of Go are you using? (`go version`)?
  
go version go1.17.11 darwin/arm64

4. What operating system and processor architecture are you using?

MacBook Pro (16-inch, 2021) 
Apple M1 Pro

6. What did you do?

package main

import "fmt"

func main() {
	fmt.Println("1sdsad")
}

I just want to debug the code .

8. What did you expect to see?
The dlv could run normally.

10. What did you see instead?

I exec the command ' dlv debug graphQL-demo --headless --log  --log-output=lldbout'

The following is the output:

API server listening at: 127.0.0.1:49579
argv[0] = 127.0.0.1:49580
argv[1] = /Users/sliu/code/gitlab/graphql-demo/__debug_bin
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1316.0.9.46
 for arm64.
host = '127.0.0.1'  port = 49580
inferior_argv[0] = '/Users/sliu/code/gitlab/graphql-demo/__debug_bin'
1 +0.000000 sec [0c1d/0103]: RNBRunLoopLaunchInferior Launching '/Users/sliu/code/gitlab/graphql-demo/__debug_bin'...
2 +0.000062 sec [0c1d/0103]: DNBProcessLaunch ( path='/Users/sliu/code/gitlab/graphql-demo/__debug_bin', argv = 0x600003d50060, envp = 0x146e04b30, working_dir=(null), stdin=/dev/stdin, stdout=/dev/stdout, stderr=/dev/stderr, no-stdio=0, launch_flavor = 1, disable_aslr = 0, err = 0x16aeb1d68, err_len = 1024) called...
3 +0.000077 sec [0c1d/0103]: MachProcess::MachProcess()
4 +0.000005 sec [0c1d/0103]: MachProcess::SetState(Unloaded) ignoring redundant state change...
5 +0.000002 sec [0c1d/0103]: LaunchForDebug( path = '/Users/sliu/code/gitlab/graphql-demo/__debug_bin', argv = 0x600003d50060, envp = 0x146e04b30, launch_flavor = 1, disable_aslr = 0 )
6 +0.000002 sec [0c1d/0103]: MachProcess::SetState(Launching) upating state (previous state was Unloaded), event_mask = 0x00000001
7 +0.000002 sec [0c1d/0103]: PosixSpawnChildForPTraceDebugging ( path='/Users/sliu/code/gitlab/graphql-demo/__debug_bin', argv=0x600003d50060, envp=0x146e04b30, working_dir=(null), stdin=/dev/stdin, stdout=/dev/stdout stderr=/dev/stderr, no-stdio=0)
8 +0.000003 sec [0c1d/0103]: ::posix_spawnattr_init ( &attr ) err = 0x00000000
9 +0.000002 sec [0c1d/0103]: ::posix_spawnattr_setflags ( &attr, POSIX_SPAWN_START_SUSPENDED ) err = 0x00000000
10 +0.000002 sec [0c1d/0103]: ::posix_spawn_file_actions_init ( &file_actions ) err = 0x00000000
11 +0.000002 sec [0c1d/0103]: ::posix_spawn_file_actions_addopen (&file_actions, filedes=STDIN_FILENO, path='/dev/stdin') err = 0x00000000
12 +0.000001 sec [0c1d/0103]: ::posix_spawn_file_actions_addopen (&file_actions, filedes=STDOUT_FILENO, path='/dev/stdout') err = 0x00000000
13 +0.000002 sec [0c1d/0103]: ::posix_spawn_file_actions_addopen (&file_actions, filedes=STDERR_FILENO, path='/dev/stderr') err = 0x00000000
14 +0.000299 sec [0c1d/0103]: ::posix_spawnp ( pid => 3102, path = '/Users/sliu/code/gitlab/graphql-demo/__debug_bin', file_actions = 0x16aeb18e0, attr = 0x16aeb18f8, argv = 0x600003d50060, envp = 0x146e04b30 ) err = 0x00000000
15 +0.000008 sec [0c1d/0103]: MachProcess::PosixSpawnChildForPTraceDebugging ( ) pid=3102, cpu_type=0x0100000c
16 +0.000002 sec [0c1d/0103]: DNBArchProtocol::SetDefaultArchitecture (cpu_type=0x0100000c, cpu_subtype=0x00000000) => 1
17 +0.000001 sec [0c1d/0103]: ::posix_spawn_file_actions_destroy ( &file_actions ) err = 0x00000000
18 +0.000002 sec [0c1d/0103]: MachTask::StartExceptionThread ( )
[LaunchAttach] (3101) about to task_for_pid(3102)
error: [LaunchAttach] MachTask::TaskPortForProcessID task_for_pid(3102) failed: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure)
19 +0.004112 sec [0c1d/0103]: error: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) err = ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) (0x00000005)
[LaunchAttach] (3101) about to task_for_pid(3102)
error: [LaunchAttach] MachTask::TaskPortForProcessID task_for_pid(3102) failed: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure)
20 +0.010508 sec [0c1d/0103]: error: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) err = ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) (0x00000005)
[LaunchAttach] (3101) about to task_for_pid(3102)
error: [LaunchAttach] MachTask::TaskPortForProcessID task_for_pid(3102) failed: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure)
21 +0.011139 sec [0c1d/0103]: error: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) err = ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) (0x00000005)
[LaunchAttach] (3101) about to task_for_pid(3102)
error: [LaunchAttach] MachTask::TaskPortForProcessID task_for_pid(3102) failed: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure)
22 +0.011121 sec [0c1d/0103]: error: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) err = ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) (0x00000005)
[LaunchAttach] (3101) about to task_for_pid(3102)
error: [LaunchAttach] MachTask::TaskPortForProcessID task_for_pid(3102) failed: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure)
23 +0.011150 sec [0c1d/0103]: error: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) err = ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) (0x00000005)
[LaunchAttach] (3101) about to task_for_pid(3102)
error: [LaunchAttach] MachTask::TaskPortForProcessID task_for_pid(3102) failed: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure)
24 +0.011147 sec [0c1d/0103]: error: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) err = ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) (0x00000005)
[LaunchAttach] (3101) about to task_for_pid(3102)
error: [LaunchAttach] MachTask::TaskPortForProcessID task_for_pid(3102) failed: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure)
25 +0.011125 sec [0c1d/0103]: error: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) err = ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) (0x00000005)
[LaunchAttach] (3101) about to task_for_pid(3102)
error: [LaunchAttach] MachTask::TaskPortForProcessID task_for_pid(3102) failed: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure)
26 +0.011174 sec [0c1d/0103]: error: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) err = ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) (0x00000005)
[LaunchAttach] (3101) about to task_for_pid(3102)
error: [LaunchAttach] MachTask::TaskPortForProcessID task_for_pid(3102) failed: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure)
27 +0.011177 sec [0c1d/0103]: error: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) err = ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) (0x00000005)
[LaunchAttach] (3101) about to task_for_pid(3102)
error: [LaunchAttach] MachTask::TaskPortForProcessID task_for_pid(3102) failed: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure)
28 +0.011107 sec [0c1d/0103]: error: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) err = ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) (0x00000005)
error: MachTask::StartExceptionThread (): task invalid, exception thread start failed.
29 +0.011024 sec [0c1d/0103]: MachProcess::StartSTDIOThread ( )
30 +0.000020 sec [0c1d/0103]: MachProcess::SetState(Attaching) upating state (previous state was Launching), event_mask = 0x00000001
[LaunchAttach] (3101) About to ptrace(PT_ATTACHEXC, 3102)...
31 +0.000010 sec [0c1d/0a03]: MachProcess::STDIOThread ( arg = 0x14700ec00 ) thread starting...
32 +0.000010 sec [0c1d/0a03]: MachProcess::STDIOThread (0x14700ec00): thread exiting...
[LaunchAttach] (3101) Completed ptrace(PT_ATTACHEXC, 3102) == 0
33 +0.000029 sec [0c1d/0103]: successfully spawned pid 3102
34 +0.000003 sec [0c1d/0103]: (DebugNub) new pid is 3102...
[LaunchAttach] (3101) about to task_for_pid(3102)
error: [LaunchAttach] MachTask::TaskPortForProcessID task_for_pid(3102) failed: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure)
35 +0.000149 sec [0c1d/0103]: error: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) err = ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) (0x00000005)
1sdsad
36 +0.003603 sec [0c1d/0a07]: waitpid (3102) -> EXITED (status = 0)
37 +0.000006 sec [0c1d/0a07]: waitpid_process_thread (): setting exit status for pid = 3102 to 0
[LaunchAttach] (3101) about to task_for_pid(3102)
error: [LaunchAttach] MachTask::TaskPortForProcessID task_for_pid(3102) failed: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure)
38 +0.007411 sec [0c1d/0103]: error: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) err = ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) (0x00000005)
[LaunchAttach] (3101) about to task_for_pid(3102)
error: [LaunchAttach] MachTask::TaskPortForProcessID task_for_pid(3102) failed: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure)
39 +0.011020 sec [0c1d/0103]: error: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) err = ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) (0x00000005)
[LaunchAttach] (3101) about to task_for_pid(3102)
error: [LaunchAttach] MachTask::TaskPortForProcessID task_for_pid(3102) failed: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure)
40 +0.011020 sec [0c1d/0103]: error: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) err = ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) (0x00000005)
[LaunchAttach] (3101) about to task_for_pid(3102)
error: [LaunchAttach] MachTask::TaskPortForProcessID task_for_pid(3102) failed: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure)
41 +0.011016 sec [0c1d/0103]: error: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) err = ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) (0x00000005)
[LaunchAttach] (3101) about to task_for_pid(3102)
error: [LaunchAttach] MachTask::TaskPortForProcessID task_for_pid(3102) failed: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure)
42 +0.011017 sec [0c1d/0103]: error: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) err = ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) (0x00000005)
[LaunchAttach] (3101) about to task_for_pid(3102)
error: [LaunchAttach] MachTask::TaskPortForProcessID task_for_pid(3102) failed: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure)
43 +0.011028 sec [0c1d/0103]: error: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) err = ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) (0x00000005)
[LaunchAttach] (3101) about to task_for_pid(3102)
error: [LaunchAttach] MachTask::TaskPortForProcessID task_for_pid(3102) failed: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure)
44 +0.011031 sec [0c1d/0103]: error: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) err = ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) (0x00000005)
[LaunchAttach] (3101) about to task_for_pid(3102)
error: [LaunchAttach] MachTask::TaskPortForProcessID task_for_pid(3102) failed: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure)
45 +0.011021 sec [0c1d/0103]: error: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) err = ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) (0x00000005)
[LaunchAttach] (3101) about to task_for_pid(3102)
error: [LaunchAttach] MachTask::TaskPortForProcessID task_for_pid(3102) failed: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure)
46 +0.011020 sec [0c1d/0103]: error: ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) err = ::task_for_pid ( target_tport = 0x0203, pid = 3102, &task ) => err = 0x00000005 ((os/kern) failure) (0x00000005)
Could not get task port for process, sending SIGKILL and exiting.
47 +0.011020 sec [0c1d/0103]: MachProcess::~MachProcess()
48 +0.000004 sec [0c1d/0103]: MachProcess::SetState(Unloaded) upating state (previous state was Attaching), event_mask = 0x00000002
49 +0.000006 sec [0c1d/0103]: RNBRunLoopLaunchInferior DNBProcessLaunch() returned error: 'failed to get the task for process 3102'
error: failed to launch process /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver: failed to get the task for process 3102
50 +0.000014 sec [0c1d/0103]:   225778 RNBRemote::StopReadRemoteDataThread called
Exiting.
51 +0.000008 sec [0c1d/0103]: RNBRemote::~RNBRemote()
52 +0.000003 sec [0c1d/0103]:       10 RNBRemote::StopReadRemoteDataThread called
could not launch process: stub exited while waiting for connection: exit status 0

**Comment by aarzilli** [comment] 2022-07-06 06:20
Your user doesn't have the right permissions to debug a process. See https://github.com/go-delve/delve/tree/master/Documentation/installation, if nothing there helps contact apple.
Closing, not a bug.

**Closed by aarzilli** 2022-07-06 06:20 UTC
