### ISSUE TITLE
Delve Fails to Locate Source Files Across All Projects on Apple M1 Pro (macOS) with "no source available" Error

### ISSUE THREAD

**Issue by liza-yemini** [go-delve/delve#3790] opened 2024-08-12 12:54 UTC
### 1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.23.0
Build: 64f3d346638c29aac3aba21b4d07fc7d55e4957b

### 2. What version of Go are you using? (`go version`)
go version go1.22.6 darwin/arm64

### 3. What operating system and processor architecture are you using?
Operating System: macOS Sonoma version 14.5
Processor Architecture: Apple M1 Pro (arm64)

### 4. What did you do?
I attempted to debug a Go application using Delve in GoLand. I tried both running Delve directly from the terminal using the following command:
`dlv debug .../cmd --log --log-output=debugger,rpc`
And initiating the debugging session within GoLand by setting breakpoints and starting the debugger.

### 5. What did you expect to see?

I expected Delve to recognize the source files, allow breakpoints to be set, and provide source-level debugging. Specifically, I expected to see the debugger stop at breakpoints and display the source code associated with the current program counter.

### 6. What did you see instead?

Delve starts, but it immediately displays the error "no source available," and the breakpoints do not work. The debugger does not show the source code, and the logs indicate that Delve cannot locate the corresponding source files. Below is a snippet of the log:
```
024-08-12T06:37:40-06:00 debug layer=rpc (async 8) <- RPCServer.State(rpc2.StateIn{"NonBlocking"
})
2024-08-12T06:37:40-06:00 debug layer=rpc (async 8) -> rpc2.StateOut{"State":{"Pid":91889,"TargetCommandLine":".../__debug_bin2947480261","Running"
,"Recording"
,"CoreDumping"
,"currentThread":{"id":2884094,"pc":4374563696,"file":"","line":0,"goroutineID":0,"ReturnValues"
,"CallReturn"
},"Threads":[{"id":2884094,"pc":4374563696,"file":"","line":0,"goroutineID":0,"ReturnValues"
,"CallReturn"
}],"NextInProgress"
,"WatchOutOfScope"
,"exited"
,"exitStatus":0,"When":""}} error: ""
(dlv)
=> 1: no source available
```

### Additional Information
- This issue occurs across all Go services I work on, not just a specific project.
- I have tried upgrading both GoLand and Delve. I also downloaded and installed Delve via Homebrew, but these steps did not resolve the issue.
- I have ensured that the Go binaries are compiled with `-gcflags="all=-N -l"` to include debug symbols.
- I have verified that the source files' paths are correct and accessible.
- I attempted to set breakpoints manually using full paths.
- The debugger logs indicate that Delve cannot locate the source files, but this behavior is consistent across different projects.

This issue seems to be related to my development environment or a configuration affecting all services I work on.

**Comment by aarzilli** [comment] 2024-08-12 13:21
It's normal for the entry point of the program to not have a source file associated.
Closing, duplicate of #1550.

**Closed by aarzilli** 2024-08-12 13:21 UTC
