### ISSUE TITLE
dlv panic 

### ISSUE THREAD

**Issue by rmGFW** [go-delve/delve#2162] opened 2020-09-06 15:36 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
1.5.0
2. What version of Go are you using? (`go version`)?
go1.14 linux/amd64
3. What operating system and processor architecture are you using?
Tencent tlinux release 2.2 (Final)  in x86_64
4. What did you do?
use dlv debug command to debug a go program 
5. What did you expect to see?
i hope dlv can work
6. What did you see instead?
![image](https://user-images.githubusercontent.com/66858140/92329396-cdb3da00-f099-11ea-98a4-ce15c3bc9552.png)

**Comment by chainhelen** [comment] 2020-09-07 03:53
This is a bug.

**Comment by rmGFW** [comment] 2020-09-07 03:55
> This is a bug.

but dlv work on my mac well .

i install dlv by brew 

but on my linux pc . i install by go get

**Comment by chainhelen** [comment] 2020-09-07 04:01
Not your fault, don't worry, I will fix it.

**Comment by aarzilli** [comment] 2020-09-07 05:35
I think this is already fixed by f90134eb4db1c423e24fddfbc6eff41b288e6297, however stepping like that won't do anything useful: you should set a breakpoint on main and continue.

**Comment by chainhelen** [comment] 2020-09-07 05:44
> I think this is already fixed by [f90134e](https://github.com/go-delve/delve/commit/f90134eb4db1c423e24fddfbc6eff41b288e6297), however stepping like that won't do anything useful: you should set a breakpoint on main and continue.



@aarzilli I have try master branch (include f90134e), also panic. So I create one new pr to solve this issue.

**Comment by aarzilli** [comment] 2020-09-07 06:30
Are you sure about this? Because I can't reproduce it on master.

**Comment by chainhelen** [comment] 2020-09-07 06:59
@aarzilli Yes.  so strange?

OS:
```
// also happened go1.15.1 linux/amd64
go version go1.14.8 linux/amd64
```

dlv version:
```
// install by master
commit 7555d1c06339e51a4f1e2d7a62dc9c44745e10b7 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
cmd,proc,terminal,debugger: Support default file descriptor redirects

make install 
go install "-ldflags=-X main.Build=7555d1c06339e51a4f1e2d7a62dc9c44745e10b7" github.com/go-delve/delve/cmd/dlv
```


```
// cat main.go
package main

import "fmt"

func main() {
	fmt.Println("test dlv")
}


dlv debug main.go   
Type 'help' for list of commands.
(dlv) b main.main
Breakpoint 1 set at 0x4adadf for main.main() ./main.go:5
(dlv) s
> main.main() ./main.go:5 (hits goroutine(1):1 total:1) (PC: 0x4adadf)
Command failed: Internal debugger error: ast.Walk: unexpected node type <nil>
runtime.gopanic (0x4344f5)
	/usr/local/go/src/runtime/panic.go:969
go/ast.Walk (0x5f7313)
	/usr/local/go/src/go/ast/walk.go:364
go/ast.Walk (0x5f5b17)
	/usr/local/go/src/go/ast/walk.go:146
github.com/go-delve/delve/pkg/proc.onNextGoroutine (0x71f4c3)
	/media/chainhelen/LENOVO/xlworkspace/code/go/src/github.com/go-delve/delve/pkg/proc/target_exec.go:1025
github.com/go-delve/delve/pkg/proc.(*Target).Continue (0x718dfe)
	/media/chainhelen/LENOVO/xlworkspace/code/go/src/github.com/go-delve/delve/pkg/proc/target_exec.go:189
github.com/go-delve/delve/pkg/proc.(*Target).Step (0x71a39c)
	/media/chainhelen/LENOVO/xlworkspace/code/go/src/github.com/go-delve/delve/pkg/proc/target_exec.go:306
github.com/go-delve/delve/service/debugger.(*Debugger).Command (0x799dc0)
	/media/chainhelen/LENOVO/xlworkspace/code/go/src/github.com/go-delve/delve/service/debugger/debugger.go:945
github.com/go-delve/delve/service/rpc2.(*RPCServer).Command (0x94ddc0)
	/media/chainhelen/LENOVO/xlworkspace/code/go/src/github.com/go-delve/delve/service/rpc2/server.go:129
reflect.Value.call (0x4c3a8a)
	/usr/local/go/src/reflect/value.go:460
reflect.Value.Call (0x4c2f93)
	/usr/local/go/src/reflect/value.go:321
github.com/go-delve/delve/service/rpccommon.(*ServerImpl).serveJSONCodec.func3 (0xa1ca29)
	/media/chainhelen/LENOVO/xlworkspace/code/go/src/github.com/go-delve/delve/service/rpccommon/server.go:338
runtime.goexit (0x464be0)
	/usr/local/go/src/runtime/asm_amd64.s:1373

```


![Selection_012](https://user-images.githubusercontent.com/7046329/92357572-a94c1200-f11a-11ea-82c6-778f043f251c.png)

**Closed** 2020-09-08 22:18 UTC
Labels: area/proc, kind/bug
