### ISSUE TITLE
Delve build error with Go tip 

### ISSUE THREAD

**Issue by archanaravindar** [go-delve/delve#3478] opened 2023-08-23 08:26 UTC
Delve Debugger
Version: 1.20.2
Build: Id: e0c278ad8e0126a312b553b8e171e81bcbd37f60 

Go
go version devel go1.22-e68c027204 Wed Aug 23 05:58:20 2023 +0000 linux/amd64

Tested on linux/amd64 and linux/ppc64le

Encountering the following error building delve using the following commands 
(on linux/amd64)

```
 go run _scripts/make.go build
# command-line-arguments
_scripts/make.go:154:6: internal compiler error: 'checkCertCmd': value ~R0 (v85) incorrectly live at entry

goroutine 36 [running]:
runtime/debug.Stack()
	../../../Gotip/go/src/runtime/debug/stack.go:24 +0x5e
cmd/compile/internal/base.FatalfAt({0x106f3d0?, 0xc0?}, {0xc00015e4b0, 0x2d}, {0xc0010665a0, 0x3, 0x3})
	../../../Gotip/go/src/cmd/compile/internal/base/print.go:230 +0x1d7
cmd/compile/internal/base.Fatalf(...)
	../../../Gotip/go/src/cmd/compile/internal/base/print.go:199
cmd/compile/internal/ssagen.(*ssafn).Fatalf(0x0?, {0x5?, 0x0?}, {0xd80171, 0x27}, {0xc000116dc0, 0x2, 0xc00106f401?})
	../../../Gotip/go/src/cmd/compile/internal/ssagen/ssa.go:8005 +0x16a
cmd/compile/internal/ssagen.(*state).Fatalf(0xcdc4e0?, {0xd80171?, 0xc000c4fcb0?}, {0xc000116dc0?, 0xebae58?, 0xc00013ba60?})
	../../../Gotip/go/src/cmd/compile/internal/ssagen/ssa.go:928 +0x67
cmd/compile/internal/ssagen.(*simplePhiState).insertPhis(0xc00106f988)
	../../../Gotip/go/src/cmd/compile/internal/ssagen/phi.go:486 +0x299
cmd/compile/internal/ssagen.(*state).insertPhis(...)
	../../../Gotip/go/src/cmd/compile/internal/ssagen/phi.go:45
cmd/compile/internal/ssagen.buildssa(0xc000a25a20, 0x1)
	../../../Gotip/go/src/cmd/compile/internal/ssagen/ssa.go:564 +0x29ec
cmd/compile/internal/ssagen.Compile(0xc000a25a20, 0x0?)
	../../../Gotip/go/src/cmd/compile/internal/ssagen/pgen.go:216 +0x45
cmd/compile/internal/gc.compileFunctions.func5.1(0x0?)
	../../../Gotip/go/src/cmd/compile/internal/gc/compile.go:186 +0x34
cmd/compile/internal/gc.compileFunctions.func3.1()
	../../../Gotip/go/src/cmd/compile/internal/gc/compile.go:168 +0x30
created by cmd/compile/internal/gc.compileFunctions.func3 in goroutine 20
	../../../Gotip/go/src/cmd/compile/internal/gc/compile.go:167 +0x247
```
(on linux/ppc64le)
```
go run _scripts/make.go build --tags exp.linuxppc64le
# command-line-arguments
_scripts/make.go:154:6: internal compiler error: 'checkCertCmd': value ~R0 (v85) incorrectly live at entry

goroutine 8 [running]:
runtime/debug.Stack()
    ../../../master-aug16/go/src/runtime/debug/stack.go:24 +0x6c
cmd/compile/internal/base.FatalfAt({0x11b9340?, 0xc0?}, {0xc0000287b0, 0x2d}, {0xc0011acb40, 0x3, 0x3})
    ../../../master-aug16/go/src/cmd/compile/internal/base/print.go:230 +0x270
cmd/compile/internal/base.Fatalf(...)
    ../../../master-aug16/go/src/cmd/compile/internal/base/print.go:199
cmd/compile/internal/ssagen.(*ssafn).Fatalf(0x658988?, {0x5?, 0x0?}, {0x972e3e, 0x27}, {0xc00007adc0, 0x2, 0xc0011b9401?})
    ../../../master-aug16/go/src/cmd/compile/internal/ssagen/ssa.go:8017 +0x1a0
cmd/compile/internal/ssagen.(*state).Fatalf(0x8cf080?, {0x972e3e?, 0xc000bcfcb0?}, {0xc00007adc0?, 0xabc560?, 0xc000037b40?})
    ../../../master-aug16/go/src/cmd/compile/internal/ssagen/ssa.go:936 +0xb8
cmd/compile/internal/ssagen.(*simplePhiState).insertPhis(0xc0011b9900)
    ../../../master-aug16/go/src/cmd/compile/internal/ssagen/phi.go:486 +0x288
cmd/compile/internal/ssagen.(*state).insertPhis(...)
    ../../../master-aug16/go/src/cmd/compile/internal/ssagen/phi.go:45
cmd/compile/internal/ssagen.buildssa(0xc000949600, 0x1)
    ../../../master-aug16/go/src/cmd/compile/internal/ssagen/ssa.go:569 +0x25f8
cmd/compile/internal/ssagen.Compile(0xc000949600, 0x0?)
    ../../../master-aug16/go/src/cmd/compile/internal/ssagen/pgen.go:216 +0x48
cmd/compile/internal/gc.compileFunctions.func5.1(0x0?)
    ../../../master-aug16/go/src/cmd/compile/internal/gc/compile.go:189 +0x4c
cmd/compile/internal/gc.compileFunctions.func3.1()
    ../../../master-aug16/go/src/cmd/compile/internal/gc/compile.go:171 +0x48
created by cmd/compile/internal/gc.compileFunctions.func3 in goroutine 20
    ../../../master-aug16/go/src/cmd/compile/internal/gc/compile.go:170 +0x20c
```

Testing with this branch the error does not occur and delve builds fine and runs on both linux/ppc64le and linux/amd64
 git fetch https://go.googlesource.com/go refs/changes/17/519417/2 && git checkout -b change-519417 FETCH_HEAD
However since this change has now been merged on Aug 18 and the error seems to occur on tip version too need to check why this is the case

**Comment by aarzilli** [comment] 2023-08-23 09:18
Duplicate of https://github.com/golang/go/issues/62211

**Closed by aarzilli** 2023-08-23 09:18 UTC
