### ISSUE TITLE
pkg/proc: support gnu_debuglink method of finding split debug info

### ISSUE THREAD

**Issue by vbatts** [go-delve/delve#2802] opened 2021-11-21 01:24 UTC
## info 

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.7.2
Build: $Id: 5b6f24e7fbcad3fe3bc574d3763b2f20afa1d6a1 $

2. What version of Go are you using? (`go version`)?
go version go1.17.3 linux/amd64

3. What operating system and processor architecture are you using?
debian/sid amd64

4. What did you do?
`dlv exec <command>`

5. What did you expect to see?
the dlv command line

6. What did you see instead?
`could not launch process: could not open debug info`

## request

While poking around https://github.com/containerd/nerdctl, I attempted to use `dlv` to inspect it. I found that they compile with `go build -ldflags "-s -w " ...` presumably for size, but now delve can't do its thing.

I remove the `-s -w`, and recompile and carry-on.

But then question whether we can just link the debug info like gcc does for C/C++/etc.

So I copied out these debug symbols, stripped them from the binary, and linked the debuginfo file.

```shell
vbatts@fogel:~/src/github.com/containerd/nerdctl$ make
GO111MODULE=on CGO_ENABLED=0 GOOS=linux go build -ldflags "-X github.com/containerd/nerdctl/pkg/version.Version=v0.13.0-43-g1e5041f.m -X github.com/containerd/nerdctl/pkg/version.Revision=1e5041feefdbdeb5825cad2bbe6263ea1a0c7d25.m"  -o /home/vbatts/src/github.com/containerd/nerdctl/_output/nerdctl github.com/containerd/nerdctl/cmd/nerdctl
vbatts@fogel:~/src/github.com/containerd/nerdctl$ link-debug _output/nerdctl 
+ name=_output/nerdctl
+ objcopy --only-keep-debug _output/nerdctl _output/nerdctl.debug
+ objcopy --strip-debug _output/nerdctl
+ objcopy --add-gnu-debuglink=_output/nerdctl.debug _output/nerdctl
vbatts@fogel:~/src/github.com/containerd/nerdctl$ ls -lsh _output/
total 40M
29M -rwxr-xr-x 1 vbatts vbatts 29M Nov 20 20:22 nerdctl*
11M -rwxr-xr-x 1 vbatts vbatts 11M Nov 20 20:22 nerdctl.debug*
vbatts@fogel:~/src/github.com/containerd/nerdctl$ objdump -Wk _output/nerdctl

_output/nerdctl: Found separate debug info file: /home/vbatts/src/github.com/containerd/nerdctl/_output/nerdctl.debug

_output/nerdctl:     file format elf64-x86-64

Contents of the .gnu_debuglink section (loaded from _output/nerdctl):

  Separate debug info file: nerdctl.debug
  CRC value: 0x3b0fa3d6
```

but still no dice from `dlv`

```shell
vbatts@fogel:~/src/github.com/containerd/nerdctl$ dlv exec ./_output/nerdctl
could not launch process: could not open debug info
```

**Comment by aarzilli** [comment] 2021-11-21 12:31
gnu_debuglink is not supported but split debug info is, by setting the `debug-info-directories` option in the configuration.

**Comment by aarzilli** [comment] 2021-12-08 14:39
Duplicate of #2150

**Closed by aarzilli** 2021-12-08 14:39 UTC
Labels: enhancement, area/proc
