### ISSUE TITLE
Delve slow startup (60+ seconds in some cases) causes debugging to timeout when running in IntelliJ Idea.

### ISSUE THREAD

**Issue by ranganath42** [go-delve/delve#2072] opened 2020-06-03 14:21 UTC
**Deleve version**
Version: 1.4.0
Build: 8bb93e9ae19589b7ee665225c2206ef118928ae9

**Go version**
go1.14.2 windows/amd64

**OS**
Edition: Windows 10 Pro
Version: 1909
Build: 18363.836

**IntelliJ IDEA**
2020.2 Ultimate EAP
2020.1.2 Ultimate 

**What did you do?**
As a domain user, run dlv.exe debugger from IntelliJ IDEA on a domain-joined computer that is currently not connected to the domain.

**What did you expect to see?**
Deleve debug session successfully starts.

**What did you see instead?**
Debug session gets timed out after 60 seconds waiting for Deleve to start up.

**Root cause**

- At startup, as a part of loading/saving the configuration, Deleve attempts to find out the home directory of the current user.
- This is done using `user.Current()` function in `os/user` package, which takes more than 60 seconds to return.
- This delay causes Deleve to get killed by the IntelliJ IDEA debugger connection timeout.

**Detailed description of the root cause**
- The `user.Current()` function in `os/user` package tries to obtain information about the current user in addition to the home directory.
- One of them is the fully qualified user name.
- Since this is a domain-joined computer, to obtain the full name, the function tries to do a name translation from SAM compatible name to display name using the `TranslateNameW` Windows system call.
- Since the computer is currently not connected to the domain, this syscall fails with 'domain could not be contacted'.
- When this attempt fails, the function then tries to query the full user name using the `NetUserGetInfo` syscall. This syscall is the culprit, taking 60 seconds upwards to return.

**Fix**
Since Deleve only needs to know about the home directory of the current user, the easiest way to fix is to use the `GetUserProfileDirectoryW` syscall. Like so.
```
func homeDir() (string, error) {
	t, err := syscall.OpenCurrentProcessToken()
	if err != nil {
		return "", err
	}
	defer t.Close()

	dir, err := t.GetUserProfileDirectory()
	if err != nil {
		return "", err
	}

	return dir, err
}
```
This function can them be used in place of the `user.Current()`. If this sounds reasonable, I will submit a pull request.

**Comment by aarzilli** [comment] 2020-06-03 15:34
I think you should report this problem to the go project, this seems like a very general problem that would affect much more than delve and it doesn't seem like a good idea to have a workaround in every program that wants the path to the home directory.

cc @alexbrainman

**Comment by alexbrainman** [comment] 2020-06-04 03:08
I agree with @aarzilli this is a Go issue. @ranganath42 please create similar issue at

http://golang.org/issues/new

Thank you.

@aarzilli 

Depending on how this issue is accepted at http://golang.org/issues you should still consider accepting small / fast version of the code that Delve needs. Go Team might decide to do nothing about this.

Alex

**Comment by ranganath42** [comment] 2020-06-04 23:19
Thanks.

I will raise a ticket in the Go standard library, but that will be for a feature request to add a helper to get only the home directory of the current user (something like `user.HomeDir()`). The `user.Current()` is doing what it is advertised to do. 

The issue here is that Delve is using the wrong tool to get the home directory. The `user.current()` is an overkill just to get the home directory. And the Go standard library has tools to get just that via a process token (as in the previous code snippet).

I'm proposing we stay away from `user.Current()` for now. If/when the feature request gets accepted, we can pivot to using that.

**Comment by alexbrainman** [comment] 2020-06-06 01:56
> I will raise a ticket in the Go standard library, but that will be for a feature request to add a helper to get only the home directory of the current user (something like `user.HomeDir()`). The `user.Current()` is doing what it is advertised to do.

I disagree. Delve is using correct facilities to fetch home directory. The problem is the implementation takes too long to get result. Lets see, if we can fix current code.

> The issue here is that Delve is using the wrong tool to get the home directory. The `user.current()` is an overkill just to get the home directory. And the Go standard library has tools to get just that via a process token (as in the previous code snippet).

Your code will only run on Windows. Perhaps you could even solve your problem by looking at some environment variables. But lets see, if we can fix current code instead.

Alex

**Comment by mainpart** [comment] 2021-02-01 05:36
Any update on the topic? I can't debug in golang due this issue. Any way to specify that IDE need to wait for delve a litle bit longer?

**Comment by aarzilli** [comment] 2021-02-01 07:54
As far as I know noone ever opened an upstream bug.

**Comment by mainpart** [comment] 2021-04-13 07:59
I solved this problem with Jetbrains Golang by recompiling delve with hard-coded userdir. Inside pkg/config/config.go

```golang
func getUserHomeDir() string {
	return "c:\\Users\\profileusername"
}

```
Then i had to rebuild delve 

```
go build cmd/dlv/main.go
```

and put result into "C:\Program Files\JetBrains\GoLand <version>\plugins\go\lib\dlv\windows\"  as dlv.exe

hope this helps to someone till upstream bug will be solved

**Comment by aarzilli** [comment] 2022-01-29 16:21
Closing, the environment variable XDG_CONFIG_HOME can be used to bypass home directory lookup on windows.

**Closed by aarzilli** 2022-01-29 16:21 UTC
Labels: os/windows, kind/discussion
