### ISSUE TITLE
delve Crashes When Debugging Starts - panic with R_USEIFACE

### ISSUE THREAD

**Issue by ossie-git** [go-delve/delve#3847] opened 2024-11-01 01:08 UTC
1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.23.1
Build: $Id: 2eba762d75437d380e48fc42213853f13aa2904d $
```
2. What version of Go are you using? (`go version`)?
```
go version go1.23.2 linux/amd64
```
3. What operating system and processor architecture are you using?
```
Linux debian12.localdomain 6.1.0-26-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30) x86_64 GNU/Linux
```
4. What did you do?
I ran into this when trying to debug link:https://github.com/trufflesecurity/trufflehog. The steps I took were as follows:

```
$ git clone https://github.com/trufflesecurity/trufflehog
$ cd trufflehog
$ dlv debug
# github.com/trufflesecurity/trufflehog/v3
panic: R_USEIFACE in github.com/microsoft/go-mssqldb.processSingleResponse references  which is not a type or itab

goroutine 1 [running]:
cmd/link/internal/ld.(*deadcodePass).flood(0xc0000cf688)
        cmd/link/internal/ld/deadcode.go:215 +0x1299
cmd/link/internal/ld.deadcode(0xc00010c200)
        cmd/link/internal/ld/deadcode.go:467 +0xc5
cmd/link/internal/ld.Main(_, {0x20, 0x20, 0x1, 0x7, 0x10, 0x0, {0xc000092391, 0x1, 0x1}, ...})
        cmd/link/internal/ld/main.go:360 +0x1318
main.main()
        cmd/link/main.go:72 +0xddb
exit status 1
```

Meanwhile, other go binaries can be debugged without issue. Also, if I build the project, it runs fine and I ran run:

```
dlv exec ./trufflehog
```

so the problem is only when I try to debug it using delve + source code

5. What did you expect to see?

See above

6. What did you see instead?

See above

**Comment by aarzilli** [comment] 2024-11-01 06:11
I can not reproduce this but if I did it would be a linker bug: what you are seeing is a panic while the linker is executing. The reason you are not seeing this bug when compiling normally might be because you are not disabling optimizations, like delve does.
Try `go build -gcflags='all=-N -l'` after `export CGO_CFLAGS='-O0 -g'`.

Either way it isn't a bug in delve so I'm closing the issue but if you can reproduce it you should definitely open an issue on golang/go's repository.

**Closed by aarzilli** 2024-11-01 06:11 UTC
