### ISSUE TITLE
Go1.21 incorrect int values

### ISSUE THREAD

**Issue by yardenlaif** [go-delve/delve#3459] opened 2023-08-10 13:40 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.21.0
Build: $Id: fec0d226b2c2cce1567d5f59169660cf61dc1efe $
2. What version of Go are you using? (`go version`)?
go version go1.21.0 linux/arm64
3. What operating system and processor architecture are you using?
ubuntu, aarch64. Does NOT reproduce on x64 ubuntu.
4. What did you do?
Debugged the following program:
package main

import "fmt"

func main() {
        SimpleMethodWithArgument(0)
}

//go:noinline
func SimpleMethodWithArgument(i int) {
        a := 5
        y := 10
        x := a + y + i // Breakpoint here
        fmt.Printf("a: %v, y: %v\n", a, y)
        _ = x
        return
}
5. What did you expect to see?
Value of `a` should be 5, value of `y` should be 10
6. What did you see instead?
Value of `a` is 109788, value of `y` is 109116 (these values seem to be consistent)

**Comment by yardenlaif** [comment] 2023-08-10 14:03
Looking at the pcln table of the function in go1.20 vs. go1.21, it does seem like some PCs at the start of the function are considered to be on the breakpoint line in go1.21 that aren't in go1.20.
Go1.20 pcln:
        value=161 until offset=0x00000020, 
        value=162 until offset=0x00000028, 
        value=163 until offset=0x00000030, 
        value=164 until offset=0x00000038, 
        value=165 until offset=0x00000108, 
        value=167 until offset=0x00000114, 
        value=161 until offset=0x00000130, 
Go1.21 pcln:
        value=161 until offset=0x00000020,                                                                                                                                                                
        value=164 until offset=0x00000024,   
        value=162 until offset=0x0000002c, 
        value=163 until offset=0x00000034, 
        value=164 until offset=0x00000038,                                                                
        value=165 until offset=0x00000110, 
        value=167 until offset=0x0000011c,                                                                                                                                                                           
        value=161 until offset=0x00000130,

**Comment by yardenlaif** [comment] 2023-08-10 14:13
Looking at the disassembly of the function, the instruction that's considered part of the breakpoint line is: `ADD X1, X0, #0xf`. Seems like the compiler does the `a+y` part as part of the compilation process because they are consts, but I'm not sure why it's done before the assignment of values to `a` and `y`.

The disassembly of the function is:
> 0x00000000: LDR X16, [X28,#16]                                                                                                                                                                                       
0x00000004: SUB X17, SP, #0x20                                                                                                                                                                                       
0x00000008: CMP X17, X16                                                                                                                                                                                             
0x0000000c: B LS, .+0x110                                                                                                                                                                                            
0x00000010: STR X30, [SP,#-160]!                                                                                                                                                                                     
0x00000014: STUR X29, [SP,#-8]                                                                                                                                                                                       
0x00000018: SUB X29, SP, #0x8                                                                                                                                                                                        
0x0000001c: STR X0, [SP,#168]                                                                                                                                                                                        
0x00000020: ADD X1, X0, #0xf                                                                                                                                                                                         
0x00000024: MOV X2, #0x5                                                                                                                                                                                             
0x00000028: STR X2, [SP,#64]                                                                                                                                                                                         
0x0000002c: MOV X2, #0xa                                                                                                                                                                                             
0x00000030: STR X2, [SP,#48]                                                                                                                                                                                         
0x00000034: STR X1, [SP,#56]                                                                                                                                                                                         
0x00000038: STP XZR, XZR, [SP,#120]                                                                                                                                                                                  
0x0000003c: STP XZR, XZR, [SP,#136]                                                                                                                                                                                  
0x00000040: ADD X1, SP, #0x78                                                                                                                                                                                        
0x00000044: STR X1, [SP,#88]                                                                                                                                                                                         
0x00000048: LDR X0, [SP,#64]                                                                                                                                                                                         
0x0000004c: BL .+0xffffffffff76b9d4                                                                                                                                                                                  
0x00000050: STR X0, [SP,#80]                                                                                                                                                                                         
0x00000054: LDR X1, [SP,#88]                                                                                                                                                                                         
0x00000058: LDRSB X27, [X1]                                                                                                                                                                                          
0x0000005c: ADRP X2, .+0x17c000                                                                                                                                                                                      
0x00000060: ADD X2, X2, #0x420                                                                                                                                                                                       
0x00000064: STR X2, [X1]                                                                                                                                                                                             
0x00000068: ADRP X27, .+0xc9e000                                                                                                                                                                                     
0x0000006c: LDR W2, [X27,#2960]                                                                                                                                                                                      
0x00000070: CBZ W2, .+0x8                                                                                                                                                                                            
0x00000074: B .+0x8                                                                                                                                                                                                  
0x00000078: B .+0x18                                                                                                                                                                                                 
0x0000007c: BL .+0xffffffffff7d15a4                                                                                                                                                                                  
0x00000080: STR X0, [X25]                                                                                                                                                                                            
0x00000084: LDR X2, [X1,#8]                                                                                                                                                                                          
0x00000088: STR X2, [X25,#8]                                                                                                                                                                                         
0x0000008c: B .+0x4                                                                                                                                                                                                  
0x00000090: STR X0, [X1,#8]                                                                                                                                                                                          
0x00000094: LDR X0, [SP,#48]                                                                                                                                                                                         
0x00000098: BL .+0xffffffffff76b988                                                                                                                                                                                  
0x0000009c: STR X0, [SP,#72]                                                                                                                                                                                         
0x000000a0: LDR X1, [SP,#88]                                                                                                                                                                                         
0x000000a4: LDRSB X27, [X1]                                                                                                                                                                                          
0x000000a8: ADRP X2, .+0x17c000                                                                                                                                                                                      
0x000000ac: ADD X2, X2, #0x420                                                                                                                                                                                       
0x000000b0: STR X2, [X1,#16]                                                                                                                                                                                         
0x000000b4: ADRP X27, .+0xc9e000                                                                                                                                                                                     
0x000000b8: LDR W2, [X27,#2960]                                                                                                                                                                                      
0x000000bc: CBZ W2, .+0x8                                                                                                                                                                                            
0x000000c0: B .+0x8                                                                                                                                                                                                  
0x000000c4: B .+0x18                                                                                                                                                                                                 
0x000000c8: BL .+0xffffffffff7d1558                                                                                                                                                                                  
0x000000cc: STR X0, [X25]                                                                                                                                                                                            
0x000000d0: LDR X5, [X1,#24]                                                                                                                                                                                         
0x000000d4: STR X5, [X25,#8]                                                                                                                                                                                         
0x000000d8: B .+0x4                      
0x000000dc: STR X0, [X1,#24]
0x000000e0: LDR X2, [SP,#88]
0x000000e4: LDRSB X27, [X2]
0x000000e8: B .+0x4                                  
0x000000ec: STR X2, [SP,#96]
0x000000f0: ORR X4, XZR, #0x2
0x000000f4: STR X4, [SP,#104]
0x000000f8: STR X4, [SP,#112]
0x000000fc: ADRP X0, .+0x282000
0x00000100: ADD X0, X0, #0xfd6
0x00000104: MOV X1, #0xd                             
0x00000108: MOV X3, X4                               
0x0000010c: BL .+0xffffffffff893144
0x00000110: LDP X29, X30, [SP,#-8]
0x00000114: ADD SP, SP, #0xa0
0x00000118: RET X30                                  
0x0000011c: STR X0, [SP,#8]
0x00000120: MOV X3, X30                              
0x00000124: BL .+0xffffffffff7cf01c
0x00000128: LDR X0, [SP,#8]
0x0000012c: B .+0xfffffffffffffed4

**Comment by aarzilli** [comment] 2023-08-10 14:39
How did you start the debugger? `dlv debug` or `dlv exec`?

**Comment by yardenlaif** [comment] 2023-08-10 17:04
Both have this issue

**Comment by aarzilli** [comment] 2023-08-10 17:16
Likely this is a problem with the location expressions for the variables.

**Comment by aarzilli** [comment] 2023-08-10 19:27
Usually things like these end up being problems with the compiler.

**Comment by yardenlaif** [comment] 2023-08-10 19:33
Should I open an issue under the golang repo?

**Comment by aarzilli** [comment] 2023-08-10 19:38
If you want to do that you should set `config show-location-expr true`, see what `whatis variable` prints and crosscheck it with the disassembly.

**Comment by derekparker** [comment] 2023-08-10 19:49
The location expression is telling Delve to look for the value on the stack, but the variables don't get initialized until after the initial `ADD` instruction. Seems the compiler is reordering the instructions making Delve jump from line 10 to 13, which is that `ADD` instruction. At that point, neither variable is initialized, however Delve assumes they are in scope (current line is greater that the decl_line for both variables in the functions DIE). The issue comes down to the compiler not providing correct scope information to Delve. There's an [open issue](https://github.com/golang/go/issues/12899) to improve this in the compiler.

**Comment by yardenlaif** [comment] 2023-08-10 20:27
I see that the open issue is from 8 years ago but this only happens to me on arm and in go1.21

**Comment by derekparker** [comment] 2023-08-10 20:51
> I see that the open issue is from 8 years ago but this only happens to me on arm and in go1.21

Yeah, that's just a general ongoing issue for better variable scope representation from the compiler. It's manifested itself differently over the years.

However, I'm curious what the disassembly looks like on arm with go1.20. Perhaps the compiler didn't reorganize the instructions in the same way previously?

**Comment by aarzilli** [comment] 2023-08-11 06:58
#58813 is a similar issue on amd64.

**Comment by aarzilli** [comment] 2023-08-12 08:06
Closing, duplicate of https://github.com/golang/go/issues/58813

**Closed by aarzilli** 2023-08-12 08:06 UTC
Labels: kind/bug, area/proc, arch/arm64
