### ISSUE TITLE
dlv  hung when Sprintf nil

### ISSUE THREAD

**Issue by Ivan-Zhu** [go-delve/delve#1840] opened 2020-01-20 08:23 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
1.3.2
2. What version of Go are you using? (`go version`)?
1.13
3. What operating system and processor architecture are you using?
mac os 10.14.6
4. What did you do?

- source code (main.go):
`package main

import (
    "fmt"
    "time"
)

type Time struct {
    time.Time
}

func main(){
    var DeletionTimestamp *Time
    fmt.Sprintf("test dlv: %v", DeletionTimestamp)
    fmt.Printf("success\n")
}`

build:  go build -gcflags="all=-N -l" -o main main.go

run: ./main
output:
![image](https://user-images.githubusercontent.com/5468158/72710163-6d6f3700-3ba1-11ea-9216-dc6228913b6a.png)

debug:
![image](https://user-images.githubusercontent.com/5468158/72710007-123d4480-3ba1-11ea-9f26-59dcfdff1825.png)

 
5. What did you expect to see?
see "success" output when use dlv debug
6. What did you see instead?
![image](https://user-images.githubusercontent.com/5468158/72710005-10738100-3ba1-11ea-8793-f488a8e31d91.png)

**Comment by chainhelen** [comment] 2020-01-20 08:37
Duplicate of #852

**Closed** 2020-01-20 08:49 UTC
