### ISSUE TITLE
arm64 your operating system and architecture combination is not supported by delve

### ISSUE THREAD

**Issue by eaglemoor** [go-delve/delve#2303] opened 2021-01-16 10:03 UTC
1. What version of Go are you using? (`go version`)?
`go version go1.16beta1 darwin/arm64`
2. What operating system and processor architecture are you using?
```
Model Name:	MacBook Air
  Model Identifier:	MacBookAir10,1
  Chip:	Apple M1
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	16 GB
```
3. What did you do?
```
cd ~/go/src/github.com/go-delve/delve/cmd/dlv

git status
HEAD detached at v1.5.1

go build .
../../service/debugger/debugger.go:26:2: found packages native (nonative_darwin.go) and your_operating_system_and_architecture_combination_is_not_supported_by_delve (support_sentinel.go) in /Users/eaglemoor/go/src/github.com/go-delve/delve/pkg/proc/native
```

```
make install
Error executing go [list -mod=vendor ./...]
2021/01/16 13:05:32 exit status 1
exit status 1
make: *** [install] Error 1
eaglemoor@Aleksejs-MacBook-Air delve % go list -mod=vendor ./...
service/debugger/debugger.go:26:2: found packages native (nonative_darwin.go) and your_operating_system_and_architecture_combination_is_not_supported_by_delve (support_sentinel.go) in /Users/eaglemoor/go/src/github.com/go-delve/delve/pkg/proc/native
```

**Comment by aarzilli** [comment] 2021-01-16 13:17
Closing, duplicate of #2302

**Closed by aarzilli** 2021-01-16 13:17 UTC

**Comment by eaglemoor** [comment] 2021-01-16 17:14
@aarzilli I build v1.5.1. Not worked, pl read my message
