### ISSUE TITLE
DW_FORM_strx with no .debug_str_offsets section

### ISSUE THREAD

**Issue by Jasstkn** [go-delve/delve#3797] opened 2024-08-20 19:20 UTC
Minimal code to reproduce an issue: https://go.dev/play/p/mT1pjsWIx9x. The same issue happens when using this dependency:
```
helm.sh/helm/v3/pkg/cli/values
```

`go build` works normally with no errors.

1. What version of Delve are you using (`dlv version`)?
```sh
Delve Debugger
Version: 1.23.0
Build: $Id: e673f2da02185a1c2b6dea52842b0a8c7e7a03b9 $
```
2. What version of Go are you using? (`go version`)?
```
go version go1.23.0 darwin/arm64
```
3. What operating system and processor architecture are you using?
MacOS on ARM, issue started to be reproduced since MacOS 15 Beta(24A5327a).
4. What did you do?
run dlv debugger via VSCode and manually
5. What did you expect to see?
Debugger is working for my project. 
6. What did you see instead?
The following error:
```
2024-08-20T21:03:44+02:00 error layer=debugger error loading binary "/Users/mariiak/repos/mycli/__debug_bin2843838000": error reading debug_info: decoding dwarf section info at offset 0x942ab7: DW_FORM_strx with no .debug_str_offsets section
could not launch process: error reading debug_info: decoding dwarf section info at offset 0x942ab7: DW_FORM_strx with no .debug_str_offsets section
```
I wasn't able to dissect what exactly is causing the issue - any directions are appreciated!

I also found this issue with similar problem that is happening on MacOS 15 Beta https://github.com/mattn/go-sqlite3/issues/1269

**Comment by aarzilli** [comment] 2024-08-21 08:40
Can you upload a binary that shows this problem? You can do it by building with `go build -gcflags='all=-N -l'` and then verifying that it doesn't work by using `dlv exec executable_name`.

@cherrymui I think there might be new problems with the dsymutil of macOS 15, are you already aware?

**Comment by Jasstkn** [comment] 2024-08-21 09:12
Still produces the same error. Here is the binary.
[helloworld.zip](https://github.com/user-attachments/files/16689300/helloworld.zip)

**Comment by cherrymui** [comment] 2024-08-21 15:32
What is the C toolchain you're using, and what version? E.g. the output of `clang -v`, `ld -v`, and `dsymutil -v`? Thanks.

**Comment by Jasstkn** [comment] 2024-08-22 07:03
@cherrymui hi. here you go:
```sh
❯ clang -v
Apple clang version 16.0.0 (clang-1600.0.26.3)
Target: arm64-apple-darwin24.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

❯ ld -v
@(#)PROGRAM:ld PROJECT:ld-1115.7.3
BUILD 07:00:06 Aug 10 2024
configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
will use ld-classic for: armv6 armv7 armv7s i386 armv6m armv7k armv7m armv7em
LTO support using: LLVM version 16.0.0 (static support for 29, runtime is 29)
TAPI support using: Apple TAPI version 16.0.0 (tapi-1600.0.11.8)

❯ dsymutil -v
Apple LLVM version 16.0.0
   (clang-1600.0.26.3)Optimized build.
```

**Comment by AntonPieper** [comment] 2024-08-23 09:00
I have the same exact issue. Also running macOS 15.0 Beta (24A5327a). My clang, ld and dsymutil is also 16.0.0. I get the same `DW_FORM_strx with no .debug_str_offsets section` error when trying to debug a single file with a sqlite3 dependency.

**Comment by Jasstkn** [comment] 2024-08-27 13:51
Hello @cherrymui. Do you have any update on this issue? It impacts my ability to debug go code. If there any workarounds available, please advise 🙏🏻

**Comment by cherrymui** [comment] 2024-08-27 15:54
I don't think the Go toolchain generate `DW_FORM_strx`. So I guess the (new version of the) C toolchain starts to generate such entries, and Delve doesn't understand?

> DW_FORM_strx with no .debug_str_offsets section

This particular error looks like https://cs.opensource.google/go/go/+/master:src/debug/dwarf/entry.go;l=670 . Maybe Go's debug/dwarf package misses something?

Do the system `dwarfdump` and `lldb` accept the binary, or complain any malformed DWARF? You probably need to build with `-ldflags=-compressdwarf=0` for the Mac system tools to understand its DWARF.

**Comment by aarzilli** [comment] 2024-08-27 16:43
PS the fix for this is going to be 🤮

**Comment by cherrymui** [comment] 2024-08-27 17:21
Interesting. Could we have debug/dwarf understand __zdebug_str_off as __zdebug_str_offsets? (If it is not ambiguous?)

**Comment by aarzilli** [comment] 2024-08-27 17:39
@Jasstkn @AntonPieper can one of you test if #3799 fixes the problem?

@cherrymui If the fix works I'll make something for the standard library, although it seems to me that this belongs more to debug/macho.(*File).DWARF.

**Comment by Jasstkn** [comment] 2024-08-27 18:27
> @Jasstkn @AntonPieper can one of you test if #3799 fixes the problem?
> 
> @cherrymui If the fix works I'll make something for the standard library, although it seems to me that this belongs more to debug/macho.(*File).DWARF.

I build `dlv` from your commit and it looks like I can no longer reproduce the issue - the same binary as I attached above started to work with dlv.
```
./dlv version
Delve Debugger
Version: 1.23.0
Build: 1ac48d1051db06b1c5897eb8898033a0ed0717df

./dlv exec ../../../src/jasstkn/hello-world/helloworld
Type 'help' for list of commands.
(dlv)
```

**Comment by Psykepro** [comment] 2024-08-29 13:32
Guys I'm with M3 Max chip and receive the same errors by trying to run the following code:
`package main

import (
	"log/slog"

	"github.com/ethereum/go-ethereum/core/types"
)

func main() {
	block := types.Block{}
	slog.Info("Block", "content", block)
}
`
Just by importing anything from go-ethereum I receive the following error on trying to debug with dlv:
`Failed to launch: could not launch process: error reading debug_info: decoding dwarf section info at offset 0x98aac: DW_FORM_strx with no .debug_str_offsets section`

Here are which version I'm using:
GoLang - 1.23
dlv - 1.23
require github.com/ethereum/go-ethereum v1.13.1

Please help me fix this.

**Comment by cpeliciari** [comment] 2024-09-02 01:58
I'm even using macOS 15.1 Beta, I reinstalled the system and the problem persists.
I suggest using devcontainer for development until this is fixed.

```
API server listening at: 127.0.0.1:54312
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1600.0.36.3
 for arm64.
Got a connection, launched process /Users/peliciari/Library/Caches/JetBrains/GoLand2024.2/tmp/GoLand/___go_build_github_com_flamingotv_broker (pid = 18073).
2024-09-01T22:49:15-03:00 error layer=debugger error loading binary "/Users/peliciari/Library/Caches/JetBrains/GoLand2024.2/tmp/GoLand/___go_build_github_com_flamingotv_broker": error reading debug_info: decoding dwarf section info at offset 0x50d5af: DW_FORM_strx with no .debug_str_offsets section
Exiting.
could not launch process: error reading debug_info: decoding dwarf section info at offset 0x50d5af: DW_FORM_strx with no .debug_str_offsets section

```

**Comment by cpeliciari** [comment] 2024-09-02 02:26
@aarzilli I tested your solution but it didn't work

**Comment by aarzilli** [comment] 2024-09-02 05:26
@cpeliciari GoLand uses it's own copy of dlv, you have to replace it, it's inside the GoLand directory somewhere.

**Comment by Psykepro** [comment] 2024-09-02 09:20
@aarzilli your fix works. Sorry for not testing it before :D I guess this fix will be released with the next version?

**Comment by cpeliciari** [comment] 2024-09-02 12:27
**Details**: 

I've pulled the branch from [aarzilli/delve/tree/fix3797](https://github.com/aarzilli/delve/tree/fix3797) and ran the following command:

```bash
go build -o /Users/peliciari/Applications/GoLand.app/Contents/plugins/go-plugin/lib/dlv/macarm/dlv cmd/dlv
```

However, the debugging functionality is not working as expected. I'm using Go 1.23.0 and MacOS 15.1 Beta. Could you please provide guidance on what might be going wrong or if there's a specific configuration needed to make this work correctly?

![image](https://github.com/user-attachments/assets/a9aa2d65-46fe-4e35-858b-60f9a6656b34)

**Comment by cpeliciari** [comment] 2024-09-02 12:40
@aarzilli Apparently, when starting the debug session, I need to manually resume it through GoLand, whereas before it would just go straight to the breakpoint.

![Screenshot 2024-09-02 at 09 35 57](https://github.com/user-attachments/assets/2484a518-feba-4c38-b6dc-5af3091580ae)

![Screenshot 2024-09-02 at 09 37 22](https://github.com/user-attachments/assets/95834613-fccc-49f1-a9c9-7c64d1be3da4)

**Closed** 2024-09-03 17:39 UTC
Labels: kind/bug, os/macOS, area/proc, kind/upstream

**Comment by siennathesane** [comment] 2024-09-18 19:04
For Goland users, here's the quick fix:

```sh
GOBIN=/Users/$USER/Applications/GoLand.app/Contents/plugins/go-plugin/lib/dlv/macarm go install github.com/go-delve/delve/cmd/dlv@b9fadba
```

![image](https://github.com/user-attachments/assets/c4cc8122-bd54-450e-a06e-492073a966d6)

![image](https://github.com/user-attachments/assets/cd9bb989-481b-4982-8e7c-75e1f3d83b62)

**Comment by nadeemc** [comment] 2024-09-19 05:36
> For Goland users, here's the quick fix:
> 
> ```shell
> GOBIN=/Users/$USER/Applications/GoLand.app/Contents/plugins/go-plugin/lib/dlv/macarm go install github.com/go-delve/delve/cmd/dlv@b9fadba
> ```

Thank you for sharing! For those having the application installed for all users, you may need to run this instead:

```shell
GOBIN=/Applications/GoLand.app/Contents/plugins/go-plugin/lib/dlv/macarm go install github.com/go-delve/delve/cmd/dlv@master
```

**Comment by ubeyali** [comment] 2024-09-19 11:17
> > For Goland users, here's the quick fix:
> > ```shell
> > GOBIN=/Users/$USER/Applications/GoLand.app/Contents/plugins/go-plugin/lib/dlv/macarm go install github.com/go-delve/delve/cmd/dlv@b9fadba
> > ```
> 
> Thank you for sharing! For those having the application installed for all users, you may need to run this instead:
> 
> ```shell
> GOBIN=/Applications/GoLand.app/Contents/plugins/go-plugin/lib/dlv/macarm go install github.com/go-delve/delve/cmd/dlv@master
> ```

That works for me. Thanks!

**Comment by shawnzxx** [comment] 2024-09-23 06:07
Works for me, apparently Goland folder macarm don't have dlv file, I don't know why suddenly removed after I upgrade the OS. 
I manually copied from `/Users/shawnzhang/go/bin/dlv` back to amcarm folder, solved the IDE debugger.

**Comment by s0xzwasd** [comment] 2024-09-23 09:21
GoLand team released 2024.2.2.1 version of GoLand that includes the latest Delve version with the fix. You may consider updating the IDE instead of replacing Delve binary manually.

**Comment by TelenLiu** [comment] 2024-10-07 12:46
GoLand team released 2024.2.3， use  （https://github.com/djimenez/iconv-go | github.com/faiface/beep | github.com/shirou/gopsutil/v3）will error like：

Warning: no debug info found, some functionality will be missing such as stack traces and variable evaluation.
Exiting.
could not launch process: could not read debug info (decoding dwarf section info at offset 0x0: too short) and could not read go symbol table (could not find rodata struct member)

**Comment by GrisaiaEvy** [comment] 2024-10-09 04:27
> MacOS 15， GoLand team released 2024.2.3， use （https://github.com/djimenez/iconv-go | https://github.com/faiface/beep | [https://github.com/shirou/gopsutil/v3）will](https://github.com/shirou/gopsutil/v3%EF%BC%89will) error like：
> 
> Warning: no debug info found, some functionality will be missing such as stack traces and variable evaluation. Exiting. could not launch process: could not read debug info (decoding dwarf section info at offset 0x0: too short) and could not read go symbol table (could not find rodata struct member)

Have you solved this problem?

**Comment by s0xzwasd** [comment] 2024-10-09 06:05
> could not find rodata struct member

can you reproduce it with 1.23 version of Go?

**Comment by akbarchandanianz** [comment] 2024-10-15 07:07
> MacOS 15， GoLand team released 2024.2.3， use （https://github.com/djimenez/iconv-go | https://github.com/faiface/beep | [https://github.com/shirou/gopsutil/v3）will](https://github.com/shirou/gopsutil/v3%EF%BC%89will) error like：
> 
> Warning: no debug info found, some functionality will be missing such as stack traces and variable evaluation. Exiting. could not launch process: could not read debug info (decoding dwarf section info at offset 0x0: too short) and could not read go symbol table (could not find rodata struct member)

Have you able to resolve this issue?

**Comment by FatIgor** [comment] 2024-10-17 17:40
I get much the same as above, have been since I started learning go for a side project.

API server listening at: 127.0.0.1:49730
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1600.0.36.3
 for arm64.
Got a connection, launched process /Users/fatigor/Library/Caches/JetBrains/GoLand2024.2/tmp/GoLand/___1go_build_Tree_Demo__1_ (pid = 2688).
Warning: no debug info found, some functionality will be missing such as stack traces and variable evaluation.
Exiting.
could not launch process: could not read debug info (decoding dwarf section info at offset 0x0: too short) and could not read go symbol table (could not find rodata struct member)

**Comment by taitelman** [comment] 2024-10-21 11:12
I got a problem:
my GoLand is installed in ```/Applications/GoLand.app/Contents/plugins/go/lib/dlv/macarm/```
and 
```
$ sudo GOBIN=/Applications/GoLand.app/Contents/plugins/go/lib/dlv/macarm/  go install github.com/go-delve/delve/cmd/dlv@master
Password:
github.com/go-delve/delve/cmd/dlv: go install github.com/go-delve/delve/cmd/dlv: copying /tmp/go-build3874712439/b001/exe/a.out: open /Applications/GoLand.app/Contents/plugins/go/lib/dlv/macarm/dlv: operation not permitted
```
any workaround ?

**Comment by yuyinweiliao** [comment] 2024-11-04 02:37
> > For Goland users, here's the quick fix:
> > ```shell
> > GOBIN=/Users/$USER/Applications/GoLand.app/Contents/plugins/go-plugin/lib/dlv/macarm go install github.com/go-delve/delve/cmd/dlv@b9fadba
> > ```
> 
> Thank you for sharing! For those having the application installed for all users, you may need to run this instead:
> 
> ```shell
> GOBIN=/Applications/GoLand.app/Contents/plugins/go-plugin/lib/dlv/macarm go install github.com/go-delve/delve/cmd/dlv@master
> ```

Thanks

**Comment by hoosssein** [comment] 2024-11-11 04:41
> > For Goland users, here's the quick fix:
> > ```shell
> > GOBIN=/Users/$USER/Applications/GoLand.app/Contents/plugins/go-plugin/lib/dlv/macarm go install github.com/go-delve/delve/cmd/dlv@b9fadba
> > ```
> 
> Thank you for sharing! For those having the application installed for all users, you may need to run this instead:
> 
> ```shell
> GOBIN=/Applications/GoLand.app/Contents/plugins/go-plugin/lib/dlv/macarm go install github.com/go-delve/delve/cmd/dlv@master
> ```

For Intel-based Mac computers (x86 architecture), you can use the following command:

```shell
GOBIN=/Applications/GoLand.app/Contents/plugins/go-plugin/lib/dlv/mac go install github.com/go-delve/delve/cmd/dlv@master
```
