### ISSUE TITLE
Can't debugging on macOS Sequoia with intel mac

### ISSUE THREAD

**Issue by sonientaegi** [go-delve/delve#3813] opened 2024-09-20 00:04 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)? 1.23.0
2. What version of Go are you using? (`go version`)? 1.22.5
3. What operating system and processor architecture are you using? macOS 15, darwin/amd64
4. What did you do? #3797
5. What did you expect to see? #3797
6. What did you see instead? #3797

I have both macarm and mactel. Thankfully, I could launch debugger on my macarm following #3797. And I do the same on my mactel but it doesn't work at all as the very first macarm did after installing Sequoia. Below is the error message.

> Warning: no debug info found, some functionality will be missing such as stack traces and variable evaluation.
> could not launch process: could not read debug info (decoding dwarf section info at offset 0x0: too short) and could not read go symbol table (could not find rodata struct member)
> 

Could anyone plz check the issue on mac with intel?

**Comment by sonientaegi** [comment] 2024-09-20 01:06
Also, I have updated xcode-tools. So those toolchains are up-to-dated.

clang : 16.0.0
ld : 16.0.0
dsymutil : 16.0.0

**Comment by aarzilli** [comment] 2024-09-20 04:42
Duplicate of #3812

**Closed by aarzilli** 2024-09-20 04:42 UTC

**Comment by sonientaegi** [comment] 2024-09-20 05:20
@aarzilli 
I made some mistake. I built the image with go 1.22 and debugging section was not generated. After building with go 1.23 I could find __zdebug* sections. Thanks for helping.
