### ISSUE TITLE
The version of golang in the go.mod is error

### ISSUE THREAD

**Issue by xieyuanhuata** [go-delve/delve#1813] opened 2020-01-07 03:16 UTC
Go Modules is a feature since go1.11 , but :
module github.com/go-delve/delve

go 1.10

**Comment by aarzilli** [comment] 2020-01-07 07:54
I don't see why this would be a problem.

**Comment by chainhelen** [comment] 2020-01-07 08:21
@xieyuanhuata 
You should follow the [rule](https://github.com/go-delve/delve/blob/master/CONTRIBUTING.md#filing-issues) for resolving issues quickly..

**Comment by derekparker** [comment] 2020-01-13 19:15
Technically not a bug, however in our CI we only test back to Go 1.11. I don't think it would hurt anything to bump the required Go version to 1.11.

**Closed** 2020-01-14 10:07 UTC
