### ISSUE TITLE
undefined: archInst on Android termux

### ISSUE THREAD

**Issue by vanloswang** [go-delve/delve#1508] opened 2019-03-11 12:58 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
latest
2. What version of Go are you using? (`go version`)?
go version
go version go1.12 android/arm64
3. What operating system and  architecture are you using?
Android/termux arm64
4. What did you do?
go get -v -u github.com/derekparker/delve/cmd/dlv
5. What did you expect to see?
no such error reported.
6. What did you see instead?
```bash
go get -v -u github.com/derekparker/delve/cmd/dlv
github.com/derekparker/delve (download)
github.com/go-delve/delve (download)
github.com/go-delve/delve/pkg/proc
# github.com/go-delve/delve/pkg/proc
gopath/src/github.com/go-delve/delve/pkg/proc/disasm.go:12:14: undefined: archInst
```

**Comment by aarzilli** [comment] 2019-03-11 16:34
ARM is not supported, duplicate of #328

**Closed by aarzilli** 2019-03-11 16:34 UTC
