### ISSUE TITLE
Failure to read stdin on programs run under dlv.

### ISSUE THREAD

**Issue by ianbruene** [go-delve/delve#1982] opened 2020-04-02 16:40 UTC
dlv version: 1.4.0

Go version: go1.14 linux/amd64

OS, CPU: Pop!_os 19.10, i7-9750H

I maintain a library for programs that run REPL command lines. When a program that uses it is run under dlv any attempt to read from stdin fails with EOF. To isolate whether this was my code, chzyer/readline's code, or a fault in dlv, I assembled a minimal test program to read from stdin. This program also fails with EOF when run under dlv.

I am not sure if this error is in dlv, or if it is a gap in the documentation and there is a way to hook stdin to a real terminal.

Test Program:

```golang
package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Println("Starting......")
	data := [1]byte{0}
	count, err := os.Stdin.Read(data[:])
	fmt.Println("Read:", data, count, err)
}
```

**Comment by chainhelen** [comment] 2020-04-03 07:45
Need to use `--headless`  mode

Run server and client respectively on two terminals.   
```
// server
dlv debug main.go --headless --listen 127.0.0.1:3100

// client 
 dlv connect 127.0.1:3100 
```

**Comment by derekparker** [comment] 2020-04-03 17:48
Possible duplicate of https://github.com/go-delve/delve/issues/1964 -- however as @chainhelen mentioned you can use `--headless` mode to accomplish what you want for now.

**Closed by derekparker** 2020-04-03 17:48 UTC
