### ISSUE TITLE
Corrupted stacktraces on darwin/arm64 during panic

### ISSUE THREAD

**Issue by thedaneeffect** [go-delve/delve#2894] opened 2022-02-05 19:35 UTC
I'm unable to debug applications on my platform. I tried to gather as much information as I could.

1. What version of Delve are you using (`dlv version`)?

<img width="443" alt="Screen Shot 2022-02-05 at 11 46 54 AM" src="https://user-images.githubusercontent.com/3468354/152655683-1b8597fb-461b-41dc-b47f-337804613190.png">

2. What version of Go are you using? (`go version`)?

<img width="270" alt="Screen Shot 2022-02-05 at 11 50 10 AM" src="https://user-images.githubusercontent.com/3468354/152655693-165e572e-19ad-417e-ad3b-9d1493255318.png">

3. What operating system and processor architecture are you using?

<img width="216" alt="Screen Shot 2022-02-05 at 11 46 08 AM" src="https://user-images.githubusercontent.com/3468354/152655636-dd5f9e3c-22df-4390-a491-edc252bf2a7b.png">

4. What did you do? **Attempted to debug an application**

5. What did you expect to see? **Debug information**

6. What did you see instead? **Erroneous output**

https://gist.github.com/thedaneeffect/4cc3a33d103db16a2222f68dd41feae6

dlv.log: https://gist.github.com/thedaneeffect/4772c491ec02e83a8d17216e57654551
out.log: https://gist.github.com/thedaneeffect/d2a659b9b7552e501c8a72535b7105e8

Commands used to generate log files:
```
~/go/bin/dlv --log --log-output debugger,minidump,gdbwire,lldbout,debuglineerr,rpc,dap,fncall --log-dest dlv.log --allow-non-terminal-interactive=true exec ___go_build_rs_cmd_test >out.log
(dlv) continue
(dlv) stack
(dlv) exit
```

<img width="1240" alt="Screen Shot 2022-02-05 at 11 37 05 AM" src="https://user-images.githubusercontent.com/3468354/152655723-5516a745-7fef-40e2-b1a1-5646af5bc26a.png">

If helpful, here is my default build configuration:

<img width="381" alt="Screen Shot 2022-02-05 at 11 53 41 AM" src="https://user-images.githubusercontent.com/3468354/152655814-342f4add-af4d-4c80-ac32-123d34cbc524.png">

**Comment by aarzilli** [comment] 2022-02-06 13:06
It would help if you could upload the binary ___go_build_rs_cmd_test that causes the problem somewhere.

**Comment by thedaneeffect** [comment] 2022-02-06 18:34
Hi, sorry @aarzilli Here is a snippet of the code to reproduce the issue. It is using the GORM library.

```go
package main

import (
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
)

type Tag struct {
	Name      string `gorm:"primarykey"`
	OwnerID   uint
	OwnerType string
}

type Foo struct {
	// ! Adding an ID solves the panic.
	// ID uint
	TagID uint
	Tag   Tag `gorm:"polymorphic:Owner;polymorphicValue:foo;not null"`
}

func main() {
	if db, err := gorm.Open(mysql.Open("root:root@tcp(localhost:3306)/test?parseTime=true"), &gorm.Config{}); err != nil {
		panic(err)
	} else if err = db.AutoMigrate(&Tag{}, &Foo{}); err != nil {
		panic(err)
	}
}

```

**Comment by thedaneeffect** [comment] 2022-02-06 18:41
Here is a build connecting to `root:root@tcp(localhost:3306)/test`

[test.tar.gz](https://github.com/go-delve/delve/files/8010906/test.tar.gz)

**Comment by aarzilli** [comment] 2022-02-09 08:32
I'm trying to look into this bug report but there is some confusion. You say you are using go1.17.6 and the log you posted reflects this, but the binary you posted is built with go1.18-d588f48770.

**Comment by thedaneeffect** [comment] 2022-02-10 06:07
> I'm trying to look into this bug report but there is some confusion. You say you are using go1.17.6 and the log you posted reflects this, but the binary you posted is built with go1.18-d588f48770.

Oops, I was playing with generics. Here it is built with go1.17.6.

[test.tar.gz](https://github.com/go-delve/delve/files/8038529/test.tar.gz)

**Comment by aarzilli** [comment] 2022-02-16 15:49
It doesn't look like this executable is lining up with the log either, instruction addresses don't match.

**Comment by nelegatti** [comment] 2022-03-04 16:38
Hey ! I'm having the same issue trying to debug golang projects using VS Code on my M1 Pro. 
This is my current configuration:
```
user$ go version
go version go1.17.8 darwin/arm64
user$ dlv version
Delve Debugger
Version: 1.8.1
Build: $Id: d85f1f6b736db99a1c239c34fd4a081dcff08a3c $
user$ code -v
1.65.0
b5205cc8eb4fbaa726835538cd82372cc0222d43
arm64
```

I'm getting the following error:
`Failed to launch: could not launch process: can not run under Rosetta, check that the installed build of Go is right for your CPU architecture
`
Any ideas?

**Comment by aarzilli** [comment] 2022-03-04 21:28
@nelegatti completely different problem, see #2604.

**Comment by nelegatti** [comment] 2022-03-04 21:32
> @nelegatti completely different problem, see #2604.

I'll do it, thanks!!!

**Comment by keep-learn** [comment] 2022-03-11 07:41
I have the same problem with @thedaneeffect  .
When is this issue expected to be fixed ?  @aarzilli 
thanks ~

**Comment by aarzilli** [comment] 2022-03-11 08:16
To be investigated this needs either logs paired with the binary that produced them or, **much preferrably**, a standalone reproducer that doesn't require mysql and gorm.

**Comment by keep-learn** [comment] 2022-03-11 09:19
1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.8.2
Build: $Id: dbb493ec14d1e7753504d016b1e1ef1665b75b16 $


2. What version of Go are you using? (`go version`)?
go version go1.17.8 darwin/arm64

3. What operating system and processor architecture are you using?
<img width="360" alt="image" src="https://user-images.githubusercontent.com/9759278/157837474-4a2eff21-6b70-4056-aab9-7403ac5ad6d4.png">

4. What did you do?
Attempted to debug an application

5. What did you expect to see?
Debug information

6. What did you see instead?
Erroneous output
<img width="600" alt="image" src="https://user-images.githubusercontent.com/9759278/157837773-0ffcad5e-25b1-4ff4-bd37-c0b01251266b.png">

this compiled file
[test.zip](https://github.com/go-delve/delve/files/8230629/test.zip)


@aarzilli  The above is my operation ， help me see thanks

**Comment by aarzilli** [comment] 2022-03-11 10:40
@keep-learn that's a different problem, please open a new issue and post the logs with `--log --log-output=gdbserial`. You should also try reinstalling xcode's command line tools, it is very likely that this is just a problem with your setup.

**Comment by keep-learn** [comment] 2022-03-11 12:57
Thank you very much, after updating xcode the problem is solved! The reason is because I use mac's migration assistant from the old intel computer to the m1 computer , you are very excellent 👍🏻  @aarzilli

**Comment by aarzilli** [comment] 2022-05-04 14:34
Closing, no feedback.

**Closed by aarzilli** 2022-05-04 14:34 UTC
Labels: kind/bug, os/macOS, kind/needs more info, area/proc/gdbserial, arch/arm64
