### ISSUE TITLE
Need to restart the process multiple times before the debug session is started

### ISSUE THREAD

**Issue by lowjoel** [go-delve/delve#684] opened 2016-12-16 01:57 UTC
When starting a debug session, I get this:

```
dlv-edge --log debug
2016/12/16 09:41:24 server.go:71: Using API v1
2016/12/16 09:41:24 debugger.go:65: launching process with args: [/../debug]
Type 'help' for list of commands.
(dlv) c
2016/12/16 09:41:26 debugger.go:397: continuing
Process 21587 has exited with status -1
(dlv) restart
Process restarted with PID 21601
(dlv) c
2016/12/16 09:41:30 debugger.go:397: continuing
Process 21601 has exited with status -1
(dlv) restart
Process restarted with PID 21609
(dlv) c
2016/12/16 09:41:32 debugger.go:397: continuing
Process 21609 has exited with status -1
(dlv) restart
Process restarted with PID 21619
(dlv) c
2016/12/16 09:41:35 debugger.go:397: continuing
{debug session commences}
```

1. What version of Delve are you using (`dlv version`)? I built from master, 6bff4d19706b46b7bd350212048e4a140caad271.
2. What version of Go are you using? (`go version`)? go version go1.7.4 darwin/amd64
3. What operating system and processor architecture are you using? Mac OS El Capitan 10.11.6
4. What did you do? `dlv debug`
5. What did you expect to see? The debuggee (?) process should be started immediately
6. What did you see instead? I had to restart the debug session multiple times before the debug session actually proceeded.

When running this via the Intellij plugin, I do get notified of a panic:

```
API server listening at: 127.0.0.1:50889
2016/12/16 09:27:00 debugger.go:397: continuing
function symbol table not sorted by program counter: 0x40f6010 type..hash.net/http.http2Setting > 0x6a0 
	0x4002d70 go.buildid
{many many other lines involving method IPs omitted}
	0x40f6010 type..hash.net/http.http2Setting
fatal error: invalid runtime symbol table
```

I'm not sure if it's the same problem. I've already removed the `pkg` directory, ran `go clean`... A simple toy program works fine. I'm out of ideas. Any suggestions?

**Comment by aarzilli** [comment] 2016-12-22 11:03
Probably a duplicate of #294 manifesting in a different way.

**Comment by joelburget** [comment] 2017-01-23 15:56
Same here, debugging [geth](https://github.com/ethereum/go-ethereum):

```
> dlv debug ./cmd/geth
Type 'help' for list of commands.
(dlv) c
Process 24200 has exited with status -1
(dlv) restart
Process restarted with PID 24265
(dlv) c
Process 24265 has exited with status -1
(dlv) restart
Process restarted with PID 24328
(dlv) c
panic: interface conversion: interface is *core.VMEnv, not vm.Environment
fatal error: panic on system stack
> [unrecovered-panic] runtime.startpanic() /usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/panic.go:543 (hits goroutine(0):1 total:1) (PC: 0x4043f70)
   538:		}
   539:		return nil
   540:	}
   541:
   542:	//go:nosplit
=> 543:	func startpanic() {
   544:		systemstack(startpanic_m)
   545:	}
   546:
   547:	//go:nosplit
   548:	func dopanic(unused int) {
(dlv) bt
0  0x0000000004043f70 in runtime.startpanic
   at /usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/panic.go:543
1  0x00000000040440b3 in runtime.throw
   at /usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/panic.go:565
2  0x0000000004043e99 in runtime.gopanic
   at /usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/panic.go:389
3  0x0000000004025888 in runtime.additab
   at /usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/iface.go:131
4  0x0000000004025c79 in runtime.itabsinit
   at /usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/iface.go:149
5  0x00000000040468a9 in runtime.schedinit
   at /usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/proc.go:444
6  0x0000000004072dda in runtime.rt0_go
   at /usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/asm_amd64.s:145
(dlv) restart
Process restarted with PID 24454
(dlv) c
I0123 10:53:48.462819 cmd/utils/flags.go:666] You're one of the lucky few that will try out the JIT VM (random). If you get a consensus failure please be so kind to report this incident with the block hash that failed. You can switch to the regular VM by setting --jitvm=false
I0123 10:53:48.462919 ethdb/database.go:81] Allotted 128MB cache and 1024 file handles to /Users/joel/Library/Ethereum/chaindata
I0123 10:53:48.494294 ethdb/database.go:174] closed db:/Users/joel/Library/Ethereum/chaindata
I0123 10:53:48.494759 node/node.go:175] instance: Geth/v1.5.0-unstable/darwin/go1.7.4
I0123 10:53:48.494785 ethdb/database.go:81] Allotted 128MB cache and 1024 file handles to /Users/joel/Library/Ethereum/chaindata
I0123 10:53:48.535676 eth/backend.go:177] Protocol Versions: [63 62], Network Id: 1
I0123 10:53:48.536981 core/blockchain.go:221] Last header: #35 [7dea5697…] TD=4604992
I0123 10:53:48.536997 core/blockchain.go:222] Last block: #35 [7dea5697…] TD=4604992
I0123 10:53:48.537002 core/blockchain.go:223] Fast block: #35 [7dea5697…] TD=4604992
I0123 10:53:48.537604 handler.go:513] start of handleLogCommands loop
I0123 10:53:48.537834 p2p/server.go:328] Starting Server
I0123 10:53:50.654663 p2p/discover/udp.go:217] Listening, enode://3efabe88746b6931ab7fcd1b147529de7b42e8c05b6852e59a851282cdcc7ba4c4a207ef8bfbddea6bf6bc7130eaf6981783e33840c49e08b17e9049b7ad6bb9@[::]:40401
I0123 10:53:50.654850 p2p/server.go:582] Listening on [::]:40401
I0123 10:53:50.656198 node/node.go:340] IPC endpoint opened: /Users/joel/Library/Ethereum/geth.ipc
```

**Comment by joelburget** [comment] 2017-01-23 15:58
Also:
* macOS Sierra 10.12.2
* Delve
  - Version: 0.12.1
  - Build: d89d115ef9efb3acdb3a1052ac058b79f36a4940

**Comment by derekparker** [comment] 2019-07-11 22:08
Closing, this should be solved now.

**Closed by derekparker** 2019-07-11 22:08 UTC
Labels: area/proc, help wanted, kind/bug, os/OSX
