### ISSUE TITLE
print supports out hex instead of decimal

### ISSUE THREAD

**Issue by jinleileiking** [go-delve/delve#1563] opened 2019-05-30 06:43 UTC
1. What version of Delve are you using (`dlv version`)?
Delve Debugger                                                                                                  │
Version: 1.2.0                                                                                                  │
Build: $Id: 068e2451004e95d0b042e5257e34f0f08ce01466 $

2. What version of Go are you using? (`go version`)?
go version go1.12 linux/amd64                                                                                   │

3. What operating system and processor architecture are you using?
linux

4. What did you do?
p x ( x is []byte{})

5. What did you expect to see?

I want to see the hex, `0x11 0x22`

6. What did you see instead?

I see the decimal  `17 34 ...`

**Comment by jinleileiking** [comment] 2019-05-30 06:44
https://github.com/go-delve/delve/issues/1038

**Comment by jinleileiking** [comment] 2019-05-30 06:46
https://github.com/go-delve/delve/blob/master/Documentation/cli/expr.md

**Comment by derekparker** [comment] 2019-05-30 15:12
Closing as dupe of #1038. Also, there is a PR for this that I've been sitting on for quite some time: https://github.com/go-delve/delve/pull/1059. Perhaps it's time I get around to it.

**Closed by derekparker** 2019-05-30 15:12 UTC
