### ISSUE TITLE
could not launch process: can not run under Rosetta, check that the installed build of Go is right for your CPU architecture

### ISSUE THREAD

**Issue by golangav** [go-delve/delve#2908] opened 2022-02-15 06:39 UTC
![image](https://user-images.githubusercontent.com/21213494/154006574-90e3324d-d1b1-4607-b3f9-0e5efe195912.png)

**Comment by aarzilli** [comment] 2022-02-15 08:28
Closing, duplicate of #2604.

**Closed by aarzilli** 2022-02-15 08:28 UTC
