### ISSUE TITLE
Cannot set breakpoints with GOFLAGS=-trimpath

### ISSUE THREAD

**Issue by zimmski** [go-delve/delve#2297] opened 2021-01-12 13:14 UTC
1. What version of Delve are you using (`dlv version`)?
1.5.1

2. What version of Go are you using? (`go version`)?
1.15.6

3. What operating system and processor architecture are you using?
linux/amd64

4. What did you do?
- a. Started Delve directly in the console with GOFLAGS=-trimpath
- a. Started VS.code with GOFLAGS=-trimpath
- b. Set a breakpoint
- c. Run program

5. What did you expect to see?

That the program stops at the breakpoint.

6. What did you see instead?

That the program did not stop at the breakpoint.

---

Our solution is right now to simple use Delve/VS.code without "-trimpath". However, all other programs and the environment still uses that option which is vital.

**Comment by krobelus** [comment] 2021-01-12 15:51
Reproducer:
```
$ mkdir src; cat > src/main.go << EOF
package main

func main() {
	println(123)
}
EOF
$ GOFLAGS=-trimpath dlv debug src/main.go
Type 'help' for list of commands.
(dlv) break src/main.go:4
Command failed: location "src/main.go:4 not found
````

Curiously, it works for Go files in the current directory.

**Comment by aarzilli** [comment] 2021-01-12 18:32
The reproducer is working as intended: you removed src from the path, so dlv doesn't know about the src directory. Delve itself provides substitute path, regarding VSCode this is a VSCode bug that is being worked on.

**Comment by zimmski** [comment] 2021-01-12 21:01
Thanks for taking a look. Can you post the VS.code issue so people who find this issue can give their +1?

**Comment by krobelus** [comment] 2021-01-12 21:56
I believe the VSCode issue is https://github.com/golang/vscode-go/issues/45.

The substitute-path works nicely for the `dlv` case, for example, for a file like `src/foo/bar.go` in the package `foo` I can use
`config substitute-path foo src/foo`.

**Comment by aarzilli** [comment] 2021-01-13 12:04
That's the issue, closing this one.

**Closed by aarzilli** 2021-01-13 12:04 UTC
