### ISSUE TITLE
Delve crashes when setting breakpoint in VSCode

### ISSUE THREAD

**Issue by kilgaloon** [go-delve/delve#2780] opened 2021-11-07 19:06 UTC
1. What version of Delve are you using (`dlv version`)? 1.7.2
2. What version of Go are you using? (`go version`)? 1.17.1
3. What operating system and processor architecture are you using? Ubuntu x86_64
4. What did you do? Set breakpoint in VSCode
5. What did you expect to see? Program running as expected
6. What did you see instead? Error log in debug console

Error:
```
panic: runtime error: slice bounds out of range [54853632:47488]

goroutine 54 [running]:
debug/dwarf.(*Data).dwarf2Ranges(0xc001866600, 0xf6d6, 0x8, 0x7, {0x0, 0xc000e09a38, 0x615238})
	/usr/local/go/src/debug/dwarf/entry.go:1105 +0x2b9
debug/dwarf.(*Data).Ranges(0xc001866600, 0xc002bb5350)
	/usr/local/go/src/debug/dwarf/entry.go:1067 +0x511
github.com/go-delve/delve/pkg/dwarf/godwarf.(*Tree).resolveRanges(0xc002bc20c0, 0x0, 0x7fdd7825b000)
	/home/strahinja/go/pkg/mod/github.com/go-delve/delve@v1.7.2/pkg/dwarf/godwarf/tree.go:131 +0x4c
github.com/go-delve/delve/pkg/dwarf/godwarf.(*Tree).resolveRanges(0xc002bc2060, 0xf6d1, 0x7fdd7825b000)
	/home/strahinja/go/pkg/mod/github.com/go-delve/delve@v1.7.2/pkg/dwarf/godwarf/tree.go:142 +0x16d
github.com/go-delve/delve/pkg/dwarf/godwarf.LoadTree(0x2a28060, 0xc001866600, 0xc000e09c6c)
	/home/strahinja/go/pkg/mod/github.com/go-delve/delve@v1.7.2/pkg/dwarf/godwarf/tree.go:84 +0x13a
github.com/go-delve/delve/pkg/proc.(*Image).getDwarfTree(0xc0001982a0, 0xf6d1)
	/home/strahinja/go/pkg/mod/github.com/go-delve/delve@v1.7.2/pkg/proc/bininfo.go:813 +0xa5
github.com/go-delve/delve/pkg/proc.(*BinaryInfo).loadDebugInfoMaps(0xc000236780, 0xc0001982a0, {0xc003460000, 0x19bd68, 0x19bd68}, {0xc002e78000, 0x47e40, 0x47e40}, 0xc002dea630, 0x0)
	/home/strahinja/go/pkg/mod/github.com/go-delve/delve@v1.7.2/pkg/proc/bininfo.go:1830 +0x1145
created by github.com/go-delve/delve/pkg/proc.loadBinaryInfoElf
	/home/strahinja/go/pkg/mod/github.com/go-delve/delve@v1.7.2/pkg/proc/bininfo.go:1249 +0x6df
```

**Comment by aarzilli** [comment] 2021-11-08 07:48
Duplicate of #2719

**Closed by aarzilli** 2021-11-08 07:48 UTC
