### ISSUE TITLE
RLIMIT_MEMLOCK is set to zero

### ISSUE THREAD

**Issue by firelizzard18** [go-delve/delve#3517] opened 2023-10-01 04:17 UTC
1. What version of Delve are you using (`dlv version`)?
   - 1.21.0 fec0d226b2c2cce1567d5f59169660cf61dc1efe
3. What version of Go are you using? (`go version`)?
   - go1.21.1 linux/amd64
4. What operating system and processor architecture are you using?
   - Gentoo, Intel
5. What did you do?
   - `dlv debug ./my/program`
6. What did you expect to see?
   - Running with delve (without breakpoints) behaves the same as running without
7. What did you see instead?
   - It works when run normally but fails when run with delve

When I run my program with delve, RLIMIT_MEMLOCK is set to zero, which causes mlock to fail. With the following code:

	var l syscall.Rlimit
	must(syscall.Getrlimit(unix.RLIMIT_MEMLOCK, &l))
	fmt.Println("memlock:", l.Cur, l.Max)

When I run normally, it prints out the expected value (the same number as `ulimit -l`, corrected for units). When I run with delve, it prints out `memlock: 0 0`.

**Comment by aarzilli** [comment] 2023-10-01 05:39
Duplicate of #3490

**Closed by aarzilli** 2023-10-01 05:39 UTC

**Comment by firelizzard18** [comment] 2023-10-01 16:14
Thanks, using `master` resolves the issue for me
