### ISSUE TITLE
Propose: named "b" == "set breaakpoint on the current line"

### ISSUE THREAD

**Issue by thockin** [go-delve/delve#2862] opened 2022-01-04 19:08 UTC
1. What version of Delve are you using (`dlv version`)?

```
$ dlv version
Delve Debugger
Version: 1.8.0
Build: $Id: 6a6c9c332d5354ddf1f8a2da3cc477bd18d2be53 $
```

2. What version of Go are you using? (`go version`)?

```
$ go version
go version go1.17 linux/amd64

$ gotip version
go version devel go1.18-b357b05b Thu Dec 23 20:03:38 2021 +0000 linux/amd64
```

3. What operating system and processor architecture are you using?

Linux AMD64

4. What did you do?

Wanted to set a breaakpoint on the current line.  typed "b<enter>".  Got an error.  This seems like  something dlv could infer, similar to GDB

5. What did you expect to see?

A breakpoint

6. What did you see instead?

An error :)

**Comment by aarzilli** [comment] 2022-01-04 19:10
Duplicate of #2788

**Closed by aarzilli** 2022-01-04 19:10 UTC
