### ISSUE TITLE
dlv does not load code changes?

### ISSUE THREAD

**Issue by dongwangdw** [go-delve/delve#1980] opened 2020-04-02 14:04 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
1.4.0
2. What version of Go are you using? (`go version`)?
1.13.5
3. What operating system and processor architecture are you using?
x86, ubuntu 18.04
4. What did you do?
dlv debug mypackage
5. What did you expect to see?
I expect to see the changes I made in the code.
6. What did you see instead?
but I did see the code not changed.

Did I missed anything?

**Comment by dongwangdw** [comment] 2020-04-02 14:40
As I found, it only presents the changes in main.go, not other packages changes. 
Is this expected?

**Comment by derekparker** [comment] 2020-04-02 16:09
This is a duplicate of #1551 and is being worked on via https://github.com/go-delve/delve/pull/1971.

**Closed by derekparker** 2020-04-02 16:09 UTC
