### ISSUE TITLE
Don't stop breakpoint  (could not find file )

### ISSUE THREAD

**Issue by Jiw0cha** [go-delve/delve#2534] opened 2021-06-11 13:07 UTC
Hello.
```
dlv version
Delve Debugger
Version: 1.6.1
Build: $Id: 114218c22f3791287c4bc2f4ff35a846a1416ee9

go version
go version go1.16.3 linux/amd64
```
I use vscodium 
```
launch.json:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${workspaceFolder}",
	   "trace": "log",
            "args": []
        }
    ]
}
```
log:
```
Running: /home/user/go/goproj/bin/dlv debug --headless=true --listen=127.0.0.1:28008 --api-version=2
API server listening at: 127.0.0.1:28008
InitializeEvent
SetBreakPointsRequest
Debuggee is not running. Setting breakpoints without halting.
All cleared
Creating on: /home/user/go/goproj/src/parallel/test.go:119
Error on CreateBreakpoint: could not find file  /home/user/go/goproj/src/parallel/test.go
```
Are there ways to solve this?

**Comment by aarzilli** [comment] 2021-06-11 13:52
It looks like parallel/test.go is not part of the program you are debugging, excluded either by a build tag or because nothing inside it is being used.

**Comment by Jiw0cha** [comment] 2021-06-12 23:15
> It looks like parallel/test.go is not part of the program you are debugging, excluded either by a build tag or because nothing inside it is being used.

If use from cmd and full path to test.go (not work):

```
dlv debug --listen=127.0.0.1:10229 --api-version=2
break bk232533636 /home/user/go/goproj/src/parallel/test.go:114
Command failed: location "/home/user/go/goproj/src/parallel/test.go:114" not found
```
If use from cmd and NOT full path to test.go (work):
```
dlv debug --listen=127.0.0.1:10229 --api-version=2
Type 'help' for list of commands.
(dlv) break bk232533636 test.go:114
Breakpoint bk232533636 (enabled) set at 0x71dceb for main.main.func1() parallel/test.go:114
```
have ideas how to fix it in  vscodium?

**Comment by aarzilli** [comment] 2021-06-13 07:35
Duplicate of https://github.com/go-delve/delve/issues/2526

**Closed by aarzilli** 2021-06-13 07:35 UTC
Labels: kind/needs more info

**Comment by Jiw0cha** [comment] 2021-06-13 11:42
> Duplicate of #2526

Thank you. I don't use symlink. I found solution, add config:

```
"substitutePath": [{"from": "/home/user/go/goproj/src/parallel/", "to": "parallel/"}],
```
