### ISSUE TITLE
Functions not found in program with CGO on windows

### ISSUE THREAD

**Issue by nd** [go-delve/delve#2786] opened 2021-11-11 14:54 UTC
1. What version of Delve are you using (`dlv version`)?

Delve Debugger
Version: 1.7.2
Build: $Id: 5b6f24e7fbcad3fe3bc574d3763b2f20afa1d6a1 $

2. What version of Go are you using? (`go version`)?

go version go1.17.3 windows/amd64

3. What operating system and processor architecture are you using?

windows 10/amd64 

4. What did you do?

Compiled program with CGO (with gcc in path, gcc version: gcc (Rev2, Built by MSYS2 project) 11.2.0) using 'go build -o exe -gcflags "all=-N -l" cgo'

```
package main

/*
 const int a=1;
*/
import "C"

func F() {
	println("ok")
}

func main() {
	println("ok")
}
```

Ran 'dlv exec exe' and executed funcs command.

5. What did you expect to see?

At least main and F

6. What did you see instead?

No funcs.

**Comment by aarzilli** [comment] 2021-11-11 14:57
I wouldn't expect to see F, it isn't called and the deadcode pass of the linker will remove it, main should be there. I think there is some problem with mingw 11, it did break our tests. Can you send me the executable?

**Comment by nd** [comment] 2021-11-11 15:06
https://drive.google.com/file/d/1NIrPxMmIaEIwjtfqDVPou4p6Y3szYFqz/view?usp=sharing

**Comment by nd** [comment] 2021-11-11 15:10
Also noticed that target version is missing:

```
2021-11-11 09:23:09,734 [ 317970]  DEBUG -           #com.goide.dlv.DlvVm - OUT: {"method":"RPCServer.GetVersion","params":[{}],"id":2} 
2021-11-11 09:23:09,735 [ 317971]  DEBUG -           #com.goide.dlv.DlvVm - IN: {"id":2,"result":{"DelveVersion":"Version: 1.7.2\nBuild: c207db792a0757e8db7420d6729b3da2608c5f31","APIVersion":2,"Backend":"native","TargetGoVersion":"","MinSupportedVersionOfGo":"1.15.0","MaxSupportedVersionOfGo":"1.17.0"},"error":null} 
```

**Comment by aarzilli** [comment] 2021-11-11 15:14
Blind guess: gcc switched to dwarf5, go still produces dwarf4 and the linker messes everything up. Haven't looked yet.

**Comment by nd** [comment] 2021-11-11 15:27
It looks like dwarf5 was used, but setting `CGO_CFLAGS=-gdwarf-4` doesn't help.

**Comment by LomikXP** [comment] 2021-11-12 07:08
> https://drive.google.com/file/d/1NIrPxMmIaEIwjtfqDVPou4p6Y3szYFqz/view?usp=sharing

One more thought:
gdb has sources in this file, dlv is not

**Comment by aarzilli** [comment] 2021-11-15 09:51
Upstream issue: https://github.com/golang/go/issues/49590

**Comment by LomikXP** [comment] 2021-11-15 10:00
> > https://drive.google.com/file/d/1NIrPxMmIaEIwjtfqDVPou4p6Y3szYFqz/view?usp=sharing
> 
> One more thought: gdb has sources in this file, dlv is not

@aarzilli May I ask why gdb can work with example exe (sources visible and breakpoints can be set), but in Delve was not?

**Comment by aarzilli** [comment] 2021-11-15 10:03
Because the problem is on reading debug_info, not on writing it.

**Comment by LomikXP** [comment] 2021-11-15 10:04
> Because the problem is on reading debug_info, not on writing it.

gdb was reading it too or not?

**Comment by aarzilli** [comment] 2021-12-08 14:17
I'm going to close this. The fixes on both our side and on go's side have been merged. It just so happens that delve will need to be built with (as of yet unreleased) go 1.18 to read executables built with recent versions of gcc on windows (or macos).

**Closed by aarzilli** 2021-12-08 14:17 UTC
Labels: os/windows, area/proc, kind/upstream
