### ISSUE TITLE
could not launch process on m1

### ISSUE THREAD

**Issue by jay-wlj** [go-delve/delve#2538] opened 2021-06-16 03:59 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.6.1
Build: $Id: 114218c22f3791287c4bc2f4ff35a846a1416ee9 $

2. What version of Go are you using? (`go version`)?
go version go1.16.5 darwin/arm64

3. What operating system and processor architecture are you using?
MacBook Air (M1, 2020) Big Sur 11.3.1 

4. What did you do?
Try to run go application
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "GoLaunch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${fileDirname}",
            "env": {
            },
            "backend": "native",
            "args":["start"],
            "dlvLoadConfig": {
                // "followPointers": true,
                "maxVariableRecurse": 1,
                "maxStringLen": 512,
                "maxArrayValues": 64,
                "maxStructFields": -1
            }
        }
    ]
}
```
5. What did you expect to see?
```
API server listening at: 127.0.0.1:28991
could not launch process: stub exited while waiting for connection: exit status 0
```
and i run
```
jayden@MacBook-Jayden hty % CGO_ENABLED=0 arch -arch arm64 dlv debug --log --headless .
API server listening at: 127.0.0.1:54482
2021-06-16T11:56:32+08:00 info layer=debugger launching process with args: [/opt/go/src/hty/__debug_bin]
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1205.0.27
 for arm64.
Got a connection, launched process /opt/go/src/hty/__debug_bin (pid = 2185).
2021-06-16T11:56:32+08:00 warning layer=debugger debug_frame workaround not applied: function internal/cpu.Initialize (at 0x104459070) covered by 0x104459070-0x1044590c0
```

How I can launch dlv with arm64 mod ?

**Comment by aarzilli** [comment] 2021-06-16 05:43
What is the problem exactly? You posted two transcripts but the second one is normal and the first one can't be happening if the second one does.

**Comment by aloooha** [comment] 2021-06-19 11:17
same version and same error

**Comment by derekparker** [comment] 2021-07-22 15:09
Can someone who is experiencing this error please post a full session transcript so we can more clearly see what the error is?

**Comment by polinasok** [comment] 2021-07-22 22:40
This reminds me of golang/vscode-go#1637

**Comment by aarzilli** [comment] 2021-08-04 08:05
Closing, no user feedback. The problem is probably that when running delve from vscode the wrong architecture gets specified, i.e. https://github.com/golang/vscode-go/issues/1637

**Closed by aarzilli** 2021-08-04 08:05 UTC
Labels: kind/needs more info
