### ISSUE TITLE
Catch fatal errors logic doesn't work on mac

### ISSUE THREAD

**Issue by nd** [go-delve/delve#1507] opened 2019-03-07 21:01 UTC
1. What version of Delve are you using (`dlv version`)?

built on commit ac3b1c7a786d681a5aefcdded9888090d69b3832

2. What version of Go are you using? (`go version`)?

go version go1.12 darwin/amd64

3. What operating system and processor architecture are you using?

MacOS 10.12.5

4. What did you do?

Debugged this program:

```
package main

type myIface interface {
	Done() <-chan struct{}
}

func main() {
	var bar myIface
	<-bar.Done()
}
```

5. What did you expect to see?

I expected that continue command will stop inside `runtime.fatalpanic` like it does on linux

6. What did you see instead?

The continue command returns an error. Rpc log:

```
time="2019-03-07T21:41:41+01:00" level=debug msg="<- RPCServer.FindLocation(rpc2.FindLocationIn{\"Scope\":{\"GoroutineID\":-1,\"Frame\":0,\"DeferredCall\":0},\"Loc\":\"main.main\"})" layer=rpc
time="2019-03-07T21:41:41+01:00" level=debug msg="-> *rpc2.FindLocationOut{\"Locations\":[{\"pc\":17120239,\"file\":\"/Users/nd/go/src/github.com/nd/awesomeProject/main.go\",\"line\":7,\"function\":{\"name\":\"main.main\",\"value\":17120224,\"type\":0,\"goType\":0,\"optimized\":false}}]} error: \"\"" layer=rpc
time="2019-03-07T21:41:41+01:00" level=debug msg="(async 2) <- RPCServer.Command(api.DebuggerCommand{\"name\":\"continue\",\"ReturnInfoLoadConfig\":null})" layer=rpc
time="2019-03-07T21:41:41+01:00" level=debug msg="(async 2) -> <nil>null error: \"bad access\"" layer=rpc
```

Gdbwire + rpc log can be found here: https://gist.github.com/nd/bea6530fd08cd5062bc2e8fdec25c3bc

**Comment by aarzilli** [comment] 2019-03-07 21:11
Duplicate of #852

**Closed by aarzilli** 2019-03-07 21:11 UTC
