### ISSUE TITLE
Missing debug_info entries and text symbols for some functions on macOS with cgo

### ISSUE THREAD

**Issue by diffmike** [go-delve/delve#1635] opened 2019-07-26 07:53 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
1.2.0
2. What version of Go are you using? (`go version`)?
1.12.7
3. What operating system and processor architecture are you using?
Mac OS 10.14.5, darwin/amd64
4. What did you do?
I've tried to set breakpoint in the nested packages of my project by
`break <project>/cmd/root.go:28`
5. What did you expect to see?
Breakpoint is set
6. What did you see instead?
`Command failed: could not find /Users/<user>/Projects/go/src/<project>/cmd/root.go:28` 
(this file exists)

It works fine with main.go in the project root: 
```
(dlv) break <project>/main.go:6
Breakpoint 1 set at 0x49d331b for main.main() ./main.go:6
```
But doesn't work with any packages inside.

**Comment by aarzilli** [comment] 2019-07-26 11:50
How are you running delve? `dlv debug` or `dlv exec` on a prebuilt file? What happens if you do `disass <name of the function in root.go:28>`?

**Comment by diffmike** [comment] 2019-07-26 12:02
I use `dlv debug`

> What happens if you do disass <name of the function in root.go:28>?
```
(dlv) disass -l cmd.Execute
Command failed: Location "cmd.Execute" not found
```
However it works fine with modules in the project:
```
(dlv) disass -l cobra.Execute
TEXT github.com/spf13/cobra.(*Command).Execute(SB) /Users/<user>/Projects/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go
	command.go:799	0x4348740	65488b0c2530000000	mov rcx, qword ptr gs:[0x30]
...
```

**Comment by aarzilli** [comment] 2019-07-26 16:01
Are you sure that function gets called at all? You can get a list of functions in your program with `funcs`. For example `funcs Execute` will list all functions that exist in the program containing the word 'Execute'.

**Comment by diffmike** [comment] 2019-07-26 16:09
You right, there no this function with `funcs` output
```
(dlv) funcs Execute
github.com/aws/aws-sdk-go/service/ssm.(*AutomationExecution).SetExecutedBy
github.com/aws/aws-sdk-go/service/ssm.(*AutomationExecutionMetadata).SetExecutedBy
github.com/go-sql-driver/mysql.(*mysqlStmt).writeExecutePacket
github.com/jmespath/go-jmespath.(*treeInterpreter).Execute
github.com/spf13/cobra.(*Command).Execute
github.com/spf13/cobra.(*Command).ExecuteC
regexp.(*Regexp).doExecute
text/template.(*Template).Execute
text/template.(*Template).ExecuteTemplate
(dlv) exit
```
But how it is possible if this is the only function the in main?
```
> cat main.go
package main

import "<project>/cmd"

func main() {
	cmd.Execute()
}
```

**Comment by aarzilli** [comment] 2019-07-26 16:46
I don't know, you could disassemble main.main and see what it does.

**Comment by diffmike** [comment] 2019-07-26 17:47
Unfortunately there no useful information for me, maybe you can see it?
```
(dlv) disass -l main.main
TEXT main.main(SB) /<project-path>/main.go
	main.go:5	0x49d3300	65488b0c2530000000	mov rcx, qword ptr gs:[0x30]
	main.go:5	0x49d3309	483b6110		cmp rsp, qword ptr [rcx+0x10]
	main.go:5	0x49d330d	761a			jbe 0x49d3329
	main.go:5	0x49d330f	4883ec08		sub rsp, $C.sqlite3Hooks+8
	main.go:5	0x49d3313	48892c24		mov qword ptr [rsp], rbp
	main.go:5	0x49d3317	488d2c24		lea rbp, ptr [rsp]
	main.go:6	0x49d331b	e830aeffff		call $C.sqlite3Hooks+77390160
	main.go:7	0x49d3320	488b2c24		mov rbp, qword ptr [rsp]
	main.go:7	0x49d3324	4883c408		add rsp, $C.sqlite3Hooks+8
	main.go:7	0x49d3328	c3			ret
	main.go:5	0x49d3329	e8b2d868ff		call $runtime.morestack_noctxt
	main.go:5	0x49d332e	ebd0			jmp $main.main
(dlv)
```

here is the main.go content:
```
     1	package main
     2
     3	import "license-api/cmd"
     4
     5	func main() {
     6		cmd.Execute()
     7	}
```

**Comment by derekparker** [comment] 2019-07-26 18:21
@diffmike can you post the contents of `cmd.Execute()`? It looks like there is not `CALL` instruction, I'm wondering if the entire thing is still being inlined for some reason.

**Comment by diffmike** [comment] 2019-07-26 18:46
@derekparker here it is:
```
var rootCmd = &cobra.Command{
	Use:   "license",
	Short: "License API",
	PersistentPreRun: func(cmd *cobra.Command, args []string) {
		if verbose, _ := cmd.Flags().GetBool("verbose"); verbose {
			logrus.SetLevel(logrus.DebugLevel)
		}
	},
}

func Execute() {
	if err := rootCmd.Execute(); err != nil {
		logrus.Fatal(err)
	}
}
```
It works for main and works for modules (for example if I set breakpoint in the cobra.Command.Execute() - it works fine despite it called from my cmd.Execute() where it doesn't work)

**Comment by derekparker** [comment] 2019-07-26 19:46
@diffmike hmm, something seems really off here.

In the assembly you posted I'm seeing references to CGO and sqlite, but in the command it's all logrus. Are you using sqlite at all in your program? Where is that coming from?

**Comment by aarzilli** [comment] 2019-07-27 06:56
The `C.sqlite3Hooks` is a red herring, it's probably just a symbol with a zero address that's tricking our disassembler (we should eventually do something about that). This is interesting:

```
	main.go:6	0x49d331b	e830aeffff		call $C.sqlite3Hooks+77390160
```

because it's calling a function for which we don't have a symbol. The next step would be to look through the output of `objdump --dwarf` and see if there's an entry for cmd.Execute there and what it looks like. It should have a low pc of 0x49ce150. Either the linker has a problem or we do.

**Comment by diffmike** [comment] 2019-07-27 08:47
@derekparker I use GORM and mysql and as primary db type and sqlite in memory as a db for tests, here is for it loads:
```
package db

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
	"github.com/pkg/errors"
)

type Database struct {
	*gorm.DB
}

func New(config *Config) (*Database, error) {
	db, err := gorm.Open(config.DatabaseType, config.DatabaseURI)
	if err != nil {
		return nil, errors.Wrap(err, "unable to connect to database")
	}
	return &Database{db}, nil
}
```
When I comment out sqlite import `_ "github.com/jinzhu/gorm/dialects/sqlite"` debugging started to work! So the issue somewhere there. It is still the issue in my case as conditional import is impossible as well as have tests with sqlite and debug together :(

@aarzilli I don't have much experience with disassembling, as I understand I need to use assemble sources for the `objdump --dwarf`. Where I can take them?

**Comment by aarzilli** [comment] 2019-07-27 08:53
Objdump doesn't take assembly sources, it uses the executable file.

1. Build your project with `go build --gcflags='all=-N -l'`
2. Run `objdump --dwarf path_to_executable | grep -A10 cmd.Execute`

I might need to see the executable file directly to fix this.

**Comment by diffmike** [comment] 2019-07-27 10:11
@aarzilli  it doesn't work for me:
1. `go build --gcflags='all=-N -l' -o debug`
2. 
```
/usr/local/opt/binutils/bin/objdump --dwarf debug
debug:     file format mach-o-x86-64
```
I've sent you an executable file to your email, hopefully it will be useful.

**Comment by aarzilli** [comment] 2019-07-27 11:16
cc @heschik 

The problem is definitely upstream from delve. I've looked at the executable you sent me and the debug_info entry for cmd.Execute is missing. Not only that it doesn't have a text symbol for it either.

The call in main.main to cmd.Execute ends up pointing inside a different text symbol that's clearly concatenating multiple actual functions, so it isn't that cmd.Execute was inlined or pruned by the linker, it's there but all informations about it were lost during link.

Given that dropping sqlite makes things work I suspect that the problem is in the external linker path of cmd/link and that it probably isn't an issue with dsymutil but rather with the step before that, the symbols get lost when calling ld and then dsymutil gets rid of the debug_info entries too (because it can't find the associated symbol).

@diffmike do I have permission to share the executable you sent me with the goteam / @heschik ?

**Comment by diffmike** [comment] 2019-07-27 13:19
Yes, you can share it with the goteam @aarzilli 
thanks

**Comment by heschik** [comment] 2019-07-27 19:07
Would you mind filing an upstream Go issue? Ideally, the form would be "when I do this I get a binary that's missing this symbol", including a repro from source. The binary is better than nothing, but it'd be much easier to trace the whole build process from source.

**Comment by diffmike** [comment] 2019-07-28 16:46
@heschik unfortunately I can't share full source code, I've tried to reproduce the issue with basic project based on the source, included only initial functionality but I can't reproduce with it. 
So, if it is still make sense tell me please how I need to create the issue in the Go repo. Most likely @aarzilli can provide more details than me.

**Comment by jeremyfaller** [comment] 2019-07-29 18:41
Bummer about the lack of source, or reproducability. If the best you can do is the binary, ok let's start there. If you can include the object files (which is basically the same as the binary), that would also help.

**Comment by diffmike** [comment] 2019-08-06 16:46
@jeremyfaller I can't create object files, looks like because of the same issue as for debug:
```
go tool compile -o build/compile main.go
main.go:3:8: can't find import: "<project>/cmd"
```
btw if I do build it works fine

**Comment by aarzilli** [comment] 2019-08-10 15:45
To get the object files you have to do `go build -work -a` they will be inside the directory it prints to stderr.

**Comment by diffmike** [comment] 2019-08-12 14:20
thanks @aarzilli, here are compressed object files
[go-build958174054.zip](https://github.com/go-delve/delve/files/3492879/go-build958174054.zip)

**Comment by aarzilli** [comment] 2019-08-13 12:55
cc @jeremyfaller

**Comment by jeremyfaller** [comment] 2019-08-13 13:20
sorry, I'll take a look today.

**Comment by jeremyfaller** [comment] 2019-08-13 14:46
So, took a look at this this AM. As near as I can tell, the go linker is handing off the correct symbols to the external linker, and ld is losing the symbols. It looks like the external linker is dropping lots of "license-api" symbols, and (strangely enough) "log." symbols. It looks to me like the code is there in the text section, it's just a problem with the darwin linker dropping the symbols.

This is a curious bug, but AFAICT not in the go linker.

Not sure what the next steps are here to help you, @diffmike. Cursory googling doesn't result in any obvious darwin-linker issues related to this.

**Comment by jeremyfaller** [comment] 2019-08-13 14:54
The following are the symbols that look like they're stripped in the output from the external linker


[stripped_symbols.zip](https://github.com/go-delve/delve/files/3497533/stripped_symbols.zip)

**Comment by aarzilli** [comment] 2019-08-13 15:25
I'm thinking somebody should tell apple, not sure how or where.

**Comment by jeremyfaller** [comment] 2019-08-13 19:00
I've filed a bug with Apple, but I don't have a public link I can share. I'll update here as I know more.

**Comment by jeremyfaller** [comment] 2019-08-19 17:44
Nothing to report from Apple yet.

**Comment by jeremyfaller** [comment] 2019-08-23 20:01
I heard back from Apple. I've copied their response below:

![Screen Shot 2019-08-23 at 3 47 27 PM](https://user-images.githubusercontent.com/3063869/63619689-5b22aa00-c5bd-11e9-8a37-4b645cde7b61.png)

Basically, the Go compiler/linker should emit mangled symbols. I'll create an upstream bug.

@aarzilli Is there anything beyond this needed on your end if we emit mangled symbols?

**Comment by aarzilli** [comment] 2019-08-23 20:04
> Is there anything beyond this needed on your end if we emit mangled symbols?

Probably not.

**Comment by jeremyfaller** [comment] 2019-08-23 20:16
Upstream issue:

https://github.com/golang/go/issues/33808

**Closed** 2019-08-24 05:04 UTC
Labels: kind/upstream

**Comment by jeremyfaller** [comment] 2019-09-18 19:28
This should be fixed upstream. If you grab go at HEAD, you should be able to debug this now.

Thanks for reporting!
