### ISSUE TITLE
Get failed on Apple Silicon ARM

### ISSUE THREAD

**Issue by ddok2** [go-delve/delve#3123] opened 2022-08-25 08:16 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)?
```
$ dlv version
Delve Debugger
Version: 1.9.1
Build: $Id: d81b9fd12bfa603f3cf7a4bc842398bd61c42940 $
```

2. What version of Go are you using? (`go version`)?
```
$ go version
go version go1.18.5 darwin/arm64
```

3. What operating system and processor architecture are you using?
```
$ sw_vers
ProductName:	macOS
ProductVersion:	12.5.1
BuildVersion:	21G83

$ uname -a
Darwin syna 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64
```

4. What did you do?
```
$ dlv debug hello.go
```

5. What did you expect to see?
```
$ dlv debug hello.go
Type 'help' for list for commands.
```

6. What did you see instead?
```
$ dlv debug hello.go
could not launch process: stub exited while waiting for connection: exit status 0

# on Goland
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1316.0.9.46
 for arm64.
error: failed to launch process /Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver: failed to get the task for process 80064
Exiting.
could not launch process: stub exited while waiting for connection: exit status 0

```

**Comment by aarzilli** [comment] 2022-08-25 13:48
Duplicate of #3056. Either you didn't follow the installation instructions, you are trying to debug through ssh (which apple does not allow) or your install of xcode is broken and you should talk to apple.

**Closed by aarzilli** 2022-08-25 13:48 UTC

**Comment by ddok2** [comment] 2022-08-26 05:16
@aarzilli  you're right. it was a local problem with`debugserver` and  `security tool`. thanks for response.

**Comment by booom** [comment] 2022-09-28 12:12
> 

how did you fix the local problem with debugserver and security tool ? please show it🙏
