### ISSUE TITLE
ArchInst undefined error on ubuntu

### ISSUE THREAD

**Issue by GSCSW** [go-delve/delve#1706] opened 2019-10-03 23:58 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
2. What version of Go are you using? (`go version`)?
3. What operating system and processor architecture are you using?
4. What did you do?
5. What did you expect to see?
6. What did you see instead?

ARM64 VM on AWS
>OS  : Ubuntu 18.04.2 LTS

>go version go1.12.10 linux/arm64
this doesn't look like the 32/64 bit error I see others mentioned.

Steps:
1. on vim do :GoInstallBinaries

error:
>vim-go: dlv not found. Installing github.com/go-delve/delve/cmd/dlv to folder /home/ubuntu/go/bin/
>vim-go: Error installing github.com/go-delve/delve/cmd/dlv: # github.com/go-delve/delve/pkg/proc
>vim-go: go/src/github.com/go-delve/delve/pkg/proc/disasm.go:10:14: undefined: archInst

**Comment by aarzilli** [comment] 2019-10-04 12:58
Duplicate of #118

**Closed by aarzilli** 2019-10-04 12:58 UTC
