### ISSUE TITLE
Installing github.com/go-delve/delve/cmd/dlv@master FAILED

### ISSUE THREAD

**Issue by oSethoum** [go-delve/delve#2820] opened 2021-12-08 12:06 UTC
Failed in installing the package by go extension : 

OS: Linux Lite 5 
vs code: v1.62.3
Go : v1.17.4
Go Extension: v0.29.0

Output : 

``` 
Tools environment: GOPATH=/home/scorpion/go
Installing 1 tool at /home/scorpion/go/bin in module mode.
  dlv-dap

Installing github.com/go-delve/delve/cmd/dlv@master FAILED
{
 "killed": false,
 "code": 2,
 "signal": null,
 "cmd": "/usr/local/go/bin/go build -o /home/scorpion/go/bin/dlv-dap github.com/go-delve/delve/cmd/dlv",
 "stdout": "",
 "stderr": "# github.com/go-delve/delve/service/dap\n/home/scorpion/go/pkg/mod/github.com/go-delve/delve@v1.7.4-0.20211207172355-a4ac69e87df3/service/dap/server.go:502:26: invalid type assertion: s.conn.(net.Conn) (non-interface type *connection on left)\n"
}

1 tools failed to install.

dlv-dap: failed to install dlv-dap(github.com/go-delve/delve/cmd/dlv@master): Error: Command failed: /usr/local/go/bin/go build -o /home/scorpion/go/bin/dlv-dap github.com/go-delve/delve/cmd/dlv
# github.com/go-delve/delve/service/dap
/home/scorpion/go/pkg/mod/github.com/go-delve/delve@v1.7.4-0.20211207172355-a4ac69e87df3/service/dap/server.go:502:26: invalid type assertion: s.conn.(net.Conn) (non-interface type *connection on left)
 
```

Edit : 
No issue with go version 1.17.3.

**Comment by aarzilli** [comment] 2021-12-08 14:13
Duplicate of #2817

**Closed by aarzilli** 2021-12-08 14:13 UTC
