### ISSUE TITLE
Can't set breakpoints in go modules

### ISSUE THREAD

**Issue by AFakeman** [go-delve/delve#1496] opened 2019-02-26 08:16 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

```
Delve Debugger
Version: 1.2.0
Build: $Id: 068e2451004e95d0b042e5257e34f0f08ce01466 $
```

2. What version of Go are you using? (`go version`)?
`go version go1.11.4 darwin/amd64`
3. What operating system and processor architecture are you using?
Mac OS Mojave, `Darwin Kernel Version 18.2.0`
4. What did you do?
I have a project that is a go module (outside of `$GOPATH`), and I ran `dlv debug` and wanted to set a breakpoint, so I typed `b test <source_code_file>:<line>`. Line is inside a function, source code file exists and can be seen with `sources` command.
5. What did you expect to see?
A breakpoint being set
6. What did you see instead?
`Command failed: could not find <source_code_file>:<line>`

**Comment by aarzilli** [comment] 2019-02-26 09:34
The problem is probably in the code generated by the compiler, you should look at the disassembly of the  function containing that line: using `diass -l <function name>` from within delve, or `go tool objdump` outside delve.

**Comment by aarzilli** [comment] 2019-03-07 17:15
Closing, no feedback (sadly)

**Closed by aarzilli** 2019-03-07 17:15 UTC
Labels: kind/needs more info

**Comment by mayongze** [comment] 2019-03-28 16:26
I had the same problem.
