### ISSUE TITLE
use dlv as remote debug server in docker container to start a gin server, which cause gin web server error msg not get printed.

### ISSUE THREAD

**Issue by zw963** [go-delve/delve#3028] opened 2022-06-07 08:51 UTC
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)?

 ╰─ $ dlv version
Delve Debugger
Version: 1.8.2
Build: $Id: dbb493ec14d1e7753504d016b1e1ef1665b75b16 $

3. What version of Go are you using? (`go version`)?
 ╰─ $ go version
go version go1.18 linux/amd64

4. What operating system and processor architecture are you using?

Arch linux

5. What did you do?

I use dlv remote debug ability to start my gin web develop server in docker use docker-compose.

like this:

```
dlv debug --listen=:2345 --continue --headless=true --log --api-version=2 --accept-multiclient .;
```

I assume above just same as `go run .`, but will remote debug.

I want to see gin web developer server error log output to console when server output some error
message, as it done when use `go run .` directly instead.

6. What did you expect to see?
see the error log come from gin web server as `go run .`

8. What did you see instead?
I can only see some debug info. e.g.

[GIN-debug] Listening and serving HTTP on :8080

But error message is not get printed into console.

**Comment by aarzilli** [comment] 2022-06-09 08:51
`dlv debug .` is equivalent to `go build .` and then running the output. It should be fine and the fact that some debug info does get printed shows that the program is running. This doesn't look like a problem with delve.

**Comment by zw963** [comment] 2022-06-14 04:26
> 

Hi, this issue happen when:

before i very first start my application in container, some code was broken which make gin could not start correct.

in this cause, if not load use dlv, we can see those error message in docker compose console, 
but, if load use dlv, all those error message is mute, there is no way to know what issue happen.

**Comment by aarzilli** [comment] 2022-06-14 04:42
Do you have any way I can reproduce this?

**Comment by zw963** [comment] 2022-06-19 06:22
sorry, i can't publish this project, because it is internal company project, but i consider any gin web project will happen.

anyway, when start a server failed use dlv the first time, dlv should redirect the server failed message to stdout, which make
user know something is wrong.

**Comment by aarzilli** [comment] 2022-06-20 11:09
```
% dlv debug --headless --continue --log --api-version=2 --accept-multiclient .
API server listening at: 127.0.0.1:46565
2022-06-20T13:06:55+02:00 info layer=debugger launching process with args: [/home/aa/temp/modtest/__debug_bin]
2022-06-20T13:06:55+02:00 warning layer=debugger can't find build-id note on binary
2022-06-20T13:06:56+02:00 debug layer=debugger continuing
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /ping                     --> main.main.func1 (3 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on 127.0.0.1:6060
[GIN-debug] [ERROR] listen tcp 127.0.0.1:6060: bind: address already in use
2022-06-20T13:06:56+02:00 error layer=rpc writing response:write tcp 127.0.0.1:46565->127.0.0.1:48784: use of closed network connection
```

Works for me, both error and debug messages are printed. If you have a reproducer you can reopen or open a new issue.
Closing, can not reproduce.

**Closed by aarzilli** 2022-06-20 11:09 UTC
Labels: kind/needs more info

**Comment by aarzilli** [comment] 2022-06-20 14:00
The `--log` option will print logging from delve, including those warnings.

**Comment by zw963** [comment] 2022-06-20 14:49
> The `--log` option will print logging from delve, including those warnings.

But, the issue is, when run same dlv command with in docker-compose. i only get logs like this:

```
go: downloading github.com/tyler-smith/go-bip39 v1.1.0
API server listening at: [::]:2345
2022-06-20T14:43:07Z warning layer=rpc Listening for remote connections (connections are not authenticated nor encrypted)
2022-06-20T14:43:07Z info layer=debugger launching process with args: [/app/__debug_bin]
2022-06-20T14:43:08Z warning layer=debugger can't find build-id note on binary
2022-06-20T14:43:08Z debug layer=debugger continuing
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:        export GIN_MODE=release
 - using code:       gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /assets/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] HEAD   /assets/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
2022-06-20T14:43:08Z error layer=rpc writing response:write tcp 127.0.0.1:2345->127.0.0.1:50028: use of closed network connection

```

but what i expected to see is the missing part of original log:

```
panic: html/template: pattern matches no files: `app/views/**/*.html`

goroutine 1 [running]:
html/template.Must(...)
        /home/zw963/Dropbox/linux/utils/go/src/html/template/template.go:374
github.com/gin-gonic/gin.(*Engine).LoadHTMLGlob(0xc0003329c0, {0xbff295, 0x13})
        /home/zw963/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:225 +0x2e6
my_test_code/config/routes.Config()
        /home/zw963/my_test_code/config/routes/routes.go:23 +0x92
main.main()
        /home/zw963/my_test_code/main.go:9 +0x19
exit status 2
```
Those info is more important for me, it told me, the wrong code is place at `/my_test_code/config/routes/routes.go:23 `

Thank you.

**Comment by aarzilli** [comment] 2022-06-20 15:37
You will not see that because that's a fatal panic and delve catches them and stops. You have to remove the relative breakpoint.
